name: Keynote Bench Setup
description: Shared setup for the keynote benchmark job

runs:
  using: composite
  steps:
    - uses: dsherret/rust-toolchain-file@v1

    - name: Set default rust toolchain
      shell: bash
      run: rustup default $(rustup show active-toolchain | cut -d' ' -f1)
