// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

// @ts-ignore
import {
  __SPACETIMEDB__,
  AlgebraicType,
  ProductType,
  BuiltinType,
  ProductTypeElement,
  SumType,
  SumTypeVariant,
  DatabaseTable,
  AlgebraicValue,
  ReducerEvent,
  Identity,
  Address,
  ClientDB,
  SpacetimeDBClient,
} from "../index";

export class OneOffQuery {
  public static tableName = "OneOffQuery";
  public messageId: Uint8Array;
  public queryString: string;

  public static primaryKey: string | undefined = undefined;

  constructor(messageId: Uint8Array, queryString: string) {
    this.messageId = messageId;
    this.queryString = queryString;
  }

  public static serialize(value: OneOffQuery): object {
    return [Array.from(value.messageId), value.queryString];
  }

  public static getAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement(
        "messageId",
        AlgebraicType.createArrayType(
          AlgebraicType.createPrimitiveType(BuiltinType.Type.U8)
        )
      ),
      new ProductTypeElement(
        "queryString",
        AlgebraicType.createPrimitiveType(BuiltinType.Type.String)
      ),
    ]);
  }

  public static fromValue(value: AlgebraicValue): OneOffQuery {
    let productValue = value.asProductValue();
    let __message_id = productValue.elements[0].asBytes();
    let __query_string = productValue.elements[1].asString();
    return new this(__message_id, __query_string);
  }
}

export default OneOffQuery;
