/** SenderError codes thrown by the lobby reducers and helpers. */
export const errors = {
  notAuthorized: 'lobby.not_authorized',
  cannotRemoveLastAdmin: 'lobby.cannot_remove_last_admin',
  configMissing: 'lobby.config_missing',
  invalidPool: 'lobby.invalid_pool',
  invalidSubject: 'lobby.invalid_subject',
  invalidTicketId: 'lobby.invalid_ticket_id',
  invalidWinnerSubject: 'lobby.invalid_winner_subject',
  invalidAttributesJson: 'lobby.invalid_attributes_json',
  invalidMatchSize: 'lobby.invalid_match_size',
  invalidTtlSeconds: 'lobby.invalid_ttl_seconds',
  invalidRating: 'lobby.invalid_rating',
  invalidConfig: 'lobby.invalid_config',
  ticketNotFound: 'lobby.ticket_not_found',
  notTicketOwner: 'lobby.not_ticket_owner',
  ticketNotQueued: 'lobby.ticket_not_queued',
  roomNotFound: 'lobby.room_not_found',
  roomClosed: 'lobby.room_closed',
  roomNotActive: 'lobby.room_not_active',
  seatNotFound: 'lobby.seat_not_found',
  seatLeft: 'lobby.seat_left',
  resultRequiresTwoSeats: 'lobby.result_requires_two_seats',
  winnerNotInRoom: 'lobby.winner_not_in_room',
} as const;
