export { default } from './submodule/schema.js';
export {
  RoomStatus,
  SeatStatus,
  TicketStatus,
  lobbyAdminIdentity,
  lobbyConfig,
  lobbyMatchResult,
  lobbyQueueTicket,
  lobbyRoom,
  lobbyRoomSeat,
  lobbySubjectRating,
  roomStatus,
  seatStatus,
  t,
  ticketStatus,
} from './submodule/schema.js';
export { install } from './submodule/install.js';
export { errors } from './errors.js';
export {
  addLobbyAdmin,
  cancelTicket,
  cancelTicketForSubject,
  closeRoom,
  getLobbyStatus,
  joinQueue,
  joinQueueForSubject,
  joinRankedQueueForSubject,
  joinRoom,
  joinRoomForSubject,
  leaveRoom,
  leaveRoomForSubject,
  lobbyAdminMatchResults,
  lobbyAdminRoomSeats,
  lobbyAdminRooms,
  lobbyAdminTickets,
  lobbyQueueSummary,
  lobbyRankedLeaderboard,
  lobbySweep,
  myLobbyRatings,
  myLobbyRoomSeats,
  myLobbyRooms,
  myLobbyTickets,
  removeLobbyAdmin,
  reportMatchResult,
  setRating,
  updateConfig,
  type JoinQueueArgs,
  type JoinQueueResult,
  type JoinRankedQueueArgs,
  type ReportMatchResultArgs,
  type RoomSubjectArgs,
  type TicketSubjectArgs,
} from './submodule/operations.js';
