// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

@file:Suppress("UNUSED", "SpellCheckingInspection")

package module_bindings

import com.clockworklabs.spacetimedb_kotlin_sdk.shared_client.bsatn.BsatnReader
import com.clockworklabs.spacetimedb_kotlin_sdk.shared_client.bsatn.BsatnWriter

/** Data type `Accounts` from the module schema. */
data class Accounts(
    val id: UInt,
    val balance: Long
) {
    /** Encodes this value to BSATN. */
    fun encode(writer: BsatnWriter) {
        writer.writeU32(id)
        writer.writeI64(balance)
    }

    companion object {
        /** Decodes a [Accounts] from BSATN. */
        fun decode(reader: BsatnReader): Accounts {
            val id = reader.readU32()
            val balance = reader.readI64()
            return Accounts(id, balance)
        }
    }
}

