// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DeleteUniqueIdentityArgs {
    pub i: __sdk::Identity,
}

impl From<DeleteUniqueIdentityArgs> for super::Reducer {
    fn from(args: DeleteUniqueIdentityArgs) -> Self {
        Self::DeleteUniqueIdentity {
            i: args.i,
}
}
}

impl __sdk::InModule for DeleteUniqueIdentityArgs {
    type Module = super::RemoteModule;
}

pub struct DeleteUniqueIdentityCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `delete_unique_identity`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait delete_unique_identity {
    /// Request that the remote module invoke the reducer `delete_unique_identity` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_delete_unique_identity`] callbacks.
    fn delete_unique_identity(&self, i: __sdk::Identity,
) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `delete_unique_identity`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`DeleteUniqueIdentityCallbackId`] can be passed to [`Self::remove_on_delete_unique_identity`]
    /// to cancel the callback.
    fn on_delete_unique_identity(&self, callback: impl FnMut(&super::ReducerEventContext, &__sdk::Identity, ) + Send + 'static) -> DeleteUniqueIdentityCallbackId;
    /// Cancel a callback previously registered by [`Self::on_delete_unique_identity`],
    /// causing it not to run in the future.
    fn remove_on_delete_unique_identity(&self, callback: DeleteUniqueIdentityCallbackId);
}

impl delete_unique_identity for super::RemoteReducers {
    fn delete_unique_identity(&self, i: __sdk::Identity,
) -> __sdk::Result<()> {
        self.imp.call_reducer("delete_unique_identity", DeleteUniqueIdentityArgs { i,  })
    }
    fn on_delete_unique_identity(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &__sdk::Identity, ) + Send + 'static,
    ) -> DeleteUniqueIdentityCallbackId {
        DeleteUniqueIdentityCallbackId(self.imp.on_reducer(
            "delete_unique_identity",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event: __sdk::ReducerEvent {
                        reducer: super::Reducer::DeleteUniqueIdentity {
                            i, 
                        },
                        ..
                    },
                    ..
                } = ctx else { unreachable!() };
                callback(ctx, i, )
            }),
        ))
    }
    fn remove_on_delete_unique_identity(&self, callback: DeleteUniqueIdentityCallbackId) {
        self.imp.remove_on_reducer("delete_unique_identity", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `delete_unique_identity`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_delete_unique_identity {
    /// Set the call-reducer flags for the reducer `delete_unique_identity` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn delete_unique_identity(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_delete_unique_identity for super::SetReducerFlags {
    fn delete_unique_identity(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("delete_unique_identity", flags);
    }
}

