// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DeleteUniqueU32Args {
    pub n: u32,
}

impl From<DeleteUniqueU32Args> for super::Reducer {
    fn from(args: DeleteUniqueU32Args) -> Self {
        Self::DeleteUniqueU32 { n: args.n }
    }
}

impl __sdk::InModule for DeleteUniqueU32Args {
    type Module = super::RemoteModule;
}

pub struct DeleteUniqueU32CallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `delete_unique_u32`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait delete_unique_u_32 {
    /// Request that the remote module invoke the reducer `delete_unique_u32` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_delete_unique_u_32`] callbacks.
    fn delete_unique_u_32(&self, n: u32) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `delete_unique_u32`.
    ///
    /// The [`super::EventContext`] passed to the `callback`
    /// will always have [`__sdk::Event::Reducer`] as its `event`,
    /// but it may or may not have terminated successfully and been committed.
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::EventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`DeleteUniqueU32CallbackId`] can be passed to [`Self::remove_on_delete_unique_u_32`]
    /// to cancel the callback.
    fn on_delete_unique_u_32(
        &self,
        callback: impl FnMut(&super::EventContext, &u32) + Send + 'static,
    ) -> DeleteUniqueU32CallbackId;
    /// Cancel a callback previously registered by [`Self::on_delete_unique_u_32`],
    /// causing it not to run in the future.
    fn remove_on_delete_unique_u_32(&self, callback: DeleteUniqueU32CallbackId);
}

impl delete_unique_u_32 for super::RemoteReducers {
    fn delete_unique_u_32(&self, n: u32) -> __sdk::Result<()> {
        self.imp.call_reducer("delete_unique_u32", DeleteUniqueU32Args { n })
    }
    fn on_delete_unique_u_32(
        &self,
        mut callback: impl FnMut(&super::EventContext, &u32) + Send + 'static,
    ) -> DeleteUniqueU32CallbackId {
        DeleteUniqueU32CallbackId(self.imp.on_reducer(
            "delete_unique_u32",
            Box::new(move |ctx: &super::EventContext| {
                let super::EventContext {
                    event:
                        __sdk::Event::Reducer(__sdk::ReducerEvent {
                            reducer: super::Reducer::DeleteUniqueU32 { n },
                            ..
                        }),
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, n)
            }),
        ))
    }
    fn remove_on_delete_unique_u_32(&self, callback: DeleteUniqueU32CallbackId) {
        self.imp.remove_on_reducer("delete_unique_u32", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `delete_unique_u32`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_delete_unique_u_32 {
    /// Set the call-reducer flags for the reducer `delete_unique_u32` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn delete_unique_u_32(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_delete_unique_u_32 for super::SetReducerFlags {
    fn delete_unique_u_32(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("delete_unique_u32", flags);
    }
}
