// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct InsertPkBoolArgs {
    pub b: bool,
    pub data: i32,
}

impl From<InsertPkBoolArgs> for super::Reducer {
    fn from(args: InsertPkBoolArgs) -> Self {
        Self::InsertPkBool {
            b: args.b,
            data: args.data,
}
}
}

impl __sdk::InModule for InsertPkBoolArgs {
    type Module = super::RemoteModule;
}

pub struct InsertPkBoolCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `insert_pk_bool`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait insert_pk_bool {
    /// Request that the remote module invoke the reducer `insert_pk_bool` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_insert_pk_bool`] callbacks.
    fn insert_pk_bool(&self, b: bool,
data: i32,
) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `insert_pk_bool`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`InsertPkBoolCallbackId`] can be passed to [`Self::remove_on_insert_pk_bool`]
    /// to cancel the callback.
    fn on_insert_pk_bool(&self, callback: impl FnMut(&super::ReducerEventContext, &bool, &i32, ) + Send + 'static) -> InsertPkBoolCallbackId;
    /// Cancel a callback previously registered by [`Self::on_insert_pk_bool`],
    /// causing it not to run in the future.
    fn remove_on_insert_pk_bool(&self, callback: InsertPkBoolCallbackId);
}

impl insert_pk_bool for super::RemoteReducers {
    fn insert_pk_bool(&self, b: bool,
data: i32,
) -> __sdk::Result<()> {
        self.imp.call_reducer("insert_pk_bool", InsertPkBoolArgs { b, data,  })
    }
    fn on_insert_pk_bool(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &bool, &i32, ) + Send + 'static,
    ) -> InsertPkBoolCallbackId {
        InsertPkBoolCallbackId(self.imp.on_reducer(
            "insert_pk_bool",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event: __sdk::ReducerEvent {
                        reducer: super::Reducer::InsertPkBool {
                            b, data, 
                        },
                        ..
                    },
                    ..
                } = ctx else { unreachable!() };
                callback(ctx, b, data, )
            }),
        ))
    }
    fn remove_on_insert_pk_bool(&self, callback: InsertPkBoolCallbackId) {
        self.imp.remove_on_reducer("insert_pk_bool", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `insert_pk_bool`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_insert_pk_bool {
    /// Set the call-reducer flags for the reducer `insert_pk_bool` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn insert_pk_bool(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_insert_pk_bool for super::SetReducerFlags {
    fn insert_pk_bool(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("insert_pk_bool", flags);
    }
}

