// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused)]
use spacetimedb_sdk::{
    self as __sdk,
    anyhow::{self as __anyhow, Context as _},
    lib as __lib, sats as __sats, ws_messages as __ws,
};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct InsertPkI16 {
    pub n: i16,
    pub data: i32,
}

impl __sdk::spacetime_module::InModule for InsertPkI16 {
    type Module = super::RemoteModule;
}

pub struct InsertPkI16CallbackId(__sdk::callbacks::CallbackId);

#[allow(non_camel_case_types)]
pub trait insert_pk_i_16 {
    fn insert_pk_i_16(&self, n: i16, data: i32) -> __anyhow::Result<()>;
    fn on_insert_pk_i_16(
        &self,
        callback: impl FnMut(&super::EventContext, &i16, &i32) + Send + 'static,
    ) -> InsertPkI16CallbackId;
    fn remove_on_insert_pk_i_16(&self, callback: InsertPkI16CallbackId);
}

impl insert_pk_i_16 for super::RemoteReducers {
    fn insert_pk_i_16(&self, n: i16, data: i32) -> __anyhow::Result<()> {
        self.imp.call_reducer("insert_pk_i16", InsertPkI16 { n, data })
    }
    fn on_insert_pk_i_16(
        &self,
        mut callback: impl FnMut(&super::EventContext, &i16, &i32) + Send + 'static,
    ) -> InsertPkI16CallbackId {
        InsertPkI16CallbackId(self.imp.on_reducer::<InsertPkI16>(
            "insert_pk_i16",
            Box::new(move |ctx: &super::EventContext, args: &InsertPkI16| callback(ctx, &args.n, &args.data)),
        ))
    }
    fn remove_on_insert_pk_i_16(&self, callback: InsertPkI16CallbackId) {
        self.imp.remove_on_reducer::<InsertPkI16>("insert_pk_i16", callback.0)
    }
}
