// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused)]
use super::one_timestamp_type::OneTimestamp;
use spacetimedb_sdk::{
    self as __sdk,
    anyhow::{self as __anyhow, Context as _},
    lib as __lib, sats as __sats, ws_messages as __ws,
};

/// Table handle for the table `one_timestamp`.
///
/// Obtain a handle from the [`OneTimestampTableAccess::one_timestamp`] method on [`super::RemoteTables`],
/// like `ctx.db.one_timestamp()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.one_timestamp().on_insert(...)`.
pub struct OneTimestampTableHandle<'ctx> {
    imp: __sdk::db_connection::TableHandle<OneTimestamp>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `one_timestamp`.
///
/// Implemented for [`super::RemoteTables`].
pub trait OneTimestampTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`OneTimestampTableHandle`], which mediates access to the table `one_timestamp`.
    fn one_timestamp(&self) -> OneTimestampTableHandle<'_>;
}

impl OneTimestampTableAccess for super::RemoteTables {
    fn one_timestamp(&self) -> OneTimestampTableHandle<'_> {
        OneTimestampTableHandle {
            imp: self.imp.get_table::<OneTimestamp>("one_timestamp"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct OneTimestampInsertCallbackId(__sdk::callbacks::CallbackId);
pub struct OneTimestampDeleteCallbackId(__sdk::callbacks::CallbackId);

impl<'ctx> __sdk::table::Table for OneTimestampTableHandle<'ctx> {
    type Row = OneTimestamp;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = OneTimestamp> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = OneTimestampInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> OneTimestampInsertCallbackId {
        OneTimestampInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: OneTimestampInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = OneTimestampDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> OneTimestampDeleteCallbackId {
        OneTimestampDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: OneTimestampDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __anyhow::Result<__sdk::spacetime_module::TableUpdate<OneTimestamp>> {
    __sdk::spacetime_module::TableUpdate::parse_table_update_no_primary_key(raw_updates)
        .context("Failed to parse table update for table \"one_timestamp\"")
}
