// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#[allow(unused)]
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct OneF32 {
    pub f: f32,
}

impl TableType for OneF32 {
    const TABLE_NAME: &'static str = "OneF32";
    type ReducerEvent = super::ReducerEvent;
}

impl OneF32 {
    #[allow(unused)]
    pub fn filter_by_f(f: f32) -> TableIter<Self> {
        Self::filter(|row| row.f == f)
    }
}
