// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused)]
use super::vec_u_64_type::VecU64;
use spacetimedb_sdk::{
    self as __sdk,
    anyhow::{self as __anyhow, Context as _},
    lib as __lib, sats as __sats, ws_messages as __ws,
};

/// Table handle for the table `VecU64`.
///
/// Obtain a handle from the [`VecU64TableAccess::vec_u_64`] method on [`super::RemoteTables`],
/// like `ctx.db.vec_u_64()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.vec_u_64().on_insert(...)`.
pub struct VecU64TableHandle<'ctx> {
    imp: __sdk::db_connection::TableHandle<VecU64>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `VecU64`.
///
/// Implemented for [`super::RemoteTables`].
pub trait VecU64TableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`VecU64TableHandle`], which mediates access to the table `VecU64`.
    fn vec_u_64(&self) -> VecU64TableHandle<'_>;
}

impl VecU64TableAccess for super::RemoteTables {
    fn vec_u_64(&self) -> VecU64TableHandle<'_> {
        VecU64TableHandle {
            imp: self.imp.get_table::<VecU64>("VecU64"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct VecU64InsertCallbackId(__sdk::callbacks::CallbackId);
pub struct VecU64DeleteCallbackId(__sdk::callbacks::CallbackId);

impl<'ctx> __sdk::table::Table for VecU64TableHandle<'ctx> {
    type Row = VecU64;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = VecU64> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = VecU64InsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VecU64InsertCallbackId {
        VecU64InsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: VecU64InsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = VecU64DeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VecU64DeleteCallbackId {
        VecU64DeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: VecU64DeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    deletes: Vec<__ws::EncodedValue>,
    inserts: Vec<__ws::EncodedValue>,
) -> __anyhow::Result<__sdk::spacetime_module::TableUpdate<VecU64>> {
    __sdk::spacetime_module::TableUpdate::parse_table_update_no_primary_key(deletes, inserts)
        .context("Failed to parse table update for table \"VecU64\"")
}
