// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class PlayersAtLevelOneHandle : RemoteTableHandle<EventContext, PlayerAndLevel>
        {
            protected override string RemoteTableName => "players_at_level_one";

            internal PlayersAtLevelOneHandle(DbConnection conn) : base(conn)
            {
            }
        }

        public readonly PlayersAtLevelOneHandle PlayersAtLevelOne;
    }
}
