// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ScoresPlayer123Handle : RemoteTableHandle<EventContext, Score>
        {
            protected override string RemoteTableName => "scores_player_123";

            internal ScoresPlayer123Handle(DbConnection conn) : base(conn)
            {
            }
        }

        public readonly ScoresPlayer123Handle ScoresPlayer123;
    }
}
