// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class TestEventHandle : RemoteEventTableHandle<EventContext, TestEvent>
        {
            protected override string RemoteTableName => "test_event";

            internal TestEventHandle(DbConnection conn) : base(conn)
            {
            }
        }

        public readonly TestEventHandle TestEvent;
    }

    public sealed class TestEventCols
    {
        public global::SpacetimeDB.Col<TestEvent, string> Name { get; }
        public global::SpacetimeDB.Col<TestEvent, ulong> Value { get; }

        public TestEventCols(string tableName)
        {
            Name = new global::SpacetimeDB.Col<TestEvent, string>(tableName, "Name");
            Value = new global::SpacetimeDB.Col<TestEvent, ulong>(tableName, "Value");
        }
    }

    public sealed class TestEventIxCols
    {

        public TestEventIxCols(string tableName)
        {
        }
    }
}
