[package]
name = "sdk-csharp-test-harness"
version.workspace = true
edition.workspace = true
license-file = "LICENSE.txt"
description = "A C# SDK test harness for SpacetimeDB clients"

[dev-dependencies]
spacetimedb-testing = { path = "../../crates/testing" }
serial_test.workspace = true

[lints]
workspace = true
