// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::reserve_item_input_type::ReserveItemInput;
use super::reserve_item_output_type::ReserveItemOutput;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
struct ReserveItemForRemoteOrderArgs {
    pub input: ReserveItemInput,
}

impl __sdk::InModule for ReserveItemForRemoteOrderArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the procedure `reserve_item_for_remote_order`.
///
/// Implemented for [`super::RemoteProcedures`].
pub trait reserve_item_for_remote_order {
    fn reserve_item_for_remote_order(&self, input: ReserveItemInput) {
        self.reserve_item_for_remote_order_then(input, |_, _| {});
    }

    fn reserve_item_for_remote_order_then(
        &self,
        input: ReserveItemInput,

        __callback: impl FnOnce(&super::ProcedureEventContext, Result<Result<ReserveItemOutput, String>, __sdk::InternalError>)
            + Send
            + 'static,
    );
}

impl reserve_item_for_remote_order for super::RemoteProcedures {
    fn reserve_item_for_remote_order_then(
        &self,
        input: ReserveItemInput,

        __callback: impl FnOnce(&super::ProcedureEventContext, Result<Result<ReserveItemOutput, String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) {
        self.imp
            .invoke_procedure_with_callback::<_, Result<ReserveItemOutput, String>>(
                "reserve_item_for_remote_order",
                ReserveItemForRemoteOrderArgs { input },
                __callback,
            );
    }
}
