export const errors = {
  notAuthorized: 'agents.not_authorized',
  unknownAgent: 'agents.unknown_agent',
  unknownProvider: 'agents.unknown_provider',
  invalidApiKey: 'agents.invalid_api_key',
  invalidStaleLockThreshold: 'agents.invalid_stale_lock_threshold',
  invalidStaleLockSweepBatch: 'agents.invalid_stale_lock_sweep_batch',
  invalidMaxTurns: 'agents.invalid_max_turns',
  invalidMaxHistory: 'agents.invalid_max_history',
  cannotRemoveLastAdmin: 'agents.cannot_remove_last_admin',
  threadNotFound: 'agents.thread_not_found',
  notThreadOwner: 'agents.not_thread_owner',
  threadBusy: 'agents.thread_busy',
  threadNotRunning: 'agents.thread_not_running',
  tooManyThreads: 'agents.too_many_threads',
  modelNotAllowed: 'agents.model_not_allowed',
  noApiKey: 'agents.no_api_key',
  emptyMessage: 'agents.empty_message',
  regenerateNoUserMessage: 'agents.regenerate_no_user_message',
  providerError: 'agents.provider_error',
  cancelled: 'agents.cancelled',
  maxTurnsExceeded: 'agents.max_turns_exceeded',
} as const;
