version: "3.6"

services:
  node:
    working_dir: /usr/src/app
    image: registry.digitalocean.com/clockwork/spacetimedb${REGISTRY_SUFFIX}:latest
    volumes:
      - /stdb
      - key_files:/etc/spacetimedb
    command: start
    privileged: true
    environment:
      ENV: live
    env_file:
      - .env
    # Turn on core dumps, hopefully.
    ulimits:
      core:
        soft: -1
        hard: -1
    logging:
      options:
        max-size: 1G
    restart: always

  prometheus:
    image: registry.digitalocean.com/clockwork/spacetimedb_prometheus${REGISTRY_SUFFIX}:latest
  grafana:
    image: registry.digitalocean.com/clockwork/spacetimedb_grafana${REGISTRY_SUFFIX}:latest
volumes:
  key_files:
