packages:
  - 'crates/bindings-typescript'
  - 'crates/bindings-typescript/test-app'
  - 'crates/bindings-typescript/case-conversion-test-client'
  - 'templates/chat-react-ts'
  - 'templates/react-ts'
  - 'templates/basic-ts'
  - 'templates/vue-ts'
  - 'templates/tanstack-ts'
  - 'templates/browser-ts'
  - 'templates/svelte-ts'
  - 'templates/angular-ts'
  - 'templates/nuxt-ts'
  - 'templates/remix-ts'
  - 'templates/bun-ts'
  - 'templates/keynote-2'
  - 'modules/benchmarks-ts'
  - 'modules/module-test-ts'
  - 'templates/chat-react-ts/spacetimedb'
  - 'modules/sdk-test-connect-disconnect-ts'
  - 'modules/sdk-test-procedure-ts'
  - 'modules/sdk-test-ts'
  - 'modules/sdk-test-case-conversion-ts'
  - 'docs'
