packages:
  - 'crates/bindings-typescript'
  - 'crates/bindings-typescript/test-app'
  - 'templates/chat-react-ts'
  - 'templates/react-ts'
  - 'templates/basic-ts'
  - 'modules/benchmarks-ts'
  - 'modules/module-test-ts'
  - 'templates/chat-react-ts/spacetimedb'
  - 'modules/sdk-test-connect-disconnect-ts'
  - 'modules/sdk-test-procedure-ts'
  - 'modules/sdk-test-ts'
  - 'docs'
