packages:
  - 'crates/bindings-typescript'
  - 'sdks/typescript'
  - 'sdks/typescript/packages/sdk'
  - 'sdks/typescript/packages/test-app'
  - 'sdks/typescript/examples/quickstart-chat'
  - 'docs'
  - 'cli/create-spacetime'