packages:
  - 'crates/bindings-typescript'
  - 'crates/bindings-typescript/test-app'
  - 'templates/quickstart-chat-typescript'
  - 'templates/basic-react'
  - 'templates/basic-typescript'
  - 'modules/benchmarks-ts'
  - 'modules/module-test-ts'
  - 'templates/quickstart-chat-typescript/spacetimedb'
  - 'modules/sdk-test-connect-disconnect-ts'
  - 'modules/sdk-test-procedure-ts'
  - 'modules/sdk-test-ts'
  - 'docs'
