packages:
  - 'crates/bindings-typescript'
  - 'crates/bindings-typescript/test-app'
  - 'crates/bindings-typescript/examples/quickstart-chat'
  - 'modules/benchmarks-ts'
  - 'modules/module-test-ts'
  - 'modules/quickstart-chat-ts'
  - 'modules/sdk-test-connect-disconnect-ts'
  - 'modules/sdk-test-ts'
  - 'docs'
