// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from '../../index';
import TypeAlias from './type_alias_type';

// The tagged union or sum type for the algebraic type `MiscModuleExport`.
const MiscModuleExport = __t.enum('MiscModuleExport', {
  get TypeAlias() {
    return TypeAlias;
  },
});

export default MiscModuleExport;
