// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "../../lib/type_builders";
import Typespace from "./typespace_type";
import RawTypeDefV10 from "./raw_type_def_v_10_type";
import RawTableDefV10 from "./raw_table_def_v_10_type";
import RawReducerDefV10 from "./raw_reducer_def_v_10_type";
import RawProcedureDefV10 from "./raw_procedure_def_v_10_type";
import RawViewDefV10 from "./raw_view_def_v_10_type";
import RawScheduleDefV10 from "./raw_schedule_def_v_10_type";
import RawLifeCycleReducerDefV10 from "./raw_life_cycle_reducer_def_v_10_type";


// The tagged union or sum type for the algebraic type `RawModuleDefV10Section`.
const RawModuleDefV10Section = __t.enum("RawModuleDefV10Section", {get Typespace() {
    return Typespace;
  },
  get Types() {
    return __t.array(RawTypeDefV10);
  },
  get Tables() {
    return __t.array(RawTableDefV10);
  },
  get Reducers() {
    return __t.array(RawReducerDefV10);
  },
  get Procedures() {
    return __t.array(RawProcedureDefV10);
  },
  get Views() {
    return __t.array(RawViewDefV10);
  },
  get Schedules() {
    return __t.array(RawScheduleDefV10);
  },
  get LifeCycleReducers() {
    return __t.array(RawLifeCycleReducerDefV10);
  },
});

export default RawModuleDefV10Section;


