// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  convertToAccessorMap as __convertToAccessorMap,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type Infer as __Infer,
  type RemoteModule as __RemoteModule,
} from '../../index';
import RawUniqueConstraintDataV9 from './raw_unique_constraint_data_v_9_type';

import * as RawConstraintDataV9Variants from './raw_constraint_data_v_9_variants';

// The tagged union or sum type for the algebraic type `RawConstraintDataV9`.
export default __t.enum('RawConstraintDataV9', {
  unique: RawUniqueConstraintDataV9,
});
