// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ConnectionId as __ConnectionId,
  Identity as __Identity,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type TableHandle as __TableHandle,
} from '../../index';
import { Typespace } from './typespace_type';
// Mark import as potentially unused
declare type __keep_Typespace = Typespace;
import { TableDesc } from './table_desc_type';
// Mark import as potentially unused
declare type __keep_TableDesc = TableDesc;
import { ReducerDef } from './reducer_def_type';
// Mark import as potentially unused
declare type __keep_ReducerDef = ReducerDef;
import { MiscModuleExport } from './misc_module_export_type';
// Mark import as potentially unused
declare type __keep_MiscModuleExport = MiscModuleExport;

export type RawModuleDefV8 = {
  typespace: Typespace;
  tables: TableDesc[];
  reducers: ReducerDef[];
  miscExports: MiscModuleExport[];
};
let _cached_RawModuleDefV8_type_value: __AlgebraicTypeType | null = null;

/**
 * An object for generated helper functions.
 */
export const RawModuleDefV8 = {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    if (_cached_RawModuleDefV8_type_value)
      return _cached_RawModuleDefV8_type_value;
    _cached_RawModuleDefV8_type_value = __AlgebraicTypeValue.Product({
      elements: [],
    });
    _cached_RawModuleDefV8_type_value.value.elements.push(
      {
        name: 'typespace',
        algebraicType: Typespace.getTypeScriptAlgebraicType(),
      },
      {
        name: 'tables',
        algebraicType: __AlgebraicTypeValue.Array(
          TableDesc.getTypeScriptAlgebraicType()
        ),
      },
      {
        name: 'reducers',
        algebraicType: __AlgebraicTypeValue.Array(
          ReducerDef.getTypeScriptAlgebraicType()
        ),
      },
      {
        name: 'miscExports',
        algebraicType: __AlgebraicTypeValue.Array(
          MiscModuleExport.getTypeScriptAlgebraicType()
        ),
      }
    );
    return _cached_RawModuleDefV8_type_value;
  },

  serialize(writer: __BinaryWriter, value: RawModuleDefV8): void {
    __AlgebraicTypeValue.serializeValue(
      writer,
      RawModuleDefV8.getTypeScriptAlgebraicType(),
      value
    );
  },

  deserialize(reader: __BinaryReader): RawModuleDefV8 {
    return __AlgebraicTypeValue.deserializeValue(
      reader,
      RawModuleDefV8.getTypeScriptAlgebraicType()
    );
  },
};

export default RawModuleDefV8;
