// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "../../lib/type_builders";
import AlgebraicType from "./algebraic_type_type";
import ProductType from "./product_type_type";
import FunctionVisibility from "./function_visibility_type";


export default __t.object("RawReducerDefV10", {
  sourceName: __t.string(),
  get params() {
    return ProductType;
  },
  get visibility() {
    return FunctionVisibility;
  },
  get okReturnType() {
    return AlgebraicType;
  },
  get errReturnType() {
    return AlgebraicType;
  },
});


