[package]
name = "spacetimedb-runtime"
version.workspace = true
edition.workspace = true
license-file = "LICENSE"
description = "Runtime and deterministic simulation utilities for SpacetimeDB"
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
tokio.workspace = true
spacetimedb-runtime-core = { workspace = true }
static_assertions = "1.1"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = ["Win32_Storage_FileSystem"] }

[dev-dependencies]
futures.workspace = true

[features]
simulation = ["spacetimedb-runtime-core/sim"]
