<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <AssemblyName>NamespaceEnvironmentAuthLib</AssemblyName>
    <TargetName>$(AssemblyName)</TargetName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../../crates/bindings-csharp/Codegen/Codegen.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" SetTargetFramework="TargetFramework=netstandard2.0;TargetFrameworks=netstandard2.0" GlobalPropertiesToRemove="RuntimeIdentifier;SelfContained;TargetFramework;TargetFrameworks" SkipGetTargetFrameworkProperties="true" />
    <ProjectReference Include="../../../../crates/bindings-csharp/Runtime/Runtime.csproj" SetTargetFramework="TargetFramework=$(TargetFramework);TargetFrameworks=$(TargetFramework)" SkipGetTargetFrameworkProperties="true" />
  </ItemGroup>
</Project>
