// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class AuthUsersHandle : RemoteTableHandle<EventContext, AuthSummary>
        {
            public override string RemoteTableName => "auth_users";

            internal AuthUsersHandle(DbConnection conn) : base(conn)
            {
            }
        }

        public readonly AuthUsersHandle AuthUsers;
    }

    public sealed class AuthUsersCols
    {
        public global::SpacetimeDB.Col<AuthSummary, uint> Score { get; }

        public AuthUsersCols(string tableName)
        {
            Score = new global::SpacetimeDB.Col<AuthSummary, uint>(tableName, "score");
        }
    }

    public sealed class AuthUsersIxCols
    {

        public AuthUsersIxCols(string tableName)
        {
        }
    }
}
