// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.
// <auto-generated />

#nullable enable

using System;
using SpacetimeDB;

namespace SpacetimeDB.Types
{
	[SpacetimeDB.Type]
	public partial class UpdatePlayerInput : IReducerArgs
	{
		string IReducerArgs.ReducerName => "update_player_input";

		public SpacetimeDB.Types.Vector2 Direction = new();
		public float Magnitude;
	}
}
