// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class ConsumeEntityTimerHandle : RemoteTableHandle<EventContext, ConsumeEntityTimer>
        {
            protected override string RemoteTableName => "consume_entity_timer";

            public sealed class ScheduledIdUniqueIndex : UniqueIndexBase<ulong>
            {
                protected override ulong GetKey(ConsumeEntityTimer row) => row.ScheduledId;

                public ScheduledIdUniqueIndex(ConsumeEntityTimerHandle table) : base(table) { }
            }

            public readonly ScheduledIdUniqueIndex ScheduledId;

            internal ConsumeEntityTimerHandle(DbConnection conn) : base(conn)
            {
                ScheduledId = new(this);
            }

            protected override object GetPrimaryKey(ConsumeEntityTimer row) => row.ScheduledId;
        }

        public readonly ConsumeEntityTimerHandle ConsumeEntityTimer;
    }

    public sealed class ConsumeEntityTimerCols
    {
        public global::SpacetimeDB.Col<ConsumeEntityTimer, ulong> ScheduledId { get; }
        public global::SpacetimeDB.Col<ConsumeEntityTimer, SpacetimeDB.ScheduleAt> ScheduledAt { get; }
        public global::SpacetimeDB.Col<ConsumeEntityTimer, int> ConsumedEntityId { get; }
        public global::SpacetimeDB.Col<ConsumeEntityTimer, int> ConsumerEntityId { get; }

        public ConsumeEntityTimerCols(string tableName)
        {
            ScheduledId = new global::SpacetimeDB.Col<ConsumeEntityTimer, ulong>(tableName, "scheduled_id");
            ScheduledAt = new global::SpacetimeDB.Col<ConsumeEntityTimer, SpacetimeDB.ScheduleAt>(tableName, "scheduled_at");
            ConsumedEntityId = new global::SpacetimeDB.Col<ConsumeEntityTimer, int>(tableName, "consumed_entity_id");
            ConsumerEntityId = new global::SpacetimeDB.Col<ConsumeEntityTimer, int>(tableName, "consumer_entity_id");
        }
    }

    public sealed class ConsumeEntityTimerIxCols
    {
        public global::SpacetimeDB.IxCol<ConsumeEntityTimer, ulong> ScheduledId { get; }

        public ConsumeEntityTimerIxCols(string tableName)
        {
            ScheduledId = new global::SpacetimeDB.IxCol<ConsumeEntityTimer, ulong>(tableName, "scheduled_id");
        }
    }
}
