// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteTables
    {
        public sealed class FoodHandle : RemoteTableHandle<EventContext, Food>
        {
            protected override string RemoteTableName => "food";

            public sealed class EntityIdUniqueIndex : UniqueIndexBase<uint>
            {
                protected override uint GetKey(Food row) => row.EntityId;

                public EntityIdUniqueIndex(FoodHandle table) : base(table) { }
            }

            public readonly EntityIdUniqueIndex EntityId;

            internal FoodHandle(DbConnection conn) : base(conn)
            {
                EntityId = new(this);
            }

            protected override object GetPrimaryKey(Food row) => row.EntityId;
        }

        public readonly FoodHandle Food;
    }
}
