// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.
// <auto-generated />

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
	[SpacetimeDB.Type]
	[DataContract]
	public partial class RawSequenceDefV8
	{
		[DataMember(Name = "sequence_name")]
		public string SequenceName = "";
		[DataMember(Name = "col_pos")]
		public uint ColPos;
		[DataMember(Name = "increment")]
		public I128 Increment;
		[DataMember(Name = "start")]
		public I128? Start;
		[DataMember(Name = "min_value")]
		public I128? MinValue;
		[DataMember(Name = "max_value")]
		public I128? MaxValue;
		[DataMember(Name = "allocated")]
		public I128 Allocated;

	}
}
