// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row("MessageViewRow", {
  id: __t.u64().primaryKey().name("id"),
  chatId: __t.u64().name("chat_id"),
  owner: __t.identity().name("owner"),
  role: __t.string().name("role"),
  content: __t.string().name("content"),
  isError: __t.bool().name("is_error"),
  createdAt: __t.timestamp().name("created_at"),
});
