// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Activity = __t.object("Activity", {
  activityId: __t.u64(),
  owner: __t.string(),
  tick: __t.u64(),
  kind: __t.string(),
  message: __t.string(),
  profile: __t.option(__t.string()),
  productId: __t.option(__t.string()),
  variantId: __t.option(__t.string()),
  amountCents: __t.option(__t.u32()),
  createdAt: __t.timestamp(),
});
export type Activity = __Infer<typeof Activity>;

export const BotSession = __t.object("BotSession", {
  sessionId: __t.u64(),
  owner: __t.string(),
  botId: __t.string(),
  tick: __t.u64(),
  profile: __t.string(),
  scenarioId: __t.string(),
  productId: __t.option(__t.string()),
  variantId: __t.option(__t.string()),
  stage: __t.string(),
  revenueCents: __t.u32(),
  reason: __t.string(),
  createdAt: __t.timestamp(),
});
export type BotSession = __Infer<typeof BotSession>;

export const CafeAnalyticsSummary = __t.object("CafeAnalyticsSummary", {});
export type CafeAnalyticsSummary = __Infer<typeof CafeAnalyticsSummary>;

export const CafeConfig = __t.object("CafeConfig", {});
export type CafeConfig = __Infer<typeof CafeConfig>;

export const CafeEcon = __t.object("CafeEcon", {});
export type CafeEcon = __Infer<typeof CafeEcon>;

export const CafeMetrics = __t.object("CafeMetrics", {});
export type CafeMetrics = __Infer<typeof CafeMetrics>;

export const CafeProducts = __t.object("CafeProducts", {});
export type CafeProducts = __Infer<typeof CafeProducts>;

export const CafeQueue = __t.object("CafeQueue", {});
export type CafeQueue = __Infer<typeof CafeQueue>;

export const CafeRecentActivity = __t.object("CafeRecentActivity", {});
export type CafeRecentActivity = __Infer<typeof CafeRecentActivity>;

export const CafeRecentPurchases = __t.object("CafeRecentPurchases", {});
export type CafeRecentPurchases = __Infer<typeof CafeRecentPurchases>;

export const CafeRecentSessions = __t.object("CafeRecentSessions", {});
export type CafeRecentSessions = __Infer<typeof CafeRecentSessions>;

export const CafeScenarios = __t.object("CafeScenarios", {});
export type CafeScenarios = __Infer<typeof CafeScenarios>;

export const CafeVariants = __t.object("CafeVariants", {});
export type CafeVariants = __Infer<typeof CafeVariants>;

export const ContextCafeAnalyticsSummaryRow = __t.object("ContextCafeAnalyticsSummaryRow", {
  queued: __t.u64(),
  delivered: __t.u64(),
  failed: __t.u64(),
});
export type ContextCafeAnalyticsSummaryRow = __Infer<typeof ContextCafeAnalyticsSummaryRow>;

export const ContextCafeDeliveryLogRow = __t.object("ContextCafeDeliveryLogRow", {
  deliveryId: __t.string(),
  source: __t.string(),
  distinctId: __t.string(),
  event: __t.string(),
  ok: __t.bool(),
  statusCode: __t.u16(),
  responseBody: __t.string(),
  attemptedAt: __t.timestamp(),
});
export type ContextCafeDeliveryLogRow = __Infer<typeof ContextCafeDeliveryLogRow>;

export const Econ = __t.object("Econ", {
  owner: __t.string(),
  cashCents: __t.u64(),
  computeUnits: __t.u32(),
  contextUnits: __t.u32(),
  memoryUnits: __t.u32(),
  suppliesSpentCents: __t.u64(),
  stockouts: __t.u32(),
  reputation: __t.u32(),
  workers: __t.u32(),
  machineLevel: __t.u32(),
  seats: __t.u32(),
  storageLevel: __t.u32(),
  reneged: __t.u32(),
  updatedAt: __t.timestamp(),
});
export type Econ = __Infer<typeof Econ>;

export const Metrics = __t.object("Metrics", {
  owner: __t.string(),
  tick: __t.u64(),
  views: __t.u64(),
  carts: __t.u64(),
  checkouts: __t.u64(),
  purchases: __t.u64(),
  abandons: __t.u64(),
  revenueCents: __t.u64(),
  updatedAt: __t.timestamp(),
});
export type Metrics = __Infer<typeof Metrics>;

// The tagged union or sum type for the algebraic type `PostHogOutboxStatus`.
export const PostHogOutboxStatus = __t.enum("PostHogOutboxStatus", {
  Queued: __t.unit(),
  Processing: __t.unit(),
  Delivered: __t.unit(),
  Failed: __t.unit(),
});
export type PostHogOutboxStatus = __Infer<typeof PostHogOutboxStatus>;

export const PosthogDeliveryLogAdmin = __t.object("PosthogDeliveryLogAdmin", {});
export type PosthogDeliveryLogAdmin = __Infer<typeof PosthogDeliveryLogAdmin>;

export const PosthogOutbox = __t.object("PosthogOutbox", {
  outboxId: __t.string(),
  idempotencyKey: __t.option(__t.string()),
  distinctId: __t.string(),
  event: __t.string(),
  propertiesJson: __t.option(__t.string()),
  get status() {
    return PostHogOutboxStatus;
  },
  attempts: __t.u32(),
  claimId: __t.option(__t.string()),
  claimExpiresAtMicros: __t.i64(),
  nextAttemptAt: __t.timestamp(),
  lastStatusCode: __t.option(__t.u16()),
  lastError: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
  deliveredAt: __t.option(__t.timestamp()),
});
export type PosthogOutbox = __Infer<typeof PosthogOutbox>;

export const PosthogOutboxAdmin = __t.object("PosthogOutboxAdmin", {});
export type PosthogOutboxAdmin = __Infer<typeof PosthogOutboxAdmin>;

export const Product = __t.object("Product", {
  key: __t.string(),
  owner: __t.string(),
  productId: __t.string(),
  name: __t.string(),
  category: __t.string(),
  description: __t.string(),
  baseAppeal: __t.u32(),
  active: __t.bool(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Product = __Infer<typeof Product>;

export const ProductTemplate = __t.object("ProductTemplate", {
  productId: __t.string(),
  name: __t.string(),
  category: __t.string(),
  description: __t.string(),
  baseAppeal: __t.u32(),
  active: __t.bool(),
});
export type ProductTemplate = __Infer<typeof ProductTemplate>;

export const Purchase = __t.object("Purchase", {
  purchaseId: __t.u64(),
  owner: __t.string(),
  sessionId: __t.u64(),
  tick: __t.u64(),
  botId: __t.string(),
  profile: __t.string(),
  productId: __t.string(),
  variantId: __t.string(),
  pricePaidCents: __t.u32(),
  createdAt: __t.timestamp(),
});
export type Purchase = __Infer<typeof Purchase>;

export const Scenario = __t.object("Scenario", {
  scenarioId: __t.string(),
  name: __t.string(),
  description: __t.string(),
  trafficPerTick: __t.u32(),
  priceSensitivity: __t.u32(),
  rushBias: __t.u32(),
  researchBias: __t.u32(),
  visualBias: __t.u32(),
  memoryBias: __t.u32(),
  premiumBias: __t.u32(),
  volatility: __t.u32(),
});
export type Scenario = __Infer<typeof Scenario>;

export const SimConfig = __t.object("SimConfig", {
  owner: __t.string(),
  scenarioId: __t.string(),
  tick: __t.u64(),
  experimentKey: __t.string(),
  experimentVariant: __t.option(__t.string()),
  updatedAt: __t.timestamp(),
});
export type SimConfig = __Infer<typeof SimConfig>;

export const Variant = __t.object("Variant", {
  key: __t.string(),
  owner: __t.string(),
  variantId: __t.string(),
  productId: __t.string(),
  name: __t.string(),
  flavor: __t.string(),
  contextTokens: __t.u32(),
  reasoning: __t.u32(),
  latency: __t.u32(),
  priceCents: __t.u32(),
  baselinePriceCents: __t.u32(),
  discountBps: __t.u32(),
  active: __t.bool(),
  featured: __t.bool(),
  updatedAt: __t.timestamp(),
});
export type Variant = __Infer<typeof Variant>;

export const VariantTemplate = __t.object("VariantTemplate", {
  variantId: __t.string(),
  productId: __t.string(),
  name: __t.string(),
  flavor: __t.string(),
  contextTokens: __t.u32(),
  reasoning: __t.u32(),
  latency: __t.u32(),
  priceCents: __t.u32(),
  discountBps: __t.u32(),
  active: __t.bool(),
  featured: __t.bool(),
});
export type VariantTemplate = __Infer<typeof VariantTemplate>;

export const WaitingBot = __t.object("WaitingBot", {
  queueId: __t.u64(),
  owner: __t.string(),
  botId: __t.string(),
  profile: __t.string(),
  scenarioId: __t.string(),
  productId: __t.string(),
  variantId: __t.string(),
  wants: __t.string(),
  thrifty: __t.bool(),
  arrivedTick: __t.u64(),
  createdAt: __t.timestamp(),
});
export type WaitingBot = __Infer<typeof WaitingBot>;

