// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "BTreeU32Type.g.generated.h"

USTRUCT(BlueprintType)
struct TESTCLIENT_API FBTreeU32Type
{
    GENERATED_BODY()

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 N = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    int32 Data = 0;

    FORCEINLINE bool operator==(const FBTreeU32Type& Other) const
    {
        return N == Other.N && Data == Other.Data;
    }

    FORCEINLINE bool operator!=(const FBTreeU32Type& Other) const
    {
        return !(*this == Other);
    }
};

/**
 * Custom hash function for FBTreeU32Type.
 * Combines the hashes of all fields that are compared in operator==.
 * @param BTreeU32Type The FBTreeU32Type instance to hash.
 * @return The combined hash value.
 */
FORCEINLINE uint32 GetTypeHash(const FBTreeU32Type& BTreeU32Type)
{
    uint32 Hash = GetTypeHash(BTreeU32Type.N);
    Hash = HashCombine(Hash, GetTypeHash(BTreeU32Type.Data));
    return Hash;
}

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_ENABLE_TARRAY(FBTreeU32Type);

    UE_SPACETIMEDB_STRUCT(FBTreeU32Type, N, Data);
}
