// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "Types/Builtins.h"
#include "EveryPrimitiveStructType.g.generated.h"

USTRUCT(BlueprintType)
struct TESTCLIENT_API FEveryPrimitiveStructType
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    uint8 A = 0;

    // NOTE: uint16 field not exposed to Blueprint due to non-blueprintable elements
    uint16 B = 0;

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 C = 0;

    // NOTE: uint64 field not exposed to Blueprint due to non-blueprintable elements
    uint64 D = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FSpacetimeDBUInt128 E;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FSpacetimeDBUInt256 F;

    // NOTE: int8 field not exposed to Blueprint due to non-blueprintable elements
    int8 G = 0;

    // NOTE: int16 field not exposed to Blueprint due to non-blueprintable elements
    int16 H = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    int32 I = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    int64 J = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FSpacetimeDBInt128 K;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FSpacetimeDBInt256 L;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    bool M = false;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    float N = 0.0f;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    double O = 0.0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FString P;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FSpacetimeDBIdentity Q;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FSpacetimeDBConnectionId R;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FSpacetimeDBTimestamp S;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FSpacetimeDBTimeDuration T;

    FORCEINLINE bool operator==(const FEveryPrimitiveStructType& Other) const
    {
        return A == Other.A && B == Other.B && C == Other.C && D == Other.D && E == Other.E && F == Other.F && G == Other.G && H == Other.H && I == Other.I && J == Other.J && K == Other.K && L == Other.L && M == Other.M && N == Other.N && O == Other.O && P == Other.P && Q == Other.Q && R == Other.R && S == Other.S && T == Other.T;
    }

    FORCEINLINE bool operator!=(const FEveryPrimitiveStructType& Other) const
    {
        return !(*this == Other);
    }
};

/**
 * Custom hash function for FEveryPrimitiveStructType.
 * Combines the hashes of all fields that are compared in operator==.
 * @param EveryPrimitiveStructType The FEveryPrimitiveStructType instance to hash.
 * @return The combined hash value.
 */
FORCEINLINE uint32 GetTypeHash(const FEveryPrimitiveStructType& EveryPrimitiveStructType)
{
    uint32 Hash = GetTypeHash(EveryPrimitiveStructType.A);
    Hash = HashCombine(Hash, GetTypeHash(EveryPrimitiveStructType.B));
    Hash = HashCombine(Hash, GetTypeHash(EveryPrimitiveStructType.C));
    Hash = HashCombine(Hash, GetTypeHash(EveryPrimitiveStructType.D));
    Hash = HashCombine(Hash, GetTypeHash(EveryPrimitiveStructType.E));
    Hash = HashCombine(Hash, GetTypeHash(EveryPrimitiveStructType.F));
    Hash = HashCombine(Hash, GetTypeHash(EveryPrimitiveStructType.G));
    Hash = HashCombine(Hash, GetTypeHash(EveryPrimitiveStructType.H));
    Hash = HashCombine(Hash, GetTypeHash(EveryPrimitiveStructType.I));
    Hash = HashCombine(Hash, GetTypeHash(EveryPrimitiveStructType.J));
    Hash = HashCombine(Hash, GetTypeHash(EveryPrimitiveStructType.K));
    Hash = HashCombine(Hash, GetTypeHash(EveryPrimitiveStructType.L));
    Hash = HashCombine(Hash, GetTypeHash(EveryPrimitiveStructType.M));
    Hash = HashCombine(Hash, GetTypeHash(EveryPrimitiveStructType.N));
    Hash = HashCombine(Hash, GetTypeHash(EveryPrimitiveStructType.O));
    Hash = HashCombine(Hash, GetTypeHash(EveryPrimitiveStructType.P));
    Hash = HashCombine(Hash, GetTypeHash(EveryPrimitiveStructType.Q));
    Hash = HashCombine(Hash, GetTypeHash(EveryPrimitiveStructType.R));
    Hash = HashCombine(Hash, GetTypeHash(EveryPrimitiveStructType.S));
    Hash = HashCombine(Hash, GetTypeHash(EveryPrimitiveStructType.T));
    return Hash;
}

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_ENABLE_TARRAY(FEveryPrimitiveStructType);

    UE_SPACETIMEDB_STRUCT(FEveryPrimitiveStructType, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T);
}
