// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "Types/Builtins.h"
#include "OneI256Type.g.generated.h"

USTRUCT(BlueprintType)
struct TESTCLIENT_API FOneI256Type
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FSpacetimeDBInt256 N;

    FORCEINLINE bool operator==(const FOneI256Type& Other) const
    {
        return N == Other.N;
    }

    FORCEINLINE bool operator!=(const FOneI256Type& Other) const
    {
        return !(*this == Other);
    }
};

/**
 * Custom hash function for FOneI256Type.
 * Combines the hashes of all fields that are compared in operator==.
 * @param OneI256Type The FOneI256Type instance to hash.
 * @return The combined hash value.
 */
FORCEINLINE uint32 GetTypeHash(const FOneI256Type& OneI256Type)
{
    uint32 Hash = GetTypeHash(OneI256Type.N);
    return Hash;
}

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_ENABLE_TARRAY(FOneI256Type);

    UE_SPACETIMEDB_STRUCT(FOneI256Type, N);
}
