// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/Results/TestClientResultEveryPrimitiveStructString.g.h"
#include "ModuleBindings/Types/EveryPrimitiveStructType.g.h"
#include "ResultEveryPrimitiveStructStringType.g.generated.h"

USTRUCT(BlueprintType)
struct TESTCLIENT_API FResultEveryPrimitiveStructStringType
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FTestClientResultEveryPrimitiveStructString R;

    FORCEINLINE bool operator==(const FResultEveryPrimitiveStructStringType& Other) const
    {
        return R == Other.R;
    }

    FORCEINLINE bool operator!=(const FResultEveryPrimitiveStructStringType& Other) const
    {
        return !(*this == Other);
    }
};

/**
 * Custom hash function for FResultEveryPrimitiveStructStringType.
 * Combines the hashes of all fields that are compared in operator==.
 * @param ResultEveryPrimitiveStructStringType The FResultEveryPrimitiveStructStringType instance to hash.
 * @return The combined hash value.
 */
FORCEINLINE uint32 GetTypeHash(const FResultEveryPrimitiveStructStringType& ResultEveryPrimitiveStructStringType)
{
    uint32 Hash = GetTypeHash(ResultEveryPrimitiveStructStringType.R);
    return Hash;
}

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_ENABLE_TARRAY(FResultEveryPrimitiveStructStringType);

    UE_SPACETIMEDB_STRUCT(FResultEveryPrimitiveStructStringType, R);
}
