// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "Types/Builtins.h"
#include "UniqueUuidType.g.generated.h"

USTRUCT(BlueprintType)
struct TESTCLIENT_API FUniqueUuidType
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FSpacetimeDBUuid U;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    int32 Data = 0;

    FORCEINLINE bool operator==(const FUniqueUuidType& Other) const
    {
        return U == Other.U && Data == Other.Data;
    }

    FORCEINLINE bool operator!=(const FUniqueUuidType& Other) const
    {
        return !(*this == Other);
    }
};

/**
 * Custom hash function for FUniqueUuidType.
 * Combines the hashes of all fields that are compared in operator==.
 * @param UniqueUuidType The FUniqueUuidType instance to hash.
 * @return The combined hash value.
 */
FORCEINLINE uint32 GetTypeHash(const FUniqueUuidType& UniqueUuidType)
{
    uint32 Hash = GetTypeHash(UniqueUuidType.U);
    Hash = HashCombine(Hash, GetTypeHash(UniqueUuidType.Data));
    return Hash;
}

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_ENABLE_TARRAY(FUniqueUuidType);

    UE_SPACETIMEDB_STRUCT(FUniqueUuidType, U, Data);
}
