// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/Optionals/TestClientOptionalInt128.g.h"
#include "Types/Builtins.h"
#include "UniqueOptionI128Type.g.generated.h"

USTRUCT(BlueprintType)
struct TESTCLIENT_API FUniqueOptionI128Type
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FTestClientOptionalInt128 N;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    int32 Data = 0;

    FORCEINLINE bool operator==(const FUniqueOptionI128Type& Other) const
    {
        return N == Other.N && Data == Other.Data;
    }

    FORCEINLINE bool operator!=(const FUniqueOptionI128Type& Other) const
    {
        return !(*this == Other);
    }
};

/**
 * Custom hash function for FUniqueOptionI128Type.
 * Combines the hashes of all fields that are compared in operator==.
 * @param UniqueOptionI128Type The FUniqueOptionI128Type instance to hash.
 * @return The combined hash value.
 */
FORCEINLINE uint32 GetTypeHash(const FUniqueOptionI128Type& UniqueOptionI128Type)
{
    uint32 Hash = GetTypeHash(UniqueOptionI128Type.N);
    Hash = HashCombine(Hash, GetTypeHash(UniqueOptionI128Type.Data));
    return Hash;
}

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_ENABLE_TARRAY(FUniqueOptionI128Type);

    UE_SPACETIMEDB_STRUCT(FUniqueOptionI128Type, N, Data);
}
