// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "Types/Builtins.h"
#include "UniqueIdentityType.g.generated.h"

USTRUCT(BlueprintType)
struct TESTCLIENT_API FUniqueIdentityType
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FSpacetimeDBIdentity I;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    int32 Data = 0;

    FORCEINLINE bool operator==(const FUniqueIdentityType& Other) const
    {
        return I == Other.I && Data == Other.Data;
    }

    FORCEINLINE bool operator!=(const FUniqueIdentityType& Other) const
    {
        return !(*this == Other);
    }
};

/**
 * Custom hash function for FUniqueIdentityType.
 * Combines the hashes of all fields that are compared in operator==.
 * @param UniqueIdentityType The FUniqueIdentityType instance to hash.
 * @return The combined hash value.
 */
FORCEINLINE uint32 GetTypeHash(const FUniqueIdentityType& UniqueIdentityType)
{
    uint32 Hash = GetTypeHash(UniqueIdentityType.I);
    Hash = HashCombine(Hash, GetTypeHash(UniqueIdentityType.Data));
    return Hash;
}

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_ENABLE_TARRAY(FUniqueIdentityType);

    UE_SPACETIMEDB_STRUCT(FUniqueIdentityType, I, Data);
}
