// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit aeeb35f0bbce28430aeeb22691976813dd469e1e).

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "Types/Builtins.h"
#include "UsersType.g.generated.h"

USTRUCT(BlueprintType)
struct TESTCLIENT_API FUsersType
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FSpacetimeDBIdentity Identity;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FString Name;

    FORCEINLINE bool operator==(const FUsersType& Other) const
    {
        return Identity == Other.Identity && Name == Other.Name;
    }

    FORCEINLINE bool operator!=(const FUsersType& Other) const
    {
        return !(*this == Other);
    }
};

/**
 * Custom hash function for FUsersType.
 * Combines the hashes of all fields that are compared in operator==.
 * @param UsersType The FUsersType instance to hash.
 * @return The combined hash value.
 */
FORCEINLINE uint32 GetTypeHash(const FUsersType& UsersType)
{
    uint32 Hash = GetTypeHash(UsersType.Identity);
    Hash = HashCombine(Hash, GetTypeHash(UsersType.Name));
    return Hash;
}

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_ENABLE_TARRAY(FUsersType);

    UE_SPACETIMEDB_STRUCT(FUsersType, Identity, Name);
}
