// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.
// <auto-generated />

#nullable enable

using System;
using SpacetimeDB;

namespace SpacetimeDB.Types
{
	[SpacetimeDB.Type]
	public partial record ClientMessage : SpacetimeDB.TaggedEnum<(
		SpacetimeDB.Types.CallReducer CallReducer,
		SpacetimeDB.Types.Subscribe Subscribe,
		SpacetimeDB.Types.OneOffQuery OneOffQuery
	)>;
}
