// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/Optionals/TestClientOptionalString.g.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "DeleteUniqueOptionString.g.generated.h"

// Reducer arguments struct for DeleteUniqueOptionString
USTRUCT(BlueprintType)
struct TESTCLIENT_API FDeleteUniqueOptionStringArgs
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    FTestClientOptionalString S;

    FDeleteUniqueOptionStringArgs() = default;

    FDeleteUniqueOptionStringArgs(const FTestClientOptionalString& InS)
        : S(InS)
    {}


    FORCEINLINE bool operator==(const FDeleteUniqueOptionStringArgs& Other) const
    {
        return S == Other.S;
    }
    FORCEINLINE bool operator!=(const FDeleteUniqueOptionStringArgs& Other) const
    {
        return !(*this == Other);
    }
};

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_STRUCT(FDeleteUniqueOptionStringArgs, S);
}

// Reducer class for internal dispatching
UCLASS(BlueprintType)
class TESTCLIENT_API UDeleteUniqueOptionStringReducer : public UReducerBase
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    FTestClientOptionalString S;

};


