// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "DeletePkBool.g.generated.h"

// Reducer arguments struct for DeletePkBool
USTRUCT(BlueprintType)
struct TESTCLIENT_API FDeletePkBoolArgs
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    bool B = false;

    FDeletePkBoolArgs() = default;

    FDeletePkBoolArgs(const bool& InB)
        : B(InB)
    {}


    FORCEINLINE bool operator==(const FDeletePkBoolArgs& Other) const
    {
        return B == Other.B;
    }
    FORCEINLINE bool operator!=(const FDeletePkBoolArgs& Other) const
    {
        return !(*this == Other);
    }
};

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_STRUCT(FDeletePkBoolArgs, B);
}

// Reducer class for internal dispatching
UCLASS(BlueprintType)
class TESTCLIENT_API UDeletePkBoolReducer : public UReducerBase
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    bool B = false;

};


