// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "DeleteAllOneU8.g.generated.h"

// Reducer arguments struct for DeleteAllOneU8
USTRUCT(BlueprintType)
struct TESTCLIENT_API FDeleteAllOneU8Args
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    uint8 N = 0;

    FDeleteAllOneU8Args() = default;

    FDeleteAllOneU8Args(const uint8& InN)
        : N(InN)
    {}


    FORCEINLINE bool operator==(const FDeleteAllOneU8Args& Other) const
    {
        return N == Other.N;
    }
    FORCEINLINE bool operator!=(const FDeleteAllOneU8Args& Other) const
    {
        return !(*this == Other);
    }
};

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_STRUCT(FDeleteAllOneU8Args, N);
}

// Reducer class for internal dispatching
UCLASS(BlueprintType)
class TESTCLIENT_API UDeleteAllOneU8Reducer : public UReducerBase
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    uint8 N = 0;

};


