// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/Optionals/TestClientOptionalUInt64.g.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "DeleteAllUniqueOptionU64.g.generated.h"

// Reducer arguments struct for DeleteAllUniqueOptionU64
USTRUCT(BlueprintType)
struct TESTCLIENT_API FDeleteAllUniqueOptionU64Args
{
    GENERATED_BODY()

    // NOTE: FTestClientOptionalUInt64 field not exposed to Blueprint due to non-blueprintable elements
    FTestClientOptionalUInt64 N;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    int32 Data = 0;

    FDeleteAllUniqueOptionU64Args() = default;

    FDeleteAllUniqueOptionU64Args(const FTestClientOptionalUInt64& InN, const int32& InData)
        : N(InN), Data(InData)
    {}


    FORCEINLINE bool operator==(const FDeleteAllUniqueOptionU64Args& Other) const
    {
        return N == Other.N && Data == Other.Data;
    }
    FORCEINLINE bool operator!=(const FDeleteAllUniqueOptionU64Args& Other) const
    {
        return !(*this == Other);
    }
};

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_STRUCT(FDeleteAllUniqueOptionU64Args, N, Data);
}

// Reducer class for internal dispatching
UCLASS(BlueprintType)
class TESTCLIENT_API UDeleteAllUniqueOptionU64Reducer : public UReducerBase
{
    GENERATED_BODY()

public:
    // NOTE: FTestClientOptionalUInt64 field not exposed to Blueprint due to non-blueprintable elements
    FTestClientOptionalUInt64 N;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    int32 Data = 0;

};


