// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit aeeb35f0bbce28430aeeb22691976813dd469e1e).

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "Types/Builtins.h"
#include "DeleteUniqueIdentity.g.generated.h"

// Reducer arguments struct for DeleteUniqueIdentity
USTRUCT(BlueprintType)
struct TESTCLIENT_API FDeleteUniqueIdentityArgs
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    FSpacetimeDBIdentity I;

    FDeleteUniqueIdentityArgs() = default;

    FDeleteUniqueIdentityArgs(const FSpacetimeDBIdentity& InI)
        : I(InI)
    {}


    FORCEINLINE bool operator==(const FDeleteUniqueIdentityArgs& Other) const
    {
        return I == Other.I;
    }
    FORCEINLINE bool operator!=(const FDeleteUniqueIdentityArgs& Other) const
    {
        return !(*this == Other);
    }
};

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_STRUCT(FDeleteUniqueIdentityArgs, I);
}

// Reducer class for internal dispatching
UCLASS(BlueprintType)
class TESTCLIENT_API UDeleteUniqueIdentityReducer : public UReducerBase
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    FSpacetimeDBIdentity I;

};


