// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "ModuleBindings/Types/ByteStructType.g.h"
#include "DeleteAllVecByteStruct.g.generated.h"

// Reducer arguments struct for DeleteAllVecByteStruct
USTRUCT(BlueprintType)
struct TESTCLIENT_API FDeleteAllVecByteStructArgs
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    TArray<FByteStructType> S;

    FDeleteAllVecByteStructArgs() = default;

    FDeleteAllVecByteStructArgs(const TArray<FByteStructType>& InS)
        : S(InS)
    {}


    FORCEINLINE bool operator==(const FDeleteAllVecByteStructArgs& Other) const
    {
        return S == Other.S;
    }
    FORCEINLINE bool operator!=(const FDeleteAllVecByteStructArgs& Other) const
    {
        return !(*this == Other);
    }
};

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_STRUCT(FDeleteAllVecByteStructArgs, S);
}

// Reducer class for internal dispatching
UCLASS(BlueprintType)
class TESTCLIENT_API UDeleteAllVecByteStructReducer : public UReducerBase
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    TArray<FByteStructType> S;

};


