// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "Types/Builtins.h"
#include "DeleteAllVecIdentity.g.generated.h"

// Reducer arguments struct for DeleteAllVecIdentity
USTRUCT(BlueprintType)
struct TESTCLIENT_API FDeleteAllVecIdentityArgs
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    TArray<FSpacetimeDBIdentity> I;

    FDeleteAllVecIdentityArgs() = default;

    FDeleteAllVecIdentityArgs(const TArray<FSpacetimeDBIdentity>& InI)
        : I(InI)
    {}


    FORCEINLINE bool operator==(const FDeleteAllVecIdentityArgs& Other) const
    {
        return I == Other.I;
    }
    FORCEINLINE bool operator!=(const FDeleteAllVecIdentityArgs& Other) const
    {
        return !(*this == Other);
    }
};

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_STRUCT(FDeleteAllVecIdentityArgs, I);
}

// Reducer class for internal dispatching
UCLASS(BlueprintType)
class TESTCLIENT_API UDeleteAllVecIdentityReducer : public UReducerBase
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    TArray<FSpacetimeDBIdentity> I;

};


