// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "ModuleBindings/Types/UnitStructType.g.h"
#include "InsertVecUnitStruct.g.generated.h"

// Reducer arguments struct for InsertVecUnitStruct
USTRUCT(BlueprintType)
struct TESTCLIENT_API FInsertVecUnitStructArgs
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    TArray<FUnitStructType> S;

    FInsertVecUnitStructArgs() = default;

    FInsertVecUnitStructArgs(const TArray<FUnitStructType>& InS)
        : S(InS)
    {}


    FORCEINLINE bool operator==(const FInsertVecUnitStructArgs& Other) const
    {
        return S == Other.S;
    }
    FORCEINLINE bool operator!=(const FInsertVecUnitStructArgs& Other) const
    {
        return !(*this == Other);
    }
};

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_STRUCT(FInsertVecUnitStructArgs, S);
}

// Reducer class for internal dispatching
UCLASS(BlueprintType)
class TESTCLIENT_API UInsertVecUnitStructReducer : public UReducerBase
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    TArray<FUnitStructType> S;

};


