// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "ModuleBindings/Types/EnumWithPayloadType.g.h"
#include "InsertVecEnumWithPayload.g.generated.h"

// Reducer arguments struct for InsertVecEnumWithPayload
USTRUCT(BlueprintType)
struct TESTCLIENT_API FInsertVecEnumWithPayloadArgs
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    TArray<FEnumWithPayloadType> E;

    FInsertVecEnumWithPayloadArgs() = default;

    FInsertVecEnumWithPayloadArgs(const TArray<FEnumWithPayloadType>& InE)
        : E(InE)
    {}


    FORCEINLINE bool operator==(const FInsertVecEnumWithPayloadArgs& Other) const
    {
        return E == Other.E;
    }
    FORCEINLINE bool operator!=(const FInsertVecEnumWithPayloadArgs& Other) const
    {
        return !(*this == Other);
    }
};

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_STRUCT(FInsertVecEnumWithPayloadArgs, E);
}

// Reducer class for internal dispatching
UCLASS(BlueprintType)
class TESTCLIENT_API UInsertVecEnumWithPayloadReducer : public UReducerBase
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    TArray<FEnumWithPayloadType> E;

};


