// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit 263b33e20d9304f44bf4d598dde892211c5c89e8).

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "Types/Builtins.h"
#include "InsertUniqueConnectionId.g.generated.h"

// Reducer arguments struct for InsertUniqueConnectionId
USTRUCT(BlueprintType)
struct TESTCLIENT_API FInsertUniqueConnectionIdArgs
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    FSpacetimeDBConnectionId A;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    int32 Data;

    FInsertUniqueConnectionIdArgs() = default;

    FInsertUniqueConnectionIdArgs(const FSpacetimeDBConnectionId& InA, const int32& InData)
        : A(InA), Data(InData)
    {}


    FORCEINLINE bool operator==(const FInsertUniqueConnectionIdArgs& Other) const
    {
        return A == Other.A && Data == Other.Data;
    }
    FORCEINLINE bool operator!=(const FInsertUniqueConnectionIdArgs& Other) const
    {
        return !(*this == Other);
    }
};

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_STRUCT(FInsertUniqueConnectionIdArgs, A, Data);
}

// Reducer class for internal dispatching
UCLASS(BlueprintType)
class TESTCLIENT_API UInsertUniqueConnectionIdReducer : public UReducerBase
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    FSpacetimeDBConnectionId A;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    int32 Data;

};


