// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit 263b33e20d9304f44bf4d598dde892211c5c89e8).

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "Types/Builtins.h"
#include "InsertVecU128.g.generated.h"

// Reducer arguments struct for InsertVecU128
USTRUCT(BlueprintType)
struct TESTCLIENT_API FInsertVecU128Args
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    TArray<FSpacetimeDBUInt128> N;

    FInsertVecU128Args() = default;

    FInsertVecU128Args(const TArray<FSpacetimeDBUInt128>& InN)
        : N(InN)
    {}


    FORCEINLINE bool operator==(const FInsertVecU128Args& Other) const
    {
        return N == Other.N;
    }
    FORCEINLINE bool operator!=(const FInsertVecU128Args& Other) const
    {
        return !(*this == Other);
    }
};

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_STRUCT(FInsertVecU128Args, N);
}

// Reducer class for internal dispatching
UCLASS(BlueprintType)
class TESTCLIENT_API UInsertVecU128Reducer : public UReducerBase
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    TArray<FSpacetimeDBUInt128> N;

};


