// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit 263b33e20d9304f44bf4d598dde892211c5c89e8).

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "ModuleBindings/Types/UnitStructType.g.h"
#include "InsertOneUnitStruct.g.generated.h"

// Reducer arguments struct for InsertOneUnitStruct
USTRUCT(BlueprintType)
struct TESTCLIENT_API FInsertOneUnitStructArgs
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    FUnitStructType S;

    FInsertOneUnitStructArgs() = default;

    FInsertOneUnitStructArgs(const FUnitStructType& InS)
        : S(InS)
    {}


    FORCEINLINE bool operator==(const FInsertOneUnitStructArgs& Other) const
    {
        return S == Other.S;
    }
    FORCEINLINE bool operator!=(const FInsertOneUnitStructArgs& Other) const
    {
        return !(*this == Other);
    }
};

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_STRUCT(FInsertOneUnitStructArgs, S);
}

// Reducer class for internal dispatching
UCLASS(BlueprintType)
class TESTCLIENT_API UInsertOneUnitStructReducer : public UReducerBase
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    FUnitStructType S;

};


