// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "InsertVecBool.g.generated.h"

// Reducer arguments struct for InsertVecBool
USTRUCT(BlueprintType)
struct TESTCLIENT_API FInsertVecBoolArgs
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    TArray<bool> B;

    FInsertVecBoolArgs() = default;

    FInsertVecBoolArgs(const TArray<bool>& InB)
        : B(InB)
    {}


    FORCEINLINE bool operator==(const FInsertVecBoolArgs& Other) const
    {
        return B == Other.B;
    }
    FORCEINLINE bool operator!=(const FInsertVecBoolArgs& Other) const
    {
        return !(*this == Other);
    }
};

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_STRUCT(FInsertVecBoolArgs, B);
}

// Reducer class for internal dispatching
UCLASS(BlueprintType)
class TESTCLIENT_API UInsertVecBoolReducer : public UReducerBase
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    TArray<bool> B;

};


