// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "InsertVecU64.g.generated.h"

// Reducer arguments struct for InsertVecU64
USTRUCT(BlueprintType)
struct TESTCLIENT_API FInsertVecU64Args
{
    GENERATED_BODY()

    // NOTE: TArray<uint64> field not exposed to Blueprint due to non-blueprintable elements
    TArray<uint64> N;

    FInsertVecU64Args() = default;

    FInsertVecU64Args(const TArray<uint64>& InN)
        : N(InN)
    {}


    FORCEINLINE bool operator==(const FInsertVecU64Args& Other) const
    {
        return N == Other.N;
    }
    FORCEINLINE bool operator!=(const FInsertVecU64Args& Other) const
    {
        return !(*this == Other);
    }
};

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_STRUCT(FInsertVecU64Args, N);
}

// Reducer class for internal dispatching
UCLASS(BlueprintType)
class TESTCLIENT_API UInsertVecU64Reducer : public UReducerBase
{
    GENERATED_BODY()

public:
    // NOTE: TArray<uint64> field not exposed to Blueprint due to non-blueprintable elements
    TArray<uint64> N;

};


