// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "InsertOneF32.g.generated.h"

// Reducer arguments struct for InsertOneF32
USTRUCT(BlueprintType)
struct TESTCLIENT_API FInsertOneF32Args
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    float F = 0.0f;

    FInsertOneF32Args() = default;

    FInsertOneF32Args(const float& InF)
        : F(InF)
    {}


    FORCEINLINE bool operator==(const FInsertOneF32Args& Other) const
    {
        return F == Other.F;
    }
    FORCEINLINE bool operator!=(const FInsertOneF32Args& Other) const
    {
        return !(*this == Other);
    }
};

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_STRUCT(FInsertOneF32Args, F);
}

// Reducer class for internal dispatching
UCLASS(BlueprintType)
class TESTCLIENT_API UInsertOneF32Reducer : public UReducerBase
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    float F = 0.0f;

};


