// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit aeeb35f0bbce28430aeeb22691976813dd469e1e).

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "Types/Builtins.h"
#include "InsertVecIdentity.g.generated.h"

// Reducer arguments struct for InsertVecIdentity
USTRUCT(BlueprintType)
struct TESTCLIENT_API FInsertVecIdentityArgs
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    TArray<FSpacetimeDBIdentity> I;

    FInsertVecIdentityArgs() = default;

    FInsertVecIdentityArgs(const TArray<FSpacetimeDBIdentity>& InI)
        : I(InI)
    {}


    FORCEINLINE bool operator==(const FInsertVecIdentityArgs& Other) const
    {
        return I == Other.I;
    }
    FORCEINLINE bool operator!=(const FInsertVecIdentityArgs& Other) const
    {
        return !(*this == Other);
    }
};

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_STRUCT(FInsertVecIdentityArgs, I);
}

// Reducer class for internal dispatching
UCLASS(BlueprintType)
class TESTCLIENT_API UInsertVecIdentityReducer : public UReducerBase
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    TArray<FSpacetimeDBIdentity> I;

};


