// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "Types/Builtins.h"
#include "UpdatePkU128.g.generated.h"

// Reducer arguments struct for UpdatePkU128
USTRUCT(BlueprintType)
struct TESTCLIENT_API FUpdatePkU128Args
{
    GENERATED_BODY()

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    FSpacetimeDBUInt128 N;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    int32 Data = 0;

    FUpdatePkU128Args() = default;

    FUpdatePkU128Args(const FSpacetimeDBUInt128& InN, const int32& InData)
        : N(InN), Data(InData)
    {}


    FORCEINLINE bool operator==(const FUpdatePkU128Args& Other) const
    {
        return N == Other.N && Data == Other.Data;
    }
    FORCEINLINE bool operator!=(const FUpdatePkU128Args& Other) const
    {
        return !(*this == Other);
    }
};

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_STRUCT(FUpdatePkU128Args, N, Data);
}

// Reducer class for internal dispatching
UCLASS(BlueprintType)
class TESTCLIENT_API UUpdatePkU128Reducer : public UReducerBase
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    FSpacetimeDBUInt128 N;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    int32 Data = 0;

};


