/** SenderError codes thrown by the grid helpers. */
export const errors = {
  invalidName: 'grid.invalid_name',
  invalidKind: 'grid.invalid_kind',
  invalidOrientation: 'grid.invalid_orientation',
  invalidMode: 'grid.invalid_mode',
  invalidDimensions: 'grid.invalid_dimensions',
  invalidDefaultCost: 'grid.invalid_default_cost',
  invalidConnectivity: 'grid.invalid_connectivity',
  invalidCost: 'grid.invalid_cost',
  invalidTerrain: 'grid.invalid_terrain',
  tooManyCells: 'grid.too_many_cells',
  invalidEntityKind: 'grid.invalid_entity_kind',
  invalidEntityLabel: 'grid.invalid_entity_label',
  invalidMaxExpansions: 'grid.invalid_max_expansions',
  notFound: 'grid.not_found',
  notOwner: 'grid.not_owner',
  entityNotFound: 'grid.entity_not_found',
  entityNotOwner: 'grid.entity_not_owner',
  entityGridMismatch: 'grid.entity_grid_mismatch',
  outOfBounds: 'grid.out_of_bounds',
  moveNotAdjacent: 'grid.move_not_adjacent',
  moveBlocked: 'grid.move_blocked',
  pathTooLong: 'grid.path_too_long',
  rangeTooLarge: 'grid.range_too_large',
} as const;
