// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.11.0 (commit f10bcb99f539cfad89cc051e5555211a472c4fc8).

#![allow(unused, clippy::all)]
use spacetimedb_sdk as spacetimedb;

pub mod insert_left_reducer;
pub mod insert_right_reducer;
pub mod left_source_table;
pub mod right_source_table;
pub mod sender_left_view_table;
pub mod sender_right_view_table;
pub mod update_left_reducer;

pub use insert_left_reducer::insert_left;
pub use insert_right_reducer::insert_right;
pub use left_source_table::*;
pub use right_source_table::*;
pub use sender_left_view_table::*;
pub use sender_right_view_table::*;
pub use update_left_reducer::update_left;

spacetimedb::client_module! {
    tables: [
        left_source_table::left_source,
        right_source_table::right_source,
        sender_left_view_table::sender_left_view,
        sender_right_view_table::sender_right_view,
    ],
    reducers: [
        insert_left_reducer::insert_left(id, filter),
        insert_right_reducer::insert_right(id, filter),
        update_left_reducer::update_left(id, filter),
    ],
}
