[package]
name = "spacetimedb-io-tokio"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
spacetimedb-io-types.workspace = true
static_assertions.workspace = true
tokio.workspace = true

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = ["Win32_Storage_FileSystem"] }

[lints]
workspace = true
