/// Classification of WASM opcodes by operation type, along with our estimated cost of
/// these operations, in our own energy 'quanta' units.
use wasmer::wasmparser::Operator;

/// Rough categorizations of types of operations, so that we can group things roughly by cost.
// TODO: These categorizations are likely going to need attention over time but reflected my
// broad understanding of the kinds of operations grouped in terms of their potential computation
// cost categorizations.
#[derive(Debug, Hash, PartialEq, Eq, PartialOrd, Ord, Copy, Clone)]
pub enum OperationType {
    Nop,

    // Integer scalar ops
    Bit,
    AtomicBit,
    AtomicXchg,
    IntegerComparison,
    AddSub,
    AtomicAddSub,
    Mul,
    Div,

    // Float scalar ops
    FloatComparison,
    FloatAdd,
    FloatMul,
    FloatDiv,
    FloatOperation, // abs/ceil/floor etc.

    // Variable / stack
    Load,
    Store,
    AtomicLoad,
    AtomicStore,
    Const,
    FloatConst,
    Local,
    Global,

    // Control flow and scope
    Branch,
    Scope,
    Unreachable,
    Call,

    // Type conversion
    Conversion,
    FloatConversion,
    Reinterpretation,

    // Memory management
    Memory,

    // I'm a snowflake!
    AtomicSynchronization,

    // Vector SIMD operations.
    Vector128Load,
    Vector128Store,
    Vector128Const,
    Vector128Bit,
    Vector128Integer,
    Vector128Float,
}

impl OperationType {
    /// Classify a Wasmer Operator by its operation type.
    #[tracing::instrument(skip_all)]
    pub fn operation_type_of(instruction: &Operator) -> Self {
        // TODO: keep an eye on this table.
        // TODO: this table is going to be not-fun to maintain over time, esp as more vector ops
        // are added, or wasmer versions change. There might be a more scalable approach.
        use Operator as O;
        match instruction {
            O::Unreachable => OperationType::Unreachable,
            O::Nop => OperationType::Nop,
            O::Block { .. } => OperationType::Scope,
            O::Loop { .. } => OperationType::Scope,
            O::If { .. } => OperationType::Scope,
            O::Else => OperationType::Scope,
            O::End => OperationType::Scope,
            O::Br { .. } => OperationType::Branch,
            O::BrIf { .. } => OperationType::Branch,
            O::BrTable { .. } => OperationType::Branch,
            O::Return => OperationType::Branch,

            O::Drop => OperationType::Branch,
            O::Select => OperationType::Branch,
            O::Try { .. } => OperationType::Scope,
            O::Catch { .. } => OperationType::Scope,
            O::Throw { .. } => OperationType::Branch,
            O::Rethrow { .. } => OperationType::Branch,
            O::ReturnCall { .. } => OperationType::Branch,
            O::ReturnCallIndirect { .. } => OperationType::Branch,
            O::Delegate { .. } => OperationType::Branch,
            O::CatchAll => OperationType::Scope,
            O::TypedSelect { .. } => OperationType::Branch,

            O::Call { .. } => OperationType::Call,
            O::CallIndirect { .. } => OperationType::Call,

            O::MemorySize { .. } => OperationType::Memory,
            O::MemoryGrow { .. } => OperationType::Memory,

            // TODO: not clear on these, I'll treat them as Local for now
            O::RefNull { .. } => OperationType::Local,
            O::RefIsNull => OperationType::Local,
            O::RefFunc { .. } => OperationType::Local,

            O::LocalGet { .. } => OperationType::Local,
            O::LocalSet { .. } => OperationType::Local,
            O::LocalTee { .. } => OperationType::Local,

            O::GlobalGet { .. } => OperationType::Global,
            O::GlobalSet { .. } => OperationType::Global,

            O::I32Load { .. } => OperationType::Load,
            O::I64Load { .. } => OperationType::Load,
            O::F32Load { .. } => OperationType::Load,
            O::F64Load { .. } => OperationType::Load,
            O::I32Load8S { .. } => OperationType::Load,
            O::I32Load8U { .. } => OperationType::Load,
            O::I32Load16S { .. } => OperationType::Load,
            O::I32Load16U { .. } => OperationType::Load,
            O::I64Load8S { .. } => OperationType::Load,
            O::I64Load8U { .. } => OperationType::Load,
            O::I64Load16S { .. } => OperationType::Load,
            O::I64Load16U { .. } => OperationType::Load,
            O::I64Load32S { .. } => OperationType::Load,
            O::I64Load32U { .. } => OperationType::Load,
            O::I32AtomicLoad { .. } => OperationType::AtomicLoad,
            O::I64AtomicLoad { .. } => OperationType::AtomicLoad,
            O::I32AtomicLoad8U { .. } => OperationType::AtomicLoad,
            O::I32AtomicLoad16U { .. } => OperationType::AtomicLoad,
            O::I64AtomicLoad8U { .. } => OperationType::AtomicLoad,
            O::I64AtomicLoad16U { .. } => OperationType::AtomicLoad,
            O::I64AtomicLoad32U { .. } => OperationType::AtomicLoad,

            // Look at me, I'm a snowflake.
            O::AtomicFence { .. } => OperationType::AtomicSynchronization,

            O::I32Store { .. } => OperationType::Store,
            O::I64Store { .. } => OperationType::Store,
            O::F32Store { .. } => OperationType::Store,
            O::F64Store { .. } => OperationType::Store,
            O::I32Store8 { .. } => OperationType::Store,
            O::I32Store16 { .. } => OperationType::Store,
            O::I64Store8 { .. } => OperationType::Store,
            O::I64Store16 { .. } => OperationType::Store,
            O::I64Store32 { .. } => OperationType::Store,
            O::I32AtomicStore { .. } => OperationType::AtomicStore,
            O::I64AtomicStore { .. } => OperationType::AtomicStore,
            O::I32AtomicStore8 { .. } => OperationType::AtomicStore,
            O::I32AtomicStore16 { .. } => OperationType::AtomicStore,
            O::I64AtomicStore8 { .. } => OperationType::AtomicStore,
            O::I64AtomicStore16 { .. } => OperationType::AtomicStore,
            O::I64AtomicStore32 { .. } => OperationType::AtomicStore,

            O::I32Const { .. } => OperationType::Const,
            O::I64Const { .. } => OperationType::Const,

            O::F32Const { .. } => OperationType::FloatConst,
            O::F64Const { .. } => OperationType::FloatConst,

            O::I32Eqz => OperationType::IntegerComparison,
            O::I32Eq => OperationType::IntegerComparison,
            O::I32Ne => OperationType::IntegerComparison,
            O::I32LtS => OperationType::IntegerComparison,
            O::I32LtU => OperationType::IntegerComparison,
            O::I32GtS => OperationType::IntegerComparison,
            O::I32GtU => OperationType::IntegerComparison,
            O::I32LeS => OperationType::IntegerComparison,
            O::I32LeU => OperationType::IntegerComparison,
            O::I32GeS => OperationType::IntegerComparison,
            O::I32GeU => OperationType::IntegerComparison,

            O::I64Eqz => OperationType::IntegerComparison,
            O::I64Eq => OperationType::IntegerComparison,
            O::I64Ne => OperationType::IntegerComparison,
            O::I64LtS => OperationType::IntegerComparison,
            O::I64LtU => OperationType::IntegerComparison,
            O::I64GtS => OperationType::IntegerComparison,
            O::I64GtU => OperationType::IntegerComparison,
            O::I64LeS => OperationType::IntegerComparison,
            O::I64LeU => OperationType::IntegerComparison,
            O::I64GeS => OperationType::IntegerComparison,
            O::I64GeU => OperationType::IntegerComparison,

            O::F32Eq => OperationType::FloatComparison,
            O::F32Ne => OperationType::FloatComparison,
            O::F32Lt => OperationType::FloatComparison,
            O::F32Gt => OperationType::FloatComparison,
            O::F32Le => OperationType::FloatComparison,
            O::F32Ge => OperationType::FloatComparison,

            O::F64Eq => OperationType::FloatComparison,
            O::F64Ne => OperationType::FloatComparison,
            O::F64Lt => OperationType::FloatComparison,
            O::F64Gt => OperationType::FloatComparison,
            O::F64Le => OperationType::FloatComparison,
            O::F64Ge => OperationType::FloatComparison,

            O::I32Clz => OperationType::Bit,
            O::I32Ctz => OperationType::Bit,
            O::I32Popcnt => OperationType::Bit,

            O::I32Add => OperationType::AddSub,
            O::I32Sub => OperationType::AddSub,

            O::I32AtomicRmwAdd { .. } => OperationType::AtomicAddSub,
            O::I64AtomicRmwAdd { .. } => OperationType::AtomicAddSub,
            O::I32AtomicRmw8AddU { .. } => OperationType::AtomicAddSub,
            O::I32AtomicRmw16AddU { .. } => OperationType::AtomicAddSub,
            O::I64AtomicRmw8AddU { .. } => OperationType::AtomicAddSub,
            O::I64AtomicRmw16AddU { .. } => OperationType::AtomicAddSub,
            O::I64AtomicRmw32AddU { .. } => OperationType::AtomicAddSub,
            O::I32AtomicRmwSub { .. } => OperationType::AtomicAddSub,
            O::I64AtomicRmwSub { .. } => OperationType::AtomicAddSub,
            O::I32AtomicRmw8SubU { .. } => OperationType::AtomicAddSub,
            O::I32AtomicRmw16SubU { .. } => OperationType::AtomicAddSub,
            O::I64AtomicRmw8SubU { .. } => OperationType::AtomicAddSub,
            O::I64AtomicRmw16SubU { .. } => OperationType::AtomicAddSub,
            O::I64AtomicRmw32SubU { .. } => OperationType::AtomicAddSub,

            O::I32AtomicRmwAnd { .. } => OperationType::AtomicBit,
            O::I64AtomicRmwAnd { .. } => OperationType::AtomicBit,
            O::I32AtomicRmw8AndU { .. } => OperationType::AtomicBit,
            O::I32AtomicRmw16AndU { .. } => OperationType::AtomicBit,
            O::I64AtomicRmw8AndU { .. } => OperationType::AtomicBit,
            O::I64AtomicRmw16AndU { .. } => OperationType::AtomicBit,
            O::I64AtomicRmw32AndU { .. } => OperationType::AtomicBit,
            O::I32AtomicRmwOr { .. } => OperationType::AtomicBit,
            O::I64AtomicRmwOr { .. } => OperationType::AtomicBit,
            O::I32AtomicRmw8OrU { .. } => OperationType::AtomicBit,
            O::I32AtomicRmw16OrU { .. } => OperationType::AtomicBit,
            O::I64AtomicRmw8OrU { .. } => OperationType::AtomicBit,
            O::I64AtomicRmw16OrU { .. } => OperationType::AtomicBit,
            O::I64AtomicRmw32OrU { .. } => OperationType::AtomicBit,
            O::I32AtomicRmwXor { .. } => OperationType::AtomicBit,
            O::I64AtomicRmwXor { .. } => OperationType::AtomicBit,
            O::I32AtomicRmw8XorU { .. } => OperationType::AtomicBit,
            O::I32AtomicRmw16XorU { .. } => OperationType::AtomicBit,
            O::I64AtomicRmw8XorU { .. } => OperationType::AtomicBit,
            O::I64AtomicRmw16XorU { .. } => OperationType::AtomicBit,
            O::I64AtomicRmw32XorU { .. } => OperationType::AtomicBit,

            O::I32AtomicRmwXchg { .. } => OperationType::AtomicXchg,
            O::I64AtomicRmwXchg { .. } => OperationType::AtomicXchg,
            O::I32AtomicRmw8XchgU { .. } => OperationType::AtomicXchg,
            O::I32AtomicRmw16XchgU { .. } => OperationType::AtomicXchg,
            O::I64AtomicRmw8XchgU { .. } => OperationType::AtomicXchg,
            O::I64AtomicRmw16XchgU { .. } => OperationType::AtomicXchg,
            O::I64AtomicRmw32XchgU { .. } => OperationType::AtomicXchg,
            O::I32AtomicRmwCmpxchg { .. } => OperationType::AtomicXchg,
            O::I64AtomicRmwCmpxchg { .. } => OperationType::AtomicXchg,
            O::I32AtomicRmw8CmpxchgU { .. } => OperationType::AtomicXchg,
            O::I32AtomicRmw16CmpxchgU { .. } => OperationType::AtomicXchg,
            O::I64AtomicRmw8CmpxchgU { .. } => OperationType::AtomicXchg,
            O::I64AtomicRmw16CmpxchgU { .. } => OperationType::AtomicXchg,
            O::I64AtomicRmw32CmpxchgU { .. } => OperationType::AtomicXchg,

            O::I32Mul => OperationType::Mul,
            O::I32DivS => OperationType::Div,
            O::I32DivU => OperationType::Div,
            O::I32RemS => OperationType::Div,
            O::I32RemU => OperationType::Div,
            O::I32And => OperationType::Bit,
            O::I32Or => OperationType::Bit,
            O::I32Xor => OperationType::Bit,
            O::I32Shl => OperationType::Bit,
            O::I32ShrS => OperationType::Bit,
            O::I32ShrU => OperationType::Bit,
            O::I32Rotl => OperationType::Bit,
            O::I32Rotr => OperationType::Bit,

            O::I64Clz => OperationType::Bit,
            O::I64Ctz => OperationType::Bit,
            O::I64Popcnt => OperationType::Bit,
            O::I64Add => OperationType::AddSub,
            O::I64Sub => OperationType::AddSub,
            O::I64Mul => OperationType::Mul,
            O::I64DivS => OperationType::Div,
            O::I64DivU => OperationType::Div,
            O::I64RemS => OperationType::Div,
            O::I64RemU => OperationType::Div,
            O::I64And => OperationType::Bit,
            O::I64Or => OperationType::Bit,
            O::I64Xor => OperationType::Bit,
            O::I64Shl => OperationType::Bit,
            O::I64ShrS => OperationType::Bit,
            O::I64ShrU => OperationType::Bit,
            O::I64Rotl => OperationType::Bit,
            O::I64Rotr => OperationType::Bit,

            O::F32Abs => OperationType::FloatOperation,
            O::F32Neg => OperationType::FloatOperation,
            O::F32Ceil => OperationType::FloatOperation,
            O::F32Floor => OperationType::FloatOperation,
            O::F32Trunc => OperationType::FloatOperation,
            O::F32Nearest => OperationType::FloatOperation,
            O::F32Sqrt => OperationType::FloatOperation,
            O::F32Add => OperationType::FloatAdd,
            O::F32Sub => OperationType::FloatAdd,
            O::F32Mul => OperationType::FloatMul,
            O::F32Div => OperationType::FloatDiv,
            O::F32Min => OperationType::FloatComparison,
            O::F32Max => OperationType::FloatComparison,
            O::F32Copysign => OperationType::FloatComparison,
            O::F64Abs => OperationType::FloatOperation,
            O::F64Neg => OperationType::FloatComparison,
            O::F64Ceil => OperationType::FloatOperation,
            O::F64Floor => OperationType::FloatOperation,
            O::F64Trunc => OperationType::FloatOperation,
            O::F64Nearest => OperationType::FloatOperation,
            O::F64Sqrt => OperationType::FloatOperation,
            O::F64Add => OperationType::FloatAdd,
            O::F64Sub => OperationType::FloatAdd,
            O::F64Mul => OperationType::FloatMul,
            O::F64Div => OperationType::FloatDiv,
            O::F64Min => OperationType::FloatComparison,
            O::F64Max => OperationType::FloatComparison,
            O::F64Copysign => OperationType::FloatComparison,

            O::I32WrapI64 => OperationType::Conversion,
            O::I64ExtendI32S => OperationType::Conversion,
            O::I64ExtendI32U => OperationType::Conversion,
            O::I32Extend8S => OperationType::Conversion,
            O::I32Extend16S => OperationType::Conversion,
            O::I64Extend8S => OperationType::Conversion,
            O::I64Extend16S => OperationType::Conversion,
            O::I64Extend32S => OperationType::Conversion,

            O::I32TruncF32S => OperationType::FloatConversion,
            O::I32TruncF32U => OperationType::FloatConversion,
            O::I32TruncF64S => OperationType::FloatConversion,
            O::I32TruncF64U => OperationType::FloatConversion,
            O::I64TruncF32S => OperationType::FloatConversion,
            O::I64TruncF32U => OperationType::FloatConversion,
            O::I64TruncF64S => OperationType::FloatConversion,
            O::I64TruncF64U => OperationType::FloatConversion,
            O::I32TruncSatF32S => OperationType::FloatConversion,
            O::I32TruncSatF32U => OperationType::FloatConversion,
            O::I32TruncSatF64S => OperationType::FloatConversion,
            O::I32TruncSatF64U => OperationType::FloatConversion,
            O::I64TruncSatF32S => OperationType::FloatConversion,
            O::I64TruncSatF32U => OperationType::FloatConversion,
            O::I64TruncSatF64S => OperationType::FloatConversion,
            O::I64TruncSatF64U => OperationType::FloatConversion,

            O::F32ConvertI32S => OperationType::FloatConversion,
            O::F32ConvertI32U => OperationType::FloatConversion,
            O::F32ConvertI64S => OperationType::FloatConversion,
            O::F32ConvertI64U => OperationType::FloatConversion,
            O::F32DemoteF64 => OperationType::FloatConversion,
            O::F64ConvertI32S => OperationType::FloatConversion,
            O::F64ConvertI32U => OperationType::FloatConversion,
            O::F64ConvertI64S => OperationType::FloatConversion,
            O::F64ConvertI64U => OperationType::FloatConversion,
            O::F64PromoteF32 => OperationType::FloatConversion,

            O::I32ReinterpretF32 => OperationType::Reinterpretation,
            O::I64ReinterpretF64 => OperationType::Reinterpretation,
            O::F32ReinterpretI32 => OperationType::Reinterpretation,
            O::F64ReinterpretI64 => OperationType::Reinterpretation,

            O::MemoryInit { .. } => OperationType::Memory,
            O::DataDrop { .. } => OperationType::Memory,
            O::MemoryCopy { .. } => OperationType::Memory,
            O::MemoryFill { .. } => OperationType::Memory,
            O::TableInit { .. } => OperationType::Memory,
            O::ElemDrop { .. } => OperationType::Memory,
            O::TableCopy { .. } => OperationType::Memory,
            O::TableFill { .. } => OperationType::Memory,
            O::TableGet { .. } => OperationType::Memory,
            O::TableSet { .. } => OperationType::Memory,
            O::TableGrow { .. } => OperationType::Memory,
            O::TableSize { .. } => OperationType::Memory,

            O::MemoryAtomicNotify { .. } => OperationType::Memory,
            O::MemoryAtomicWait32 { .. } => OperationType::Memory,
            O::MemoryAtomicWait64 { .. } => OperationType::Memory,

            O::V128Load { .. } => OperationType::Vector128Load,
            O::V128Load8x8S { .. } => OperationType::Vector128Load,
            O::V128Load8x8U { .. } => OperationType::Vector128Load,
            O::V128Load16x4S { .. } => OperationType::Vector128Load,
            O::V128Load16x4U { .. } => OperationType::Vector128Load,
            O::V128Load32x2S { .. } => OperationType::Vector128Load,
            O::V128Load32x2U { .. } => OperationType::Vector128Load,
            O::V128Load8Splat { .. } => OperationType::Vector128Load,
            O::V128Load16Splat { .. } => OperationType::Vector128Load,
            O::V128Load32Splat { .. } => OperationType::Vector128Load,
            O::V128Load64Splat { .. } => OperationType::Vector128Load,
            O::V128Load32Zero { .. } => OperationType::Vector128Load,
            O::V128Load64Zero { .. } => OperationType::Vector128Load,
            O::V128Load8Lane { .. } => OperationType::Vector128Load,
            O::V128Load16Lane { .. } => OperationType::Vector128Load,
            O::V128Load32Lane { .. } => OperationType::Vector128Load,
            O::V128Load64Lane { .. } => OperationType::Vector128Load,

            O::V128Store { .. } => OperationType::Vector128Store,
            O::V128Store8Lane { .. } => OperationType::Vector128Store,
            O::V128Store16Lane { .. } => OperationType::Vector128Store,
            O::V128Store32Lane { .. } => OperationType::Vector128Store,
            O::V128Store64Lane { .. } => OperationType::Vector128Store,
            O::V128Const { .. } => OperationType::Vector128Const,

            O::V128Not => OperationType::Vector128Bit,
            O::V128And => OperationType::Vector128Bit,
            O::V128AndNot => OperationType::Vector128Bit,
            O::V128Or => OperationType::Vector128Bit,
            O::V128Xor => OperationType::Vector128Bit,
            O::V128Bitselect => OperationType::Vector128Bit,
            O::V128AnyTrue => OperationType::Vector128Bit,

            O::I8x16Shuffle { .. } => OperationType::Vector128Integer,
            O::I8x16ExtractLaneS { .. } => OperationType::Vector128Integer,
            O::I8x16ExtractLaneU { .. } => OperationType::Vector128Integer,
            O::I8x16ReplaceLane { .. } => OperationType::Vector128Integer,
            O::I16x8ExtractLaneS { .. } => OperationType::Vector128Integer,
            O::I16x8ExtractLaneU { .. } => OperationType::Vector128Integer,
            O::I16x8ReplaceLane { .. } => OperationType::Vector128Integer,
            O::I32x4ExtractLane { .. } => OperationType::Vector128Integer,
            O::I32x4ReplaceLane { .. } => OperationType::Vector128Integer,
            O::I64x2ExtractLane { .. } => OperationType::Vector128Integer,
            O::I64x2ReplaceLane { .. } => OperationType::Vector128Integer,
            O::F32x4ExtractLane { .. } => OperationType::Vector128Integer,
            O::F32x4ReplaceLane { .. } => OperationType::Vector128Integer,
            O::F64x2ExtractLane { .. } => OperationType::Vector128Integer,
            O::F64x2ReplaceLane { .. } => OperationType::Vector128Integer,
            O::I8x16Swizzle => OperationType::Vector128Integer,
            O::I8x16Splat => OperationType::Vector128Integer,
            O::I16x8Splat => OperationType::Vector128Integer,
            O::I32x4Splat => OperationType::Vector128Integer,
            O::I64x2Splat => OperationType::Vector128Integer,
            O::F32x4Splat => OperationType::Vector128Integer,
            O::F64x2Splat => OperationType::Vector128Integer,
            O::I8x16Eq => OperationType::Vector128Integer,
            O::I8x16Ne => OperationType::Vector128Integer,
            O::I8x16LtS => OperationType::Vector128Integer,
            O::I8x16LtU => OperationType::Vector128Integer,
            O::I8x16GtS => OperationType::Vector128Integer,
            O::I8x16GtU => OperationType::Vector128Integer,
            O::I8x16LeS => OperationType::Vector128Integer,
            O::I8x16LeU => OperationType::Vector128Integer,
            O::I8x16GeS => OperationType::Vector128Integer,
            O::I8x16GeU => OperationType::Vector128Integer,
            O::I16x8Eq => OperationType::Vector128Integer,
            O::I16x8Ne => OperationType::Vector128Integer,
            O::I16x8LtS => OperationType::Vector128Integer,
            O::I16x8LtU => OperationType::Vector128Integer,
            O::I16x8GtS => OperationType::Vector128Integer,
            O::I16x8GtU => OperationType::Vector128Integer,
            O::I16x8LeS => OperationType::Vector128Integer,
            O::I16x8LeU => OperationType::Vector128Integer,
            O::I16x8GeS => OperationType::Vector128Integer,
            O::I16x8GeU => OperationType::Vector128Integer,
            O::I32x4Eq => OperationType::Vector128Integer,
            O::I32x4Ne => OperationType::Vector128Integer,
            O::I32x4LtS => OperationType::Vector128Integer,
            O::I32x4LtU => OperationType::Vector128Integer,
            O::I32x4GtS => OperationType::Vector128Integer,
            O::I32x4GtU => OperationType::Vector128Integer,
            O::I32x4LeS => OperationType::Vector128Integer,
            O::I32x4LeU => OperationType::Vector128Integer,
            O::I32x4GeS => OperationType::Vector128Integer,
            O::I32x4GeU => OperationType::Vector128Integer,
            O::I64x2Eq => OperationType::Vector128Integer,
            O::I64x2Ne => OperationType::Vector128Integer,
            O::I64x2LtS => OperationType::Vector128Integer,
            O::I64x2GtS => OperationType::Vector128Integer,
            O::I64x2LeS => OperationType::Vector128Integer,
            O::I64x2GeS => OperationType::Vector128Integer,
            O::I8x16Abs => OperationType::Vector128Integer,
            O::I8x16Neg => OperationType::Vector128Integer,
            O::I8x16Popcnt => OperationType::Vector128Integer,
            O::I8x16AllTrue => OperationType::Vector128Integer,
            O::I8x16Bitmask => OperationType::Vector128Integer,
            O::I8x16NarrowI16x8S => OperationType::Vector128Integer,
            O::I8x16NarrowI16x8U => OperationType::Vector128Integer,
            O::I8x16Shl => OperationType::Vector128Integer,
            O::I8x16ShrS => OperationType::Vector128Integer,
            O::I8x16ShrU => OperationType::Vector128Integer,
            O::I8x16Add => OperationType::Vector128Integer,
            O::I8x16AddSatS => OperationType::Vector128Integer,
            O::I8x16AddSatU => OperationType::Vector128Integer,
            O::I8x16Sub => OperationType::Vector128Integer,
            O::I8x16SubSatS => OperationType::Vector128Integer,
            O::I8x16SubSatU => OperationType::Vector128Integer,
            O::I8x16MinS => OperationType::Vector128Integer,
            O::I8x16MinU => OperationType::Vector128Integer,
            O::I8x16MaxS => OperationType::Vector128Integer,
            O::I8x16MaxU => OperationType::Vector128Integer,
            O::I8x16AvgrU => OperationType::Vector128Integer,
            O::I16x8ExtAddPairwiseI8x16S => OperationType::Vector128Integer,
            O::I16x8ExtAddPairwiseI8x16U => OperationType::Vector128Integer,
            O::I16x8Abs => OperationType::Vector128Integer,
            O::I16x8Neg => OperationType::Vector128Integer,
            O::I16x8Q15MulrSatS => OperationType::Vector128Integer,
            O::I16x8AllTrue => OperationType::Vector128Integer,
            O::I16x8Bitmask => OperationType::Vector128Integer,
            O::I16x8NarrowI32x4S => OperationType::Vector128Integer,
            O::I16x8NarrowI32x4U => OperationType::Vector128Integer,
            O::I16x8ExtendLowI8x16S => OperationType::Vector128Integer,
            O::I16x8ExtendHighI8x16S => OperationType::Vector128Integer,
            O::I16x8ExtendLowI8x16U => OperationType::Vector128Integer,
            O::I16x8ExtendHighI8x16U => OperationType::Vector128Integer,
            O::I16x8Shl => OperationType::Vector128Integer,
            O::I16x8ShrS => OperationType::Vector128Integer,
            O::I16x8ShrU => OperationType::Vector128Integer,
            O::I16x8Add => OperationType::Vector128Integer,
            O::I16x8AddSatS => OperationType::Vector128Integer,
            O::I16x8AddSatU => OperationType::Vector128Integer,
            O::I16x8Sub => OperationType::Vector128Integer,
            O::I16x8SubSatS => OperationType::Vector128Integer,
            O::I16x8SubSatU => OperationType::Vector128Integer,
            O::I16x8Mul => OperationType::Vector128Integer,
            O::I16x8MinS => OperationType::Vector128Integer,
            O::I16x8MinU => OperationType::Vector128Integer,
            O::I16x8MaxS => OperationType::Vector128Integer,
            O::I16x8MaxU => OperationType::Vector128Integer,
            O::I16x8AvgrU => OperationType::Vector128Integer,
            O::I16x8ExtMulLowI8x16S => OperationType::Vector128Integer,
            O::I16x8ExtMulHighI8x16S => OperationType::Vector128Integer,
            O::I16x8ExtMulLowI8x16U => OperationType::Vector128Integer,
            O::I16x8ExtMulHighI8x16U => OperationType::Vector128Integer,
            O::I32x4ExtAddPairwiseI16x8S => OperationType::Vector128Integer,
            O::I32x4ExtAddPairwiseI16x8U => OperationType::Vector128Integer,
            O::I32x4Abs => OperationType::Vector128Integer,
            O::I32x4Neg => OperationType::Vector128Integer,
            O::I32x4AllTrue => OperationType::Vector128Integer,
            O::I32x4Bitmask => OperationType::Vector128Integer,
            O::I32x4ExtendLowI16x8S => OperationType::Vector128Integer,
            O::I32x4ExtendHighI16x8S => OperationType::Vector128Integer,
            O::I32x4ExtendLowI16x8U => OperationType::Vector128Integer,
            O::I32x4ExtendHighI16x8U => OperationType::Vector128Integer,
            O::I32x4Shl => OperationType::Vector128Integer,
            O::I32x4ShrS => OperationType::Vector128Integer,
            O::I32x4ShrU => OperationType::Vector128Integer,
            O::I32x4Add => OperationType::Vector128Integer,
            O::I32x4Sub => OperationType::Vector128Integer,
            O::I32x4Mul => OperationType::Vector128Integer,
            O::I32x4MinS => OperationType::Vector128Integer,
            O::I32x4MinU => OperationType::Vector128Integer,
            O::I32x4MaxS => OperationType::Vector128Integer,
            O::I32x4MaxU => OperationType::Vector128Integer,
            O::I32x4DotI16x8S => OperationType::Vector128Integer,
            O::I32x4ExtMulLowI16x8S => OperationType::Vector128Integer,
            O::I32x4ExtMulHighI16x8S => OperationType::Vector128Integer,
            O::I32x4ExtMulLowI16x8U => OperationType::Vector128Integer,
            O::I32x4ExtMulHighI16x8U => OperationType::Vector128Integer,
            O::I64x2Abs => OperationType::Vector128Integer,
            O::I64x2Neg => OperationType::Vector128Integer,
            O::I64x2AllTrue => OperationType::Vector128Integer,
            O::I64x2Bitmask => OperationType::Vector128Integer,
            O::I64x2ExtendLowI32x4S => OperationType::Vector128Integer,
            O::I64x2ExtendHighI32x4S => OperationType::Vector128Integer,
            O::I64x2ExtendLowI32x4U => OperationType::Vector128Integer,
            O::I64x2ExtendHighI32x4U => OperationType::Vector128Integer,
            O::I64x2Shl => OperationType::Vector128Integer,
            O::I64x2ShrS => OperationType::Vector128Integer,
            O::I64x2ShrU => OperationType::Vector128Integer,
            O::I64x2Add => OperationType::Vector128Integer,
            O::I64x2Sub => OperationType::Vector128Integer,
            O::I64x2Mul => OperationType::Vector128Integer,
            O::I64x2ExtMulLowI32x4S => OperationType::Vector128Integer,
            O::I64x2ExtMulHighI32x4S => OperationType::Vector128Integer,
            O::I64x2ExtMulLowI32x4U => OperationType::Vector128Integer,
            O::I64x2ExtMulHighI32x4U => OperationType::Vector128Integer,
            O::I8x16RelaxedLaneselect => OperationType::Vector128Integer,
            O::I16x8RelaxedLaneselect => OperationType::Vector128Integer,
            O::I32x4RelaxedLaneselect => OperationType::Vector128Integer,
            O::I64x2RelaxedLaneselect => OperationType::Vector128Integer,

            O::F32x4Eq => OperationType::Vector128Float,
            O::F32x4Ne => OperationType::Vector128Float,
            O::F32x4Lt => OperationType::Vector128Float,
            O::F32x4Gt => OperationType::Vector128Float,
            O::F32x4Le => OperationType::Vector128Float,
            O::F32x4Ge => OperationType::Vector128Float,
            O::F64x2Eq => OperationType::Vector128Float,
            O::F64x2Ne => OperationType::Vector128Float,
            O::F64x2Lt => OperationType::Vector128Float,
            O::F64x2Gt => OperationType::Vector128Float,
            O::F64x2Le => OperationType::Vector128Float,
            O::F64x2Ge => OperationType::Vector128Float,
            O::F32x4Ceil => OperationType::Vector128Float,
            O::F32x4Floor => OperationType::Vector128Float,
            O::F32x4Trunc => OperationType::Vector128Float,
            O::F32x4Nearest => OperationType::Vector128Float,
            O::F32x4Abs => OperationType::Vector128Float,
            O::F32x4Neg => OperationType::Vector128Float,
            O::F32x4Sqrt => OperationType::Vector128Float,
            O::F32x4Add => OperationType::Vector128Float,
            O::F32x4Sub => OperationType::Vector128Float,
            O::F32x4Mul => OperationType::Vector128Float,
            O::F32x4Div => OperationType::Vector128Float,
            O::F32x4Min => OperationType::Vector128Float,
            O::F32x4Max => OperationType::Vector128Float,
            O::F32x4PMin => OperationType::Vector128Float,
            O::F32x4PMax => OperationType::Vector128Float,
            O::F64x2Ceil => OperationType::Vector128Float,
            O::F64x2Floor => OperationType::Vector128Float,
            O::F64x2Trunc => OperationType::Vector128Float,
            O::F64x2Nearest => OperationType::Vector128Float,
            O::F64x2Abs => OperationType::Vector128Float,
            O::F64x2Neg => OperationType::Vector128Float,
            O::F64x2Sqrt => OperationType::Vector128Float,
            O::F64x2Add => OperationType::Vector128Float,
            O::F64x2Sub => OperationType::Vector128Float,
            O::F64x2Mul => OperationType::Vector128Float,
            O::F64x2Div => OperationType::Vector128Float,
            O::F64x2Min => OperationType::Vector128Float,
            O::F64x2Max => OperationType::Vector128Float,
            O::F64x2PMin => OperationType::Vector128Float,
            O::F64x2PMax => OperationType::Vector128Float,
            O::I32x4TruncSatF32x4S => OperationType::Vector128Float,
            O::I32x4TruncSatF32x4U => OperationType::Vector128Float,
            O::F32x4ConvertI32x4S => OperationType::Vector128Float,
            O::F32x4ConvertI32x4U => OperationType::Vector128Float,
            O::I32x4TruncSatF64x2SZero => OperationType::Vector128Float,
            O::I32x4TruncSatF64x2UZero => OperationType::Vector128Float,
            O::F64x2ConvertLowI32x4S => OperationType::Vector128Float,
            O::F64x2ConvertLowI32x4U => OperationType::Vector128Float,
            O::F32x4DemoteF64x2Zero => OperationType::Vector128Float,
            O::F64x2PromoteLowF32x4 => OperationType::Vector128Float,
            O::I8x16RelaxedSwizzle => OperationType::Vector128Float,
            O::I32x4RelaxedTruncSatF32x4S => OperationType::Vector128Float,
            O::I32x4RelaxedTruncSatF32x4U => OperationType::Vector128Float,
            O::I32x4RelaxedTruncSatF64x2SZero => OperationType::Vector128Float,
            O::I32x4RelaxedTruncSatF64x2UZero => OperationType::Vector128Float,
            O::F32x4RelaxedFma => OperationType::Vector128Float,
            O::F32x4RelaxedFnma => OperationType::Vector128Float,
            O::F64x2RelaxedFma => OperationType::Vector128Float,
            O::F64x2RelaxedFnma => OperationType::Vector128Float,
            O::F32x4RelaxedMin => OperationType::Vector128Float,
            O::F32x4RelaxedMax => OperationType::Vector128Float,
            O::F64x2RelaxedMin => OperationType::Vector128Float,
            O::F64x2RelaxedMax => OperationType::Vector128Float,

            O::I16x8RelaxedQ15mulrS => OperationType::Vector128Integer,
            O::I16x8DotI8x16I7x16S => OperationType::Vector128Integer,
            O::I32x4DotI8x16I7x16AddS => OperationType::Vector128Integer,
            O::F32x4RelaxedDotBf16x8AddF32x4 => OperationType::Vector128Float,
        }
    }

    /// Attempt to quantify the potential runtime/hardware cost of the operation.
    // TODO: These will need attention over time.
    #[tracing::instrument(skip_all)]
    pub fn energy_cost(&self) -> u64 {
        match self {
            // Note I am assuming scalar operations (for integers and floats) have the same
            // cost for 32-bits vs 64-bits, because I am assuming 64-bit hardware.
            OperationType::Bit => 1000,
            OperationType::AddSub => 1000,
            OperationType::Mul => 5000,

            // Treat division as roughly twice as expensive as multiplication, mainly because
            // division is more expensive on modern hardware because it can't be parallelized
            // as efficiently.
            OperationType::Div => 10000,
            OperationType::Load => 3000,
            OperationType::Store => 3000,
            OperationType::Const => 100,

            OperationType::FloatConst => 250,
            OperationType::FloatAdd => 1000,
            OperationType::FloatMul => 5000,
            OperationType::FloatDiv => 10000,
            OperationType::FloatOperation => 3000,
            OperationType::Local => 1500, // Register vs memory lookup, potentially.
            OperationType::Global => 3000,
            OperationType::IntegerComparison => 1000,
            OperationType::FloatComparison => 2000,
            OperationType::Conversion => 3000,
            OperationType::FloatConversion => 3000,
            OperationType::Reinterpretation => 000,
            OperationType::Unreachable => 000,
            OperationType::Nop => 100,

            OperationType::Scope => 500,
            OperationType::Branch => 1000,
            OperationType::Call => 4000,

            OperationType::Memory => 3000,

            OperationType::AtomicBit => 1000,
            OperationType::AtomicXchg => 1000,
            OperationType::AtomicAddSub => 1000,
            OperationType::AtomicLoad => 1000,
            OperationType::AtomicStore => 1000,
            OperationType::AtomicSynchronization => 1000,

            // I am treating all vector operations as the same cost for now, but this will likely
            // need tweaking over time. We may also need more granular classification of the
            // operations but I'm broadly assuming that if there is SIMD hardware available, it
            // will generally be fast.
            // TODO: If we don't have SIMD hardware, we could maybe detect that and make these
            // somewhat more expensive?
            OperationType::Vector128Load => 10000,
            OperationType::Vector128Store => 10000,
            OperationType::Vector128Const => 10000,
            OperationType::Vector128Bit => 10000,
            OperationType::Vector128Integer => 10000,
            OperationType::Vector128Float => 10000,
        }
    }
}
