// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
<<<<<<< HEAD
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from 'spacetimedb';

export type Person = {
  name: string;
};
let _cached_Person_type_value: __AlgebraicTypeType | null = null;

/**
 * An object for generated helper functions.
 */
export const Person = {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    if (_cached_Person_type_value) return _cached_Person_type_value;
    _cached_Person_type_value = __AlgebraicTypeValue.Product({ elements: [] });
    _cached_Person_type_value.value.elements.push({
      name: 'name',
      algebraicType: __AlgebraicTypeValue.String,
    });
    return _cached_Person_type_value;
  },

  serialize(writer: __BinaryWriter, value: Person): void {
    __AlgebraicTypeValue.serializeValue(
      writer,
      Person.getTypeScriptAlgebraicType(),
      value
    );
  },

  deserialize(reader: __BinaryReader): Person {
    return __AlgebraicTypeValue.deserializeValue(
      reader,
      Person.getTypeScriptAlgebraicType()
    );
  },
};

export default Person;
=======
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from 'spacetimedb';

export default __t.object('Person', {
  name: __t.string(),
});
>>>>>>> origin/master
