// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

@file:Suppress("UNUSED", "SpellCheckingInspection")

package module_bindings

import com.clockworklabs.spacetimedb_kotlin_sdk.shared_client.bsatn.BsatnReader
import com.clockworklabs.spacetimedb_kotlin_sdk.shared_client.bsatn.BsatnWriter

data class AddNoteArgs(
    val content: String,
    val tag: String
) {
    fun encode(): ByteArray {
        val writer = BsatnWriter()
        writer.writeString(content)
        writer.writeString(tag)
        return writer.toByteArray()
    }

    companion object {
        fun decode(reader: BsatnReader): AddNoteArgs {
            val content = reader.readString()
            val tag = reader.readString()
            return AddNoteArgs(content, tag)
        }
    }
}

object AddNoteReducer {
    const val REDUCER_NAME = "add_note"
}
