// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

@file:Suppress("UNUSED", "SpellCheckingInspection")

package module_bindings

import com.clockworklabs.spacetimedb_kotlin_sdk.shared_client.bsatn.BsatnReader
import com.clockworklabs.spacetimedb_kotlin_sdk.shared_client.bsatn.BsatnWriter
import com.clockworklabs.spacetimedb_kotlin_sdk.shared_client.type.Identity
import com.clockworklabs.spacetimedb_kotlin_sdk.shared_client.type.ScheduleAt
import com.clockworklabs.spacetimedb_kotlin_sdk.shared_client.type.Timestamp

data class Message(
    val id: ULong,
    val sender: Identity,
    val sent: Timestamp,
    val text: String
) {
    fun encode(writer: BsatnWriter) {
        writer.writeU64(id)
        sender.encode(writer)
        sent.encode(writer)
        writer.writeString(text)
    }

    companion object {
        fun decode(reader: BsatnReader): Message {
            val id = reader.readU64()
            val sender = Identity.decode(reader)
            val sent = Timestamp.decode(reader)
            val text = reader.readString()
            return Message(id, sender, sent, text)
        }
    }
}

data class Note(
    val id: ULong,
    val owner: Identity,
    val content: String,
    val tag: String
) {
    fun encode(writer: BsatnWriter) {
        writer.writeU64(id)
        owner.encode(writer)
        writer.writeString(content)
        writer.writeString(tag)
    }

    companion object {
        fun decode(reader: BsatnReader): Note {
            val id = reader.readU64()
            val owner = Identity.decode(reader)
            val content = reader.readString()
            val tag = reader.readString()
            return Note(id, owner, content, tag)
        }
    }
}

data class Reminder(
    val scheduledId: ULong,
    val scheduledAt: ScheduleAt,
    val text: String,
    val owner: Identity
) {
    fun encode(writer: BsatnWriter) {
        writer.writeU64(scheduledId)
        scheduledAt.encode(writer)
        writer.writeString(text)
        owner.encode(writer)
    }

    companion object {
        fun decode(reader: BsatnReader): Reminder {
            val scheduledId = reader.readU64()
            val scheduledAt = ScheduleAt.decode(reader)
            val text = reader.readString()
            val owner = Identity.decode(reader)
            return Reminder(scheduledId, scheduledAt, text, owner)
        }
    }
}

data class User(
    val identity: Identity,
    val name: String?,
    val online: Boolean
) {
    fun encode(writer: BsatnWriter) {
        identity.encode(writer)
        if (name != null) {
            writer.writeSumTag(0u)
            writer.writeString(name)
        } else {
            writer.writeSumTag(1u)
        }
        writer.writeBool(online)
    }

    companion object {
        fun decode(reader: BsatnReader): User {
            val identity = Identity.decode(reader)
            val name = if (reader.readSumTag().toInt() == 0) reader.readString() else null
            val online = reader.readBool()
            return User(identity, name, online)
        }
    }
}

