// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.8.3 (commit 8e410d2842147bd8e5a32a9589cc00c19f7478e2).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import BuildReducer from "./build_reducer";
import ClearReducer from "./clear_reducer";
import ClearWorldEventsReducer from "./clear_world_events_reducer";
import PlantReducer from "./plant_reducer";
import PresenceHeartbeatReducer from "./presence_heartbeat_reducer";
import PresenceLeaveReducer from "./presence_leave_reducer";
import ResetWorldReducer from "./reset_world_reducer";
import RevokeAccessKeyReducer from "./revoke_access_key_reducer";
import TerraformReducer from "./terraform_reducer";
import UnbuildReducer from "./unbuild_reducer";

// Import all procedure arg schemas
import * as CreateAccessKeyProcedure from "./create_access_key_procedure";
import * as EnsureWorldProcedure from "./ensure_world_procedure";
import * as RotateAccessKeyProcedure from "./rotate_access_key_procedure";

// Import all table schema definitions
import ColonyCellsRow from "./colony_cells_table";
import ColonyEntitiesRow from "./colony_entities_table";
import ColonyGridRow from "./colony_grid_table";
import MyAccessKeysRow from "./my_access_keys_table";
import PresenceEntryRow from "./presence_entry_table";
import WorldRow from "./world_table";
import WorldEventRow from "./world_event_table";

// Import namespace table schema definitions
import ApiKeys_ApiKeyUsageAdminRow from "./apiKeys/api_key_usage_admin_table";
import ApiKeys_ApiKeysAdminRow from "./apiKeys/api_keys_admin_table";
import ApiKeys_MyApiKeysRow from "./apiKeys/my_api_keys_table";

// Import namespace reducer arg schemas
import ApiKeys_AddAdminIdentityReducer from "./apiKeys/add_admin_identity_reducer";
import ApiKeys_RemoveAdminIdentityReducer from "./apiKeys/remove_admin_identity_reducer";
import ApiKeys_RevokeApiKeyReducer from "./apiKeys/revoke_api_key_reducer";
import ApiKeys_RevokeApiKeyForSubjectReducer from "./apiKeys/revoke_api_key_for_subject_reducer";
import ApiKeys_SweepApiKeyUsageReducer from "./apiKeys/sweep_api_key_usage_reducer";

// Import namespace procedure arg schemas
import * as ApiKeys_CreateApiKeyProcedure from "./apiKeys/create_api_key_procedure";
import * as ApiKeys_CreateApiKeyForSubjectProcedure from "./apiKeys/create_api_key_for_subject_procedure";
import * as ApiKeys_RotateApiKeyProcedure from "./apiKeys/rotate_api_key_procedure";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  presenceEntry: __table({
    name: 'presence_entry',
    indexes: [
      { accessor: 'expiresAt', name: 'presence_entry_expires_at_idx_btree', algorithm: 'btree', columns: [
        'expiresAt',
      ] },
      { accessor: 'joinedAt', name: 'presence_entry_joined_at_idx_btree', algorithm: 'btree', columns: [
        'joinedAt',
      ] },
      { accessor: 'key', name: 'presence_entry_key_idx_btree', algorithm: 'btree', columns: [
        'key',
      ] },
      { accessor: 'lastSeenAt', name: 'presence_entry_last_seen_at_idx_btree', algorithm: 'btree', columns: [
        'lastSeenAt',
      ] },
      { accessor: 'scope', name: 'presence_entry_scope_idx_btree', algorithm: 'btree', columns: [
        'scope',
      ] },
      { accessor: 'status', name: 'presence_entry_status_idx_btree', algorithm: 'btree', columns: [
        'status',
      ] },
      { accessor: 'subject', name: 'presence_entry_subject_idx_btree', algorithm: 'btree', columns: [
        'subject',
      ] },
    ],
    constraints: [
      { name: 'presence_entry_key_key', constraint: 'unique', columns: ['key'] },
    ],
  }, PresenceEntryRow),
  world: __table({
    name: 'world',
    indexes: [
      { accessor: 'gridId', name: 'world_grid_id_idx_btree', algorithm: 'btree', columns: [
        'gridId',
      ] },
      { accessor: 'ownerSubject', name: 'world_owner_subject_idx_btree', algorithm: 'btree', columns: [
        'ownerSubject',
      ] },
    ],
    constraints: [
      { name: 'world_owner_subject_key', constraint: 'unique', columns: ['ownerSubject'] },
    ],
  }, WorldRow),
  worldEvent: __table({
    name: 'world_event',
    indexes: [
      { accessor: 'action', name: 'world_event_action_idx_btree', algorithm: 'btree', columns: [
        'action',
      ] },
      { accessor: 'allowed', name: 'world_event_allowed_idx_btree', algorithm: 'btree', columns: [
        'allowed',
      ] },
      { accessor: 'createdAt', name: 'world_event_created_at_idx_btree', algorithm: 'btree', columns: [
        'createdAt',
      ] },
      { accessor: 'eventId', name: 'world_event_event_id_idx_btree', algorithm: 'btree', columns: [
        'eventId',
      ] },
      { accessor: 'ownerSubject', name: 'world_event_owner_subject_idx_btree', algorithm: 'btree', columns: [
        'ownerSubject',
      ] },
    ],
    constraints: [
      { name: 'world_event_event_id_key', constraint: 'unique', columns: ['eventId'] },
    ],
  }, WorldEventRow),
  colonyCells: __table({
    name: 'colony_cells',
    indexes: [
    ],
    constraints: [
    ],
  }, ColonyCellsRow),
  colonyEntities: __table({
    name: 'colony_entities',
    indexes: [
    ],
    constraints: [
    ],
  }, ColonyEntitiesRow),
  colonyGrid: __table({
    name: 'colony_grid',
    indexes: [
    ],
    constraints: [
    ],
  }, ColonyGridRow),
  myAccessKeys: __table({
    name: 'my_access_keys',
    indexes: [
    ],
    constraints: [
    ],
  }, MyAccessKeysRow),
  "apiKeys.api_key_usage_admin": __table({
    name: 'apiKeys.api_key_usage_admin',
    indexes: [
    ],
    constraints: [
    ],
  }, ApiKeys_ApiKeyUsageAdminRow),
  "apiKeys.api_keys_admin": __table({
    name: 'apiKeys.api_keys_admin',
    indexes: [
    ],
    constraints: [
    ],
  }, ApiKeys_ApiKeysAdminRow),
  "apiKeys.my_api_keys": __table({
    name: 'apiKeys.my_api_keys',
    indexes: [
    ],
    constraints: [
    ],
  }, ApiKeys_MyApiKeysRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("build", BuildReducer),
  __reducerSchema("clear", ClearReducer),
  __reducerSchema("clear_world_events", ClearWorldEventsReducer),
  __reducerSchema("plant", PlantReducer),
  __reducerSchema("presence_heartbeat", PresenceHeartbeatReducer),
  __reducerSchema("presence_leave", PresenceLeaveReducer),
  __reducerSchema("reset_world", ResetWorldReducer),
  __reducerSchema("revoke_access_key", RevokeAccessKeyReducer),
  __reducerSchema("terraform", TerraformReducer),
  __reducerSchema("unbuild", UnbuildReducer),
  __reducerSchema("apiKeys.add_admin_identity", ApiKeys_AddAdminIdentityReducer),
  __reducerSchema("apiKeys.remove_admin_identity", ApiKeys_RemoveAdminIdentityReducer),
  __reducerSchema("apiKeys.revoke_api_key", ApiKeys_RevokeApiKeyReducer),
  __reducerSchema("apiKeys.revoke_api_key_for_subject", ApiKeys_RevokeApiKeyForSubjectReducer),
  __reducerSchema("apiKeys.sweep_api_key_usage", ApiKeys_SweepApiKeyUsageReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
  __procedureSchema("create_access_key", CreateAccessKeyProcedure.params, CreateAccessKeyProcedure.returnType),
  __procedureSchema("ensure_world", EnsureWorldProcedure.params, EnsureWorldProcedure.returnType),
  __procedureSchema("rotate_access_key", RotateAccessKeyProcedure.params, RotateAccessKeyProcedure.returnType),
  __procedureSchema("apiKeys.create_api_key", ApiKeys_CreateApiKeyProcedure.params, ApiKeys_CreateApiKeyProcedure.returnType),
  __procedureSchema("apiKeys.create_api_key_for_subject", ApiKeys_CreateApiKeyForSubjectProcedure.params, ApiKeys_CreateApiKeyForSubjectProcedure.returnType),
  __procedureSchema("apiKeys.rotate_api_key", ApiKeys_RotateApiKeyProcedure.params, ApiKeys_RotateApiKeyProcedure.returnType),
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.8.3" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
const __qb = __makeQueryBuilder(tablesSchema.schemaType);
export const tables = {
  presenceEntry: __qb.presenceEntry,
  world: __qb.world,
  worldEvent: __qb.worldEvent,
  colonyCells: __qb.colonyCells,
  colonyEntities: __qb.colonyEntities,
  colonyGrid: __qb.colonyGrid,
  myAccessKeys: __qb.myAccessKeys,
  apiKeys: {
    apiKeyUsageAdmin: __qb["apiKeys.api_key_usage_admin"],
    apiKeysAdmin: __qb["apiKeys.api_keys_admin"],
    myApiKeys: __qb["apiKeys.my_api_keys"],
  },
} as const;

/** The reducers available in this remote SpacetimeDB module. */
const __reducerAccessors = __convertToAccessorMap(reducersSchema.reducersType.reducers);
export const reducers = {
  build: __reducerAccessors.build,
  clear: __reducerAccessors.clear,
  clearWorldEvents: __reducerAccessors.clearWorldEvents,
  plant: __reducerAccessors.plant,
  presenceHeartbeat: __reducerAccessors.presenceHeartbeat,
  presenceLeave: __reducerAccessors.presenceLeave,
  resetWorld: __reducerAccessors.resetWorld,
  revokeAccessKey: __reducerAccessors.revokeAccessKey,
  terraform: __reducerAccessors.terraform,
  unbuild: __reducerAccessors.unbuild,
  apiKeys: {
    addAdminIdentity: __reducerAccessors["apiKeys.addAdminIdentity"],
    removeAdminIdentity: __reducerAccessors["apiKeys.removeAdminIdentity"],
    revokeApiKey: __reducerAccessors["apiKeys.revokeApiKey"],
    revokeApiKeyForSubject: __reducerAccessors["apiKeys.revokeApiKeyForSubject"],
    sweepApiKeyUsage: __reducerAccessors["apiKeys.sweepApiKeyUsage"],
  },
} as const;

/** The procedures available in this remote SpacetimeDB module. */
const __procedureAccessors = __convertToAccessorMap(proceduresSchema.procedures);
export const procedures = {
  createAccessKey: __procedureAccessors.createAccessKey,
  ensureWorld: __procedureAccessors.ensureWorld,
  rotateAccessKey: __procedureAccessors.rotateAccessKey,
  apiKeys: {
    createApiKey: __procedureAccessors["apiKeys.createApiKey"],
    createApiKeyForSubject: __procedureAccessors["apiKeys.createApiKeyForSubject"],
    rotateApiKey: __procedureAccessors["apiKeys.rotateApiKey"],
  },
} as const;

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

