// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  eventId: __t.u64().primaryKey().name("event_id"),
  ownerSubject: __t.string().name("owner_subject"),
  keyPrefix: __t.string().name("key_prefix"),
  action: __t.string(),
  allowed: __t.bool(),
  reason: __t.string(),
  message: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
});
