// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all procedure arg schemas
import * as CreateChatProcedure from "../create_chat_procedure";
import * as GetLlmConfigStatusProcedure from "../get_llm_config_status_procedure";
import * as SendMessageProcedure from "../send_message_procedure";

export type CreateChatArgs = __Infer<typeof CreateChatProcedure.params>;
export type CreateChatResult = __Infer<typeof CreateChatProcedure.returnType>;
export type GetLlmConfigStatusArgs = __Infer<typeof GetLlmConfigStatusProcedure.params>;
export type GetLlmConfigStatusResult = __Infer<typeof GetLlmConfigStatusProcedure.returnType>;
export type SendMessageArgs = __Infer<typeof SendMessageProcedure.params>;
export type SendMessageResult = __Infer<typeof SendMessageProcedure.returnType>;

