// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit be6130a209e59b047af47123db3be3182ede6d36).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "../index";
import { RawScopedTypeNameV9 as __RawScopedTypeNameV9 } from "./raw_scoped_type_name_v_9_type";

export type RawTypeDefV9 = {
  name: __RawScopedTypeNameV9,
  ty: number,
  customOrdering: boolean,
};
export default RawTypeDefV9;

/**
 * A namespace for generated helper functions.
 */
export namespace RawTypeDefV9 {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.Product({
      elements: [
        { name: "name", algebraicType: __RawScopedTypeNameV9.getTypeScriptAlgebraicType()},
        { name: "ty", algebraicType: AlgebraicType.U32},
        { name: "customOrdering", algebraicType: AlgebraicType.Bool},
      ]
    });
  }

  export function serialize(writer: BinaryWriter, value: RawTypeDefV9): void {
    AlgebraicType.serializeValue(writer, RawTypeDefV9.getTypeScriptAlgebraicType(), value);
  }

  export function deserialize(reader: BinaryReader): RawTypeDefV9 {
    return AlgebraicType.deserializeValue(reader, RawTypeDefV9.getTypeScriptAlgebraicType());
  }

}


