// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteProcedures : RemoteBase
    {
        public void ReadMySchema(ProcedureCallback<string> callback)
        {
            // Convert the clean callback to the wrapper callback
            InternalReadMySchema((ctx, result) =>
            {
                if (result.IsSuccess && result.Value != null)
                {
                    callback(ctx, ProcedureCallbackResult<string>.Success(result.Value.Value));
                }
                else
                {
                    callback(ctx, ProcedureCallbackResult<string>.Failure(result.Error!));
                }
            });
        }

        private void InternalReadMySchema(ProcedureCallback<Procedure.ReadMySchema> callback)
        {
            conn.InternalCallProcedure(new Procedure.ReadMySchemaArgs(), callback);
        }

    }

    public abstract partial class Procedure
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ReadMySchema
        {
            [DataMember(Name = "Value")]
            public string Value;

            public ReadMySchema(string Value)
            {
                this.Value = Value;
            }

            public ReadMySchema()
            {
                this.Value = "";
            }
        }
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class ReadMySchemaArgs : Procedure, IProcedureArgs
        {
            string IProcedureArgs.ProcedureName => "read_my_schema";
        }

    }
}
