// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteProcedures : RemoteBase
    {
        public void SortedUuidsInsert(ProcedureCallback<SpacetimeDB.Unit> callback)
        {
            // Convert the clean callback to the wrapper callback
            InternalSortedUuidsInsert((ctx, result) =>
            {
                if (result.IsSuccess && result.Value != null)
                {
                    callback(ctx, ProcedureCallbackResult<SpacetimeDB.Unit>.Success(result.Value.Value));
                }
                else
                {
                    callback(ctx, ProcedureCallbackResult<SpacetimeDB.Unit>.Failure(result.Error!));
                }
            });
        }

        private void InternalSortedUuidsInsert(ProcedureCallback<Procedure.SortedUuidsInsert> callback)
        {
            conn.InternalCallProcedure(new Procedure.SortedUuidsInsertArgs(), callback);
        }

    }

    public abstract partial class Procedure
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SortedUuidsInsert
        {
            [DataMember(Name = "Value")]
            public SpacetimeDB.Unit Value;

            public SortedUuidsInsert(SpacetimeDB.Unit Value)
            {
                this.Value = Value;
            }

            public SortedUuidsInsert()
            {
            }
        }
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class SortedUuidsInsertArgs : Procedure, IProcedureArgs
        {
            string IProcedureArgs.ProcedureName => "sorted_uuids_insert";
        }

    }
}
