[package]
name = "spacetimedb-expr"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file = "LICENSE"
description = "The logical expression representation for the SpacetimeDB query engine"

[dependencies]
anyhow.workspace = true
bigdecimal.workspace = true
derive_more.workspace = true
ethnum.workspace = true
thiserror.workspace = true
spacetimedb-lib.workspace = true
spacetimedb-primitives.workspace = true
spacetimedb-sats.workspace = true
spacetimedb-schema.workspace = true
spacetimedb-sql-parser.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
spacetimedb = { workspace = true, features = ["unstable"] }
spacetimedb-lib.workspace = true
