export { default } from './submodule/index';
export { installAuth } from './submodule/install';
export {
  authSweep,
  getAuthPublicKey,
  linkConnection,
  listMySessions,
  myAuthUser,
  revokeMySession,
  revokeSession,
  setAuthConfig,
  unlinkConnection,
  updateProfile,
  whoami,
} from './submodule/index';

export {
  setAuthConfigParams,
  getPublicKeyPemParams,
  linkConnectionParams,
  unlinkConnectionParams,
  updateProfileParams,
  revokeSessionParams,
  listMySessionsParams,
  revokeMySessionParams,
  passwordSignupHandler,
  parseCookies,
  passwordLoginHandler,
  meHandler,
  logoutHandler,
  refreshHandler,
  googleStartHandler,
  googleCallbackHandler,
  githubStartHandler,
  githubCallbackHandler,
  makeForgotPasswordHandler,
  resetPasswordHandler,
  makeEmailVerifyRequestHandler,
  makeEmailVerifyHandler,
  getCallerUserId,
  publicKeyFromPem,
  verifyJwt,
  type AuthHttpOptions,
  type TrustedProxyHeader,
  type SendMailFn,
  type MailParams,
} from './index';
