export { default } from './mounted/index';
export { installAuth } from './mounted/install';
export {
  authEmailVerify,
  authEmailVerifyRequest,
  authGithubCallback,
  authGithubStart,
  authGoogleCallback,
  authGoogleStart,
  authLogout,
  authMe,
  authPasswordForgot,
  authPasswordLogin,
  authPasswordReset,
  authPasswordSignup,
  authRefresh,
  auth_sweep,
  get_auth_public_key,
  link_connection,
  list_my_sessions,
  myAuthUser,
  revoke_my_session,
  revoke_session,
  set_auth_config,
  unlink_connection,
  update_profile,
  whoami,
} from './mounted/index';

export {
  setAuthConfigParams,
  getPublicKeyPemParams,
  linkConnectionParams,
  linkConnection,
  unlinkConnectionParams,
  updateProfileParams,
  revokeSessionParams,
  listMySessionsParams,
  revokeMySessionParams,
  passwordSignupHandler,
  parseCookies,
  passwordLoginHandler,
  meHandler,
  logoutHandler,
  refreshHandler,
  googleStartHandler,
  googleCallbackHandler,
  githubStartHandler,
  githubCallbackHandler,
  makeForgotPasswordHandler,
  resetPasswordHandler,
  makeEmailVerifyRequestHandler,
  makeEmailVerifyHandler,
  getCallerUserId,
  publicKeyFromPem,
  verifyJwt,
  type AuthHttpOptions,
  type TrustedProxyHeader,
  type SendMailFn,
  type MailParams,
} from './index';
