// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused)]
use super::circle_type::Circle;
use super::vector_2_type::Vector2;
use spacetimedb_sdk::{
    self as __sdk,
    anyhow::{self as __anyhow, Context as _},
    lib as __lib, sats as __sats, ws_messages as __ws,
};

/// Table handle for the table `circle`.
///
/// Obtain a handle from the [`CircleTableAccess::circle`] method on [`super::RemoteTables`],
/// like `ctx.db.circle()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.circle().on_insert(...)`.
pub struct CircleTableHandle<'ctx> {
    imp: __sdk::db_connection::TableHandle<Circle>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `circle`.
///
/// Implemented for [`super::RemoteTables`].
pub trait CircleTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`CircleTableHandle`], which mediates access to the table `circle`.
    fn circle(&self) -> CircleTableHandle<'_>;
}

impl CircleTableAccess for super::RemoteTables {
    fn circle(&self) -> CircleTableHandle<'_> {
        CircleTableHandle {
            imp: self.imp.get_table::<Circle>("circle"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct CircleInsertCallbackId(__sdk::callbacks::CallbackId);
pub struct CircleDeleteCallbackId(__sdk::callbacks::CallbackId);

impl<'ctx> __sdk::table::Table for CircleTableHandle<'ctx> {
    type Row = Circle;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Circle> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = CircleInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CircleInsertCallbackId {
        CircleInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CircleInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = CircleDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CircleDeleteCallbackId {
        CircleDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CircleDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct CircleUpdateCallbackId(__sdk::callbacks::CallbackId);

impl<'ctx> __sdk::table::TableWithPrimaryKey for CircleTableHandle<'ctx> {
    type UpdateCallbackId = CircleUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CircleUpdateCallbackId {
        CircleUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CircleUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __anyhow::Result<__sdk::spacetime_module::TableUpdate<Circle>> {
    __sdk::spacetime_module::TableUpdate::parse_table_update_with_primary_key::<u32>(
        raw_updates,
        |row: &Circle| &row.entity_id,
    )
    .context("Failed to parse table update for table \"circle\"")
}

/// Access to the `entity_id` unique index on the table `circle`,
/// which allows point queries on the field of the same name
/// via the [`CircleEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.circle().entity_id().find(...)`.
pub struct CircleEntityIdUnique<'ctx> {
    imp: __sdk::client_cache::UniqueConstraint<Circle, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> CircleTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `circle`.
    pub fn entity_id(&self) -> CircleEntityIdUnique<'ctx> {
        CircleEntityIdUnique {
            imp: self
                .imp
                .get_unique_constraint::<u32>("entity_id", |row| &row.entity_id),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> CircleEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<Circle> {
        self.imp.find(col_val)
    }
}
