// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit aeeb35f0bbce28430aeeb22691976813dd469e1e).

#include "ModuleBindings/Tables/MessageTable.g.h"
#include "DBCache/UniqueIndex.h"
#include "DBCache/BTreeUniqueIndex.h"
#include "DBCache/ClientCache.h"
#include "DBCache/TableCache.h"

void UMessageTable::PostInitialize()
{
    /** Client cache init and setting up indexes*/
    Data = MakeShared<UClientCache<FMessageType>>();

    TSharedPtr<FTableCache<FMessageType>> MessageTable = Data->GetOrAdd(TableName);

    /***/
}

FTableAppliedDiff<FMessageType> UMessageTable::Update(TArray<FWithBsatn<FMessageType>> InsertsRef, TArray<FWithBsatn<FMessageType>> DeletesRef)
{
    FTableAppliedDiff<FMessageType> Diff = BaseUpdate<FMessageType>(InsertsRef, DeletesRef, Data, TableName);

    return Diff;
}

int32 UMessageTable::Count() const
{
    return GetRowCountFromTable<FMessageType>(Data, TableName);
}

TArray<FMessageType> UMessageTable::Iter() const
{
    return GetAllRowsFromTable<FMessageType>(Data, TableName);
}
