import { ManeuverSlot, ShipClass } from './schema';

export const SHIP_CATALOG = [
  {
    shipId: 'Bulwark',
    shipClass: ShipClass.Bulwark,
    role: 'Heavy defender',
    description:
      'High hull and shields. Wins by absorbing punishment and grinding the opponent down.',
    hull: 160,
    shields: 80,
    attack: 18,
    defense: 7,
    speed: 3,
    critBps: 500,
    dodgeBps: 400,
  },
  {
    shipId: 'Interceptor',
    shipClass: ShipClass.Interceptor,
    role: 'Fast attack',
    description:
      'High damage and speed. Fragile, but dangerous if it can end the duel quickly.',
    hull: 95,
    shields: 45,
    attack: 30,
    defense: 2,
    speed: 8,
    critBps: 1400,
    dodgeBps: 900,
  },
  {
    shipId: 'Phantom',
    shipClass: ShipClass.Phantom,
    role: 'Evasion striker',
    description:
      'Dodge and crit focused. Swingy, slippery, and built around high-risk turns.',
    hull: 110,
    shields: 50,
    attack: 22,
    defense: 3,
    speed: 7,
    critBps: 1200,
    dodgeBps: 2200,
  },
  {
    shipId: 'Artillery',
    shipClass: ShipClass.Artillery,
    role: 'Burst cannon',
    description:
      'Slow, heavy burst damage. Weak shields, but every shot can change the duel.',
    hull: 105,
    shields: 35,
    attack: 38,
    defense: 1,
    speed: 2,
    critBps: 900,
    dodgeBps: 300,
  },
];

export const MANEUVER_CATALOG = [
  {
    shipClass: ShipClass.Bulwark,
    slot: ManeuverSlot.Primary,
    name: 'Cannon Volley',
    description: 'Reliable pressure with no tradeoff.',
    damageBps: 10000,
    defenseBps: 0,
    shieldRestore: 0,
    selfShieldCost: 0,
    critBonusBps: 0,
    dodgeBonusBps: 0,
  },
  {
    shipClass: ShipClass.Bulwark,
    slot: ManeuverSlot.Defensive,
    name: 'Fortify',
    description: 'Restore shields and absorb the next hit.',
    damageBps: 5500,
    defenseBps: 4500,
    shieldRestore: 18,
    selfShieldCost: 0,
    critBonusBps: 0,
    dodgeBonusBps: 0,
  },
  {
    shipClass: ShipClass.Bulwark,
    slot: ManeuverSlot.Risky,
    name: 'Ramming Burn',
    description: 'Spend shields for a heavy strike.',
    damageBps: 15000,
    defenseBps: -1500,
    shieldRestore: 0,
    selfShieldCost: 12,
    critBonusBps: 0,
    dodgeBonusBps: -300,
  },
  {
    shipClass: ShipClass.Interceptor,
    slot: ManeuverSlot.Primary,
    name: 'Pulse Lasers',
    description: 'Fast, clean damage.',
    damageBps: 10500,
    defenseBps: 0,
    shieldRestore: 0,
    selfShieldCost: 0,
    critBonusBps: 0,
    dodgeBonusBps: 0,
  },
  {
    shipClass: ShipClass.Interceptor,
    slot: ManeuverSlot.Defensive,
    name: 'Evasive Roll',
    description: 'Light damage while boosting dodge.',
    damageBps: 6500,
    defenseBps: 0,
    shieldRestore: 6,
    selfShieldCost: 0,
    critBonusBps: 0,
    dodgeBonusBps: 2500,
  },
  {
    shipClass: ShipClass.Interceptor,
    slot: ManeuverSlot.Risky,
    name: 'Afterburn Strike',
    description: 'High crit attack with shield burn.',
    damageBps: 13000,
    defenseBps: 0,
    shieldRestore: 0,
    selfShieldCost: 10,
    critBonusBps: 1800,
    dodgeBonusBps: -500,
  },
  {
    shipClass: ShipClass.Phantom,
    slot: ManeuverSlot.Primary,
    name: 'Phase Lance',
    description: 'A balanced strike with evasive drift.',
    damageBps: 9500,
    defenseBps: 0,
    shieldRestore: 0,
    selfShieldCost: 0,
    critBonusBps: 0,
    dodgeBonusBps: 600,
  },
  {
    shipClass: ShipClass.Phantom,
    slot: ManeuverSlot.Defensive,
    name: 'Cloak',
    description: 'Low damage, huge dodge, and a small shield refresh.',
    damageBps: 4500,
    defenseBps: 0,
    shieldRestore: 4,
    selfShieldCost: 0,
    critBonusBps: 0,
    dodgeBonusBps: 4200,
  },
  {
    shipClass: ShipClass.Phantom,
    slot: ManeuverSlot.Risky,
    name: 'Ambush',
    description: 'Crit-heavy attack that lowers defenses.',
    damageBps: 12500,
    defenseBps: -1000,
    shieldRestore: 0,
    selfShieldCost: 0,
    critBonusBps: 2600,
    dodgeBonusBps: 0,
  },
  {
    shipClass: ShipClass.Artillery,
    slot: ManeuverSlot.Primary,
    name: 'Rail Shot',
    description: 'Slow but punishing direct fire.',
    damageBps: 11500,
    defenseBps: 0,
    shieldRestore: 0,
    selfShieldCost: 0,
    critBonusBps: 0,
    dodgeBonusBps: 0,
  },
  {
    shipClass: ShipClass.Artillery,
    slot: ManeuverSlot.Defensive,
    name: 'Brace',
    description: 'Hold position, restore shields, reduce incoming damage.',
    damageBps: 6500,
    defenseBps: 3500,
    shieldRestore: 10,
    selfShieldCost: 0,
    critBonusBps: 0,
    dodgeBonusBps: 0,
  },
  {
    shipClass: ShipClass.Artillery,
    slot: ManeuverSlot.Risky,
    name: 'Overload Cannon',
    description: 'Massive shot that drains shields and hurts evasiveness.',
    damageBps: 16500,
    defenseBps: 0,
    shieldRestore: 0,
    selfShieldCost: 16,
    critBonusBps: 900,
    dodgeBonusBps: -400,
  },
].map(row => ({
  ...row,
  maneuverId: `${row.shipClass.tag}:${row.slot.tag}`,
}));
