//HintName: TestScheduleIssues.DummyScheduledReducer.cs
// <auto-generated />
#nullable enable

partial struct TestScheduleIssues
{
    private static string __ScheduleDummyScheduledReducerName =>
        field ??= global::SpacetimeDB.Internal.Module.ResolveFunctionName(
            "diag, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
            nameof(DummyScheduledReducer),
            null
        );

    [System.Diagnostics.CodeAnalysis.Experimental("STDB_UNSTABLE")]
    public static void VolatileNonatomicScheduleImmediateDummyScheduledReducer(
        TestScheduleIssues table
    )
    {
        using var stream = new MemoryStream();
        using var writer = new BinaryWriter(stream);
        new TestScheduleIssues.BSATN().Write(writer, table);
        SpacetimeDB.Internal.IReducer.VolatileNonatomicScheduleImmediate(
            __ScheduleDummyScheduledReducerName,
            stream
        );
    }

    private static string?[] __ScheduleDummyScheduledReducerNames =>
        field ??= new string?[global::SpacetimeDB.Internal.Module.InstanceCount];

    private static string __ResolveScheduleDummyScheduledReducerName(int contextInstance)
    {
        var names = __ScheduleDummyScheduledReducerNames;
        if (names[contextInstance] is { } name)
        {
            return name;
        }
        var instance = global::SpacetimeDB.Internal.Module.ResolveInstance(
            contextInstance,
            "diag, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null"
        );
        return names[contextInstance] = names[instance] ??=
            global::SpacetimeDB.Internal.Module.ResolveFunctionName(
                instance,
                nameof(DummyScheduledReducer),
                null
            );
    }

    [System.Diagnostics.CodeAnalysis.Experimental("STDB_UNSTABLE")]
    public static void VolatileNonatomicScheduleImmediateDummyScheduledReducer<__Context>(
        __Context __context,
        TestScheduleIssues table
    )
        where __Context : global::SpacetimeDB.Internal.IModuleContext
    {
        var __name = __ResolveScheduleDummyScheduledReducerName(__context.InstanceId);
        using var stream = new MemoryStream();
        using var writer = new BinaryWriter(stream);
        new TestScheduleIssues.BSATN().Write(writer, table);
        SpacetimeDB.Internal.IReducer.VolatileNonatomicScheduleImmediate(__name, stream);
    }
} // TestScheduleIssues
