//HintName: Reducers.TestDuplicateReducerName.cs
// <auto-generated />
#nullable enable

partial class Reducers
{
    [System.Diagnostics.CodeAnalysis.Experimental("STDB_UNSTABLE")]
    public static void VolatileNonatomicScheduleImmediateTestDuplicateReducerName()
    {
        using var stream = new MemoryStream();
        using var writer = new BinaryWriter(stream);

        SpacetimeDB.Internal.IReducer.VolatileNonatomicScheduleImmediate(
            global::SpacetimeDB.Internal.Module.ResolveName(
                "diag, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
                nameof(TestDuplicateReducerName)
            ),
            stream
        );
    }
} // Reducers
