// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Internal
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class NameMapping
    {
        [DataMember(Name = "source_name")]
        public string SourceName;
        [DataMember(Name = "canonical_name")]
        public string CanonicalName;

        public NameMapping(
            string SourceName,
            string CanonicalName
        )
        {
            this.SourceName = SourceName;
            this.CanonicalName = CanonicalName;
        }

        public NameMapping()
        {
            this.SourceName = "";
            this.CanonicalName = "";
        }
    }
}
