// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Internal
{
    [SpacetimeDB.Type]
    [DataContract]
    public sealed partial class TypeAlias
    {
        [DataMember(Name = "name")]
        public string Name;
        [DataMember(Name = "ty")]
        public uint Ty;

        public TypeAlias(
            string Name,
            uint Ty
        )
        {
            this.Name = Name;
            this.Ty = Ty;
        }

        public TypeAlias()
        {
            this.Name = "";
        }
    }
}
