//HintName: MultiTableRow.InsertMultiData.cs
// <auto-generated />
#nullable enable

partial struct MultiTableRow
{
    private static class __ScheduleInsertMultiDataName
    {
        internal static readonly string Name = global::SpacetimeDB.Internal.Module.ResolveName(
            "server, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
            nameof(InsertMultiData)
        );

        // Prevent eager initialization before the root installs namespace placements.
        static __ScheduleInsertMultiDataName() { }
    }

    [System.Diagnostics.CodeAnalysis.Experimental("STDB_UNSTABLE")]
    public static void VolatileNonatomicScheduleImmediateInsertMultiData(MultiTableRow data)
    {
        using var stream = new MemoryStream();
        using var writer = new BinaryWriter(stream);
        new MultiTableRow.BSATN().Write(writer, data);
        SpacetimeDB.Internal.IReducer.VolatileNonatomicScheduleImmediate(
            __ScheduleInsertMultiDataName.Name,
            stream
        );
    }
} // MultiTableRow
