// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;
using SpacetimeDB.BSATN;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types.@MyAuth
{
    public sealed partial class RemoteTables
    {
        public sealed class NoticeHandle : RemoteEventTableHandle<global::SpacetimeDB.Types.EventContext, Notice>
        {
            public override string RemoteTableName => "MyAuth.notice";
            internal static readonly global::SpacetimeDB.SqlTableName SqlName = new global::SpacetimeDB.SqlTableName(new string[] { "MyAuth" }, "notice");
            protected override global::SpacetimeDB.SqlTableName RemoteSqlTableName => SqlName;

            internal NoticeHandle(global::SpacetimeDB.Types.DbConnection conn) : base(conn)
            {
            }
        }

        public readonly NoticeHandle Notice;
    }

    public sealed class NoticeCols
    {
        public global::SpacetimeDB.Col<Notice, uint> Id { get; }

        public NoticeCols(global::SpacetimeDB.SqlTableName tableName)
        {
            Id = new global::SpacetimeDB.Col<Notice, uint>(tableName, "id");
        }
    }

    public sealed class NoticeIxCols
    {

        public NoticeIxCols(global::SpacetimeDB.SqlTableName tableName)
        {
        }
    }
}
