{
 "title": "Home",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "nodes",
    "query": {
     "query": "label_values(spacetime_worker_process_cpu_usage, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "welcome",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Worker Node Count",
   "type": "timeseries",
   "description": "Displays the number of worker nodes in the cluster over time.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "spacetime_control_worker_nodes", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "Connected Clients",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "spacetime_worker_connected_clients",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Worker CPU Usage",
   "type": "timeseries",
   "description": "Tracks the worker node process's CPU usage over time.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "spacetime_worker_process_cpu_usage",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Databases", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Tx / Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by(database_address) (rate(spacetime_worker_transactions{instance=\"$nodes\"}[$__rate_interval]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Tx Compute Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(spacetime_worker_module_tx_compute_time_sum[30s]) / rate(spacetime_worker_module_tx_compute_time_count[30s])",
     "legendFormat": "{{database_address}}/{{reducer_symbol}}"
    }
   ]
  },
  {
   "title": "Bytes Written / Tx",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(spacetime_worker_tx_size_sum[1m]) / rate(spacetime_worker_tx_size_count[1m])",
     "legendFormat": "{{database_address}}/{{reducer_symbol}}"
    }
   ]
  }
 ]
}