{
 "title": "Session Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Client Sessions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connected clients",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Sessions" } },
   "targets": [
    {
     "expr": "spacetime_worker_connected_clients",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Websocket Message Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(spacetime_websocket_requests[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Websocket Message Sent",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(spacetime_websocket_sent[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Websocket Received Message Size",
   "type": "timeseries",
   "description": "Number of outbound messages sent, per identity.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(spacetime_websocket_request_msg_size_sum[5m]) / rate(spacetime_websocket_request_msg_size_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Websocket Sent Message Size",
   "type": "timeseries",
   "description": "Number of outbound messages sent, per identity.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(spacetime_websocket_sent_msg_size_sum[5m]) / rate(spacetime_websocket_sent_msg_size_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Energy Balance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true
  },
  {
   "title": "Identity Energy Balance",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "Quanta" } },
   "targets": [
    {
     "expr": "spacetime_control_identity_energy_balance",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Identity/Node Energy Budget",
   "type": "timeseries",
   "description": "Per worker node energy budget, by identity/node",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "Quanta" } },
   "targets": [
    {
     "expr": "spacetime_worker_identity_energy_budget",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}