// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#nullable enable

using System;

namespace SpacetimeDB.Types
{
    public static partial class Module
    {
        [SpacetimeDB.Reducer(Name = "emit_test_event")]
        public static partial void EmitTestEvent(SpacetimeDB.ReducerContext ctx, string name, ulong value);
    }
}
