[package]
name = "keynote-benchmarks"
version = "0.1.0"
edition.workspace = true
license-file = "LICENSE"

[lib]
crate-type = ["cdylib"]

[dependencies]
spacetimedb = { path = "../../crates/bindings" }
log = "0.4"
