// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "Types/Builtins.h"
#include "ModuleBindings/Types/IndexedTable2Type.g.h"
#include "Tables/RemoteTable.h"
#include "DBCache/WithBsatn.h"
#include "DBCache/TableHandle.h"
#include "DBCache/TableCache.h"
#include "IndexedTable2Table.g.generated.h"

UCLASS(Blueprintable)
class UIndexedTable2PlayerIdSnazzIndexIndex : public UObject
{
    GENERATED_BODY()

public:
    TArray<FIndexedTable2Type> Filter(const uint32& PlayerId, const float& PlayerSnazz) const
    {
        TArray<FIndexedTable2Type> OutResults;

        LocalCache->FindByMultiKeyBTreeIndex<TTuple<uint32, float>>(
            OutResults,
            TEXT("player_id_snazz_index"),
            MakeTuple(PlayerId, PlayerSnazz)
        );

        return OutResults;
    }

    void SetCache(TSharedPtr<FTableCache<FIndexedTable2Type>> InCache)
    {
        LocalCache = InCache;
    }

private:
    // NOTE: Not exposed to Blueprint because some parameter types are not Blueprint-compatible
    void FilterPlayerIdPlayerSnazz(TArray<FIndexedTable2Type>& OutResults, const uint32& PlayerId, const float& PlayerSnazz)
    {
        OutResults = Filter(PlayerId, PlayerSnazz);
    }

    TSharedPtr<FTableCache<FIndexedTable2Type>> LocalCache;
};

UCLASS(BlueprintType)
class TESTCLIENT_API UIndexedTable2Table : public URemoteTable
{
    GENERATED_BODY()

public:
    UPROPERTY(BlueprintReadOnly)
    UIndexedTable2PlayerIdSnazzIndexIndex* PlayerIdSnazzIndex;

    void PostInitialize();

    /** Update function for indexed_table_2 table*/
    FTableAppliedDiff<FIndexedTable2Type> Update(TArray<FWithBsatn<FIndexedTable2Type>> InsertsRef, TArray<FWithBsatn<FIndexedTable2Type>> DeletesRef);

    /** Number of subscribed rows currently in the cache */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    int32 Count() const;

    /** Return all subscribed rows in the cache */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    TArray<FIndexedTable2Type> Iter() const;

    // Table Events
    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams( 
        FOnIndexedTable2Insert,
        const FEventContext&, Context,
        const FIndexedTable2Type&, NewRow);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams( 
        FOnIndexedTable2Update,
        const FEventContext&, Context,
        const FIndexedTable2Type&, OldRow,
        const FIndexedTable2Type&, NewRow);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams( 
        FOnIndexedTable2Delete,
        const FEventContext&, Context,
        const FIndexedTable2Type&, DeletedRow);

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnIndexedTable2Insert OnInsert;

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnIndexedTable2Update OnUpdate;

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnIndexedTable2Delete OnDelete;

private:
    const FString TableName = TEXT("indexed_table_2");

    TSharedPtr<UClientCache<FIndexedTable2Type>> Data;
};
