// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit aeeb35f0bbce28430aeeb22691976813dd469e1e).

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "Types/Builtins.h"
#include "ModuleBindings/Types/OneByteStructType.g.h"
#include "Tables/RemoteTable.h"
#include "DBCache/WithBsatn.h"
#include "DBCache/TableHandle.h"
#include "DBCache/TableCache.h"
#include "OneByteStructTable.g.generated.h"

UCLASS(BlueprintType)
class TESTCLIENT_API UOneByteStructTable : public URemoteTable
{
    GENERATED_BODY()

public:
    void PostInitialize();

    /** Update function for one_byte_struct table*/
    FTableAppliedDiff<FOneByteStructType> Update(TArray<FWithBsatn<FOneByteStructType>> InsertsRef, TArray<FWithBsatn<FOneByteStructType>> DeletesRef);

    /** Number of subscribed rows currently in the cache */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    int32 Count() const;

    /** Return all subscribed rows in the cache */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    TArray<FOneByteStructType> Iter() const;

    // Table Events
    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams( 
        FOnOneByteStructInsert,
        const FEventContext&, Context,
        const FOneByteStructType&, NewRow);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams( 
        FOnOneByteStructUpdate,
        const FEventContext&, Context,
        const FOneByteStructType&, OldRow,
        const FOneByteStructType&, NewRow);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams( 
        FOnOneByteStructDelete,
        const FEventContext&, Context,
        const FOneByteStructType&, DeletedRow);

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnOneByteStructInsert OnInsert;

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnOneByteStructUpdate OnUpdate;

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnOneByteStructDelete OnDelete;

private:
    const FString TableName = TEXT("one_byte_struct");

    TSharedPtr<UClientCache<FOneByteStructType>> Data;
};
