// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "Types/Builtins.h"
#include "ModuleBindings/Types/OptionUuidType.g.h"
#include "Tables/RemoteTable.h"
#include "DBCache/WithBsatn.h"
#include "DBCache/TableHandle.h"
#include "DBCache/TableCache.h"
#include "OptionUuidTable.g.generated.h"

UCLASS(BlueprintType)
class TESTCLIENT_API UOptionUuidTable : public URemoteTable
{
    GENERATED_BODY()

public:
    void PostInitialize();

    /** Update function for option_uuid table*/
    FTableAppliedDiff<FOptionUuidType> Update(TArray<FWithBsatn<FOptionUuidType>> InsertsRef, TArray<FWithBsatn<FOptionUuidType>> DeletesRef);

    /** Number of subscribed rows currently in the cache */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    int32 Count() const;

    /** Return all subscribed rows in the cache */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    TArray<FOptionUuidType> Iter() const;

    // Table Events
    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams( 
        FOnOptionUuidInsert,
        const FEventContext&, Context,
        const FOptionUuidType&, NewRow);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams( 
        FOnOptionUuidUpdate,
        const FEventContext&, Context,
        const FOptionUuidType&, OldRow,
        const FOptionUuidType&, NewRow);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams( 
        FOnOptionUuidDelete,
        const FEventContext&, Context,
        const FOptionUuidType&, DeletedRow);

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnOptionUuidInsert OnInsert;

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnOptionUuidUpdate OnUpdate;

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnOptionUuidDelete OnDelete;

private:
    const FString TableName = TEXT("option_uuid");

    TSharedPtr<UClientCache<FOptionUuidType>> Data;
};
