// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "Types/Builtins.h"
#include "ModuleBindings/Types/OptionVecOptionI32Type.g.h"
#include "Tables/RemoteTable.h"
#include "DBCache/WithBsatn.h"
#include "DBCache/TableHandle.h"
#include "DBCache/TableCache.h"
#include "OptionVecOptionI32Table.g.generated.h"

UCLASS(BlueprintType)
class TESTCLIENT_API UOptionVecOptionI32Table : public URemoteTable
{
    GENERATED_BODY()

public:
    void PostInitialize();

    /** Update function for option_vec_option_i32 table*/
    FTableAppliedDiff<FOptionVecOptionI32Type> Update(TArray<FWithBsatn<FOptionVecOptionI32Type>> InsertsRef, TArray<FWithBsatn<FOptionVecOptionI32Type>> DeletesRef);

    /** Number of subscribed rows currently in the cache */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    int32 Count() const;

    /** Return all subscribed rows in the cache */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    TArray<FOptionVecOptionI32Type> Iter() const;

    // Table Events
    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams( 
        FOnOptionVecOptionI32Insert,
        const FEventContext&, Context,
        const FOptionVecOptionI32Type&, NewRow);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams( 
        FOnOptionVecOptionI32Update,
        const FEventContext&, Context,
        const FOptionVecOptionI32Type&, OldRow,
        const FOptionVecOptionI32Type&, NewRow);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams( 
        FOnOptionVecOptionI32Delete,
        const FEventContext&, Context,
        const FOptionVecOptionI32Type&, DeletedRow);

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnOptionVecOptionI32Insert OnInsert;

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnOptionVecOptionI32Update OnUpdate;

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnOptionVecOptionI32Delete OnDelete;

private:
    const FString TableName = TEXT("option_vec_option_i32");

    TSharedPtr<UClientCache<FOptionVecOptionI32Type>> Data;
};
