// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "Types/Builtins.h"
#include "ModuleBindings/Types/ResultSimpleEnumI32Type.g.h"
#include "Tables/RemoteTable.h"
#include "DBCache/WithBsatn.h"
#include "DBCache/TableHandle.h"
#include "DBCache/TableCache.h"
#include "ResultSimpleEnumI32Table.g.generated.h"

UCLASS(BlueprintType)
class TESTCLIENT_API UResultSimpleEnumI32Table : public URemoteTable
{
    GENERATED_BODY()

public:
    void PostInitialize();

    /** Update function for result_simple_enum_i32 table*/
    FTableAppliedDiff<FResultSimpleEnumI32Type> Update(TArray<FWithBsatn<FResultSimpleEnumI32Type>> InsertsRef, TArray<FWithBsatn<FResultSimpleEnumI32Type>> DeletesRef);

    /** Number of subscribed rows currently in the cache */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    int32 Count() const;

    /** Return all subscribed rows in the cache */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    TArray<FResultSimpleEnumI32Type> Iter() const;

    // Table Events
    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams( 
        FOnResultSimpleEnumI32Insert,
        const FEventContext&, Context,
        const FResultSimpleEnumI32Type&, NewRow);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams( 
        FOnResultSimpleEnumI32Update,
        const FEventContext&, Context,
        const FResultSimpleEnumI32Type&, OldRow,
        const FResultSimpleEnumI32Type&, NewRow);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams( 
        FOnResultSimpleEnumI32Delete,
        const FEventContext&, Context,
        const FResultSimpleEnumI32Type&, DeletedRow);

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnResultSimpleEnumI32Insert OnInsert;

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnResultSimpleEnumI32Update OnUpdate;

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnResultSimpleEnumI32Delete OnDelete;

private:
    const FString TableName = TEXT("result_simple_enum_i32");

    TSharedPtr<UClientCache<FResultSimpleEnumI32Type>> Data;
};
