// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit aeeb35f0bbce28430aeeb22691976813dd469e1e).

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "Types/Builtins.h"
#include "ModuleBindings/Types/VecEnumWithPayloadType.g.h"
#include "Tables/RemoteTable.h"
#include "DBCache/WithBsatn.h"
#include "DBCache/TableHandle.h"
#include "DBCache/TableCache.h"
#include "VecEnumWithPayloadTable.g.generated.h"

UCLASS(BlueprintType)
class TESTCLIENT_API UVecEnumWithPayloadTable : public URemoteTable
{
    GENERATED_BODY()

public:
    void PostInitialize();

    /** Update function for vec_enum_with_payload table*/
    FTableAppliedDiff<FVecEnumWithPayloadType> Update(TArray<FWithBsatn<FVecEnumWithPayloadType>> InsertsRef, TArray<FWithBsatn<FVecEnumWithPayloadType>> DeletesRef);

    /** Number of subscribed rows currently in the cache */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    int32 Count() const;

    /** Return all subscribed rows in the cache */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    TArray<FVecEnumWithPayloadType> Iter() const;

    // Table Events
    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams( 
        FOnVecEnumWithPayloadInsert,
        const FEventContext&, Context,
        const FVecEnumWithPayloadType&, NewRow);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams( 
        FOnVecEnumWithPayloadUpdate,
        const FEventContext&, Context,
        const FVecEnumWithPayloadType&, OldRow,
        const FVecEnumWithPayloadType&, NewRow);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams( 
        FOnVecEnumWithPayloadDelete,
        const FEventContext&, Context,
        const FVecEnumWithPayloadType&, DeletedRow);

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnVecEnumWithPayloadInsert OnInsert;

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnVecEnumWithPayloadUpdate OnUpdate;

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnVecEnumWithPayloadDelete OnDelete;

private:
    const FString TableName = TEXT("vec_enum_with_payload");

    TSharedPtr<UClientCache<FVecEnumWithPayloadType>> Data;
};
