// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit 263b33e20d9304f44bf4d598dde892211c5c89e8).

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "Types/Builtins.h"
#include "ModuleBindings/Types/VecI64Type.g.h"
#include "Tables/RemoteTable.h"
#include "DBCache/WithBsatn.h"
#include "DBCache/TableHandle.h"
#include "DBCache/TableCache.h"
#include "VecI64Table.g.generated.h"

UCLASS(BlueprintType)
class TESTCLIENT_API UVecI64Table : public URemoteTable
{
    GENERATED_BODY()

public:
    void PostInitialize();

    /** Update function for vec_i64 table*/
    FTableAppliedDiff<FVecI64Type> Update(TArray<FWithBsatn<FVecI64Type>> InsertsRef, TArray<FWithBsatn<FVecI64Type>> DeletesRef);

    /** Number of subscribed rows currently in the cache */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    int32 Count() const;

    /** Return all subscribed rows in the cache */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    TArray<FVecI64Type> Iter() const;

    // Table Events
    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams( 
        FOnVecI64Insert,
        const FEventContext&, Context,
        const FVecI64Type&, NewRow);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams( 
        FOnVecI64Update,
        const FEventContext&, Context,
        const FVecI64Type&, OldRow,
        const FVecI64Type&, NewRow);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams( 
        FOnVecI64Delete,
        const FEventContext&, Context,
        const FVecI64Type&, DeletedRow);

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnVecI64Insert OnInsert;

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnVecI64Update OnUpdate;

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnVecI64Delete OnDelete;

private:
    const FString TableName = TEXT("vec_i64");

    TSharedPtr<UClientCache<FVecI64Type>> Data;
};
