// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit 263b33e20d9304f44bf4d598dde892211c5c89e8).

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "Types/Builtins.h"
#include "ModuleBindings/Types/VecUnitStructType.g.h"
#include "Tables/RemoteTable.h"
#include "DBCache/WithBsatn.h"
#include "DBCache/TableHandle.h"
#include "DBCache/TableCache.h"
#include "VecUnitStructTable.g.generated.h"

UCLASS(BlueprintType)
class TESTCLIENT_API UVecUnitStructTable : public URemoteTable
{
    GENERATED_BODY()

public:
    void PostInitialize();

    /** Update function for vec_unit_struct table*/
    FTableAppliedDiff<FVecUnitStructType> Update(TArray<FWithBsatn<FVecUnitStructType>> InsertsRef, TArray<FWithBsatn<FVecUnitStructType>> DeletesRef);

    /** Number of subscribed rows currently in the cache */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    int32 Count() const;

    /** Return all subscribed rows in the cache */
    UFUNCTION(BlueprintCallable, Category = "SpacetimeDB")
    TArray<FVecUnitStructType> Iter() const;

    // Table Events
    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams( 
        FOnVecUnitStructInsert,
        const FEventContext&, Context,
        const FVecUnitStructType&, NewRow);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams( 
        FOnVecUnitStructUpdate,
        const FEventContext&, Context,
        const FVecUnitStructType&, OldRow,
        const FVecUnitStructType&, NewRow);

    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams( 
        FOnVecUnitStructDelete,
        const FEventContext&, Context,
        const FVecUnitStructType&, DeletedRow);

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnVecUnitStructInsert OnInsert;

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnVecUnitStructUpdate OnUpdate;

    UPROPERTY(BlueprintAssignable, Category = "SpacetimeDB Events")
    FOnVecUnitStructDelete OnDelete;

private:
    const FString TableName = TEXT("vec_unit_struct");

    TSharedPtr<UClientCache<FVecUnitStructType>> Data;
};
