// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#include "ModuleBindings/Tables/LargeTableTable.g.h"
#include "DBCache/UniqueIndex.h"
#include "DBCache/BTreeUniqueIndex.h"
#include "DBCache/ClientCache.h"
#include "DBCache/TableCache.h"

void ULargeTableTable::PostInitialize()
{
    /** Client cache init and setting up indexes*/
    Data = MakeShared<UClientCache<FLargeTableType>>();

    TSharedPtr<FTableCache<FLargeTableType>> LargeTableTable = Data->GetOrAdd(TableName);

    /***/
}

FTableAppliedDiff<FLargeTableType> ULargeTableTable::Update(TArray<FWithBsatn<FLargeTableType>> InsertsRef, TArray<FWithBsatn<FLargeTableType>> DeletesRef)
{
    FTableAppliedDiff<FLargeTableType> Diff = BaseUpdate<FLargeTableType>(InsertsRef, DeletesRef, Data, TableName);

    return Diff;
}

int32 ULargeTableTable::Count() const
{
    return GetRowCountFromTable<FLargeTableType>(Data, TableName);
}

TArray<FLargeTableType> ULargeTableTable::Iter() const
{
    return GetAllRowsFromTable<FLargeTableType>(Data, TableName);
}
