// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit aeeb35f0bbce28430aeeb22691976813dd469e1e).

#include "ModuleBindings/Tables/OneByteStructTable.g.h"
#include "DBCache/UniqueIndex.h"
#include "DBCache/BTreeUniqueIndex.h"
#include "DBCache/ClientCache.h"
#include "DBCache/TableCache.h"

void UOneByteStructTable::PostInitialize()
{
    /** Client cache init and setting up indexes*/
    Data = MakeShared<UClientCache<FOneByteStructType>>();

    TSharedPtr<FTableCache<FOneByteStructType>> OneByteStructTable = Data->GetOrAdd(TableName);

    /***/
}

FTableAppliedDiff<FOneByteStructType> UOneByteStructTable::Update(TArray<FWithBsatn<FOneByteStructType>> InsertsRef, TArray<FWithBsatn<FOneByteStructType>> DeletesRef)
{
    FTableAppliedDiff<FOneByteStructType> Diff = BaseUpdate<FOneByteStructType>(InsertsRef, DeletesRef, Data, TableName);

    return Diff;
}

int32 UOneByteStructTable::Count() const
{
    return GetRowCountFromTable<FOneByteStructType>(Data, TableName);
}

TArray<FOneByteStructType> UOneByteStructTable::Iter() const
{
    return GetAllRowsFromTable<FOneByteStructType>(Data, TableName);
}
