// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit aeeb35f0bbce28430aeeb22691976813dd469e1e).

#include "ModuleBindings/Tables/OneEveryPrimitiveStructTable.g.h"
#include "DBCache/UniqueIndex.h"
#include "DBCache/BTreeUniqueIndex.h"
#include "DBCache/ClientCache.h"
#include "DBCache/TableCache.h"

void UOneEveryPrimitiveStructTable::PostInitialize()
{
    /** Client cache init and setting up indexes*/
    Data = MakeShared<UClientCache<FOneEveryPrimitiveStructType>>();

    TSharedPtr<FTableCache<FOneEveryPrimitiveStructType>> OneEveryPrimitiveStructTable = Data->GetOrAdd(TableName);

    /***/
}

FTableAppliedDiff<FOneEveryPrimitiveStructType> UOneEveryPrimitiveStructTable::Update(TArray<FWithBsatn<FOneEveryPrimitiveStructType>> InsertsRef, TArray<FWithBsatn<FOneEveryPrimitiveStructType>> DeletesRef)
{
    FTableAppliedDiff<FOneEveryPrimitiveStructType> Diff = BaseUpdate<FOneEveryPrimitiveStructType>(InsertsRef, DeletesRef, Data, TableName);

    return Diff;
}

int32 UOneEveryPrimitiveStructTable::Count() const
{
    return GetRowCountFromTable<FOneEveryPrimitiveStructType>(Data, TableName);
}

TArray<FOneEveryPrimitiveStructType> UOneEveryPrimitiveStructTable::Iter() const
{
    return GetAllRowsFromTable<FOneEveryPrimitiveStructType>(Data, TableName);
}
