// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit 263b33e20d9304f44bf4d598dde892211c5c89e8).

#include "ModuleBindings/Tables/OneEveryVecStructTable.g.h"
#include "DBCache/UniqueIndex.h"
#include "DBCache/BTreeUniqueIndex.h"
#include "DBCache/ClientCache.h"
#include "DBCache/TableCache.h"

void UOneEveryVecStructTable::PostInitialize()
{
    /** Client cache init and setting up indexes*/
    Data = MakeShared<UClientCache<FOneEveryVecStructType>>();

    TSharedPtr<FTableCache<FOneEveryVecStructType>> OneEveryVecStructTable = Data->GetOrAdd(TableName);

    /***/
}

FTableAppliedDiff<FOneEveryVecStructType> UOneEveryVecStructTable::Update(TArray<FWithBsatn<FOneEveryVecStructType>> InsertsRef, TArray<FWithBsatn<FOneEveryVecStructType>> DeletesRef)
{
    FTableAppliedDiff<FOneEveryVecStructType> Diff = BaseUpdate<FOneEveryVecStructType>(InsertsRef, DeletesRef, Data, TableName);

    return Diff;
}

int32 UOneEveryVecStructTable::Count() const
{
    return GetRowCountFromTable<FOneEveryVecStructType>(Data, TableName);
}

TArray<FOneEveryVecStructType> UOneEveryVecStructTable::Iter() const
{
    return GetAllRowsFromTable<FOneEveryVecStructType>(Data, TableName);
}
