// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#include "ModuleBindings/Tables/ResultVecI32StringTable.g.h"
#include "DBCache/UniqueIndex.h"
#include "DBCache/BTreeUniqueIndex.h"
#include "DBCache/ClientCache.h"
#include "DBCache/TableCache.h"

void UResultVecI32StringTable::PostInitialize()
{
    /** Client cache init and setting up indexes*/
    Data = MakeShared<UClientCache<FResultVecI32StringType>>();

    TSharedPtr<FTableCache<FResultVecI32StringType>> ResultVecI32StringTable = Data->GetOrAdd(TableName);

    /***/
}

FTableAppliedDiff<FResultVecI32StringType> UResultVecI32StringTable::Update(TArray<FWithBsatn<FResultVecI32StringType>> InsertsRef, TArray<FWithBsatn<FResultVecI32StringType>> DeletesRef)
{
    FTableAppliedDiff<FResultVecI32StringType> Diff = BaseUpdate<FResultVecI32StringType>(InsertsRef, DeletesRef, Data, TableName);

    return Diff;
}

int32 UResultVecI32StringTable::Count() const
{
    return GetRowCountFromTable<FResultVecI32StringType>(Data, TableName);
}

TArray<FResultVecI32StringType> UResultVecI32StringTable::Iter() const
{
    return GetAllRowsFromTable<FResultVecI32StringType>(Data, TableName);
}
