// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#include "ModuleBindings/Tables/UniqueOptionI128Table.g.h"
#include "DBCache/UniqueIndex.h"
#include "DBCache/BTreeUniqueIndex.h"
#include "DBCache/ClientCache.h"
#include "DBCache/TableCache.h"

void UUniqueOptionI128Table::PostInitialize()
{
    /** Client cache init and setting up indexes*/
    Data = MakeShared<UClientCache<FUniqueOptionI128Type>>();

    TSharedPtr<FTableCache<FUniqueOptionI128Type>> UniqueOptionI128Table = Data->GetOrAdd(TableName);
    UniqueOptionI128Table->AddUniqueConstraint<FTestClientOptionalInt128>("n", [](const FUniqueOptionI128Type& Row) -> const FTestClientOptionalInt128& {
        return Row.N; });

    N = NewObject<UUniqueOptionI128NUniqueIndex>(this);
    N->SetCache(UniqueOptionI128Table);

    /***/
}

FTableAppliedDiff<FUniqueOptionI128Type> UUniqueOptionI128Table::Update(TArray<FWithBsatn<FUniqueOptionI128Type>> InsertsRef, TArray<FWithBsatn<FUniqueOptionI128Type>> DeletesRef)
{
    FTableAppliedDiff<FUniqueOptionI128Type> Diff = BaseUpdate<FUniqueOptionI128Type>(InsertsRef, DeletesRef, Data, TableName);

    return Diff;
}

int32 UUniqueOptionI128Table::Count() const
{
    return GetRowCountFromTable<FUniqueOptionI128Type>(Data, TableName);
}

TArray<FUniqueOptionI128Type> UUniqueOptionI128Table::Iter() const
{
    return GetAllRowsFromTable<FUniqueOptionI128Type>(Data, TableName);
}
