// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#include "ModuleBindings/Tables/VecConnectionIdTable.g.h"
#include "DBCache/UniqueIndex.h"
#include "DBCache/BTreeUniqueIndex.h"
#include "DBCache/ClientCache.h"
#include "DBCache/TableCache.h"

void UVecConnectionIdTable::PostInitialize()
{
    /** Client cache init and setting up indexes*/
    Data = MakeShared<UClientCache<FVecConnectionIdType>>();

    TSharedPtr<FTableCache<FVecConnectionIdType>> VecConnectionIdTable = Data->GetOrAdd(TableName);

    /***/
}

FTableAppliedDiff<FVecConnectionIdType> UVecConnectionIdTable::Update(TArray<FWithBsatn<FVecConnectionIdType>> InsertsRef, TArray<FWithBsatn<FVecConnectionIdType>> DeletesRef)
{
    FTableAppliedDiff<FVecConnectionIdType> Diff = BaseUpdate<FVecConnectionIdType>(InsertsRef, DeletesRef, Data, TableName);

    return Diff;
}

int32 UVecConnectionIdTable::Count() const
{
    return GetRowCountFromTable<FVecConnectionIdType>(Data, TableName);
}

TArray<FVecConnectionIdType> UVecConnectionIdTable::Iter() const
{
    return GetAllRowsFromTable<FVecConnectionIdType>(Data, TableName);
}
