// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.2 (commit 263b33e20d9304f44bf4d598dde892211c5c89e8).

#include "ModuleBindings/Tables/VecEnumWithPayloadTable.g.h"
#include "DBCache/UniqueIndex.h"
#include "DBCache/BTreeUniqueIndex.h"
#include "DBCache/ClientCache.h"
#include "DBCache/TableCache.h"

void UVecEnumWithPayloadTable::PostInitialize()
{
    /** Client cache init and setting up indexes*/
    Data = MakeShared<UClientCache<FVecEnumWithPayloadType>>();

    TSharedPtr<FTableCache<FVecEnumWithPayloadType>> VecEnumWithPayloadTable = Data->GetOrAdd(TableName);

    /***/
}

FTableAppliedDiff<FVecEnumWithPayloadType> UVecEnumWithPayloadTable::Update(TArray<FWithBsatn<FVecEnumWithPayloadType>> InsertsRef, TArray<FWithBsatn<FVecEnumWithPayloadType>> DeletesRef)
{
    FTableAppliedDiff<FVecEnumWithPayloadType> Diff = BaseUpdate<FVecEnumWithPayloadType>(InsertsRef, DeletesRef, Data, TableName);

    return Diff;
}

int32 UVecEnumWithPayloadTable::Count() const
{
    return GetRowCountFromTable<FVecEnumWithPayloadType>(Data, TableName);
}

TArray<FVecEnumWithPayloadType> UVecEnumWithPayloadTable::Iter() const
{
    return GetAllRowsFromTable<FVecEnumWithPayloadType>(Data, TableName);
}
