// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#include "ModuleBindings/Tables/VecU256Table.g.h"
#include "DBCache/UniqueIndex.h"
#include "DBCache/BTreeUniqueIndex.h"
#include "DBCache/ClientCache.h"
#include "DBCache/TableCache.h"

void UVecU256Table::PostInitialize()
{
    /** Client cache init and setting up indexes*/
    Data = MakeShared<UClientCache<FVecU256Type>>();

    TSharedPtr<FTableCache<FVecU256Type>> VecU256Table = Data->GetOrAdd(TableName);

    /***/
}

FTableAppliedDiff<FVecU256Type> UVecU256Table::Update(TArray<FWithBsatn<FVecU256Type>> InsertsRef, TArray<FWithBsatn<FVecU256Type>> DeletesRef)
{
    FTableAppliedDiff<FVecU256Type> Diff = BaseUpdate<FVecU256Type>(InsertsRef, DeletesRef, Data, TableName);

    return Diff;
}

int32 UVecU256Table::Count() const
{
    return GetRowCountFromTable<FVecU256Type>(Data, TableName);
}

TArray<FVecU256Type> UVecU256Table::Iter() const
{
    return GetAllRowsFromTable<FVecU256Type>(Data, TableName);
}
