// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

// @ts-ignore
import {
  __SPACETIMEDB__,
  AlgebraicType,
  ProductType,
  ProductTypeElement,
  SumType,
  SumTypeVariant,
  DatabaseTable,
  AlgebraicValue,
  ReducerEvent,
  Identity,
  Address,
  ClientDB,
  SpacetimeDBClient,
} from "../../src/index";

export class Point extends DatabaseTable {
  public static db: ClientDB = __SPACETIMEDB__.clientDB;
  public static tableName = "Point";
  public x: number;
  public y: number;

  public static primaryKey: string | undefined = undefined;

  constructor(x: number, y: number) {
    super();
    this.x = x;
    this.y = y;
  }

  public static serialize(value: Point): object {
    return [value.x, value.y];
  }

  public static getAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("x", AlgebraicType.createU16Type()),
      new ProductTypeElement("y", AlgebraicType.createU16Type()),
    ]);
  }

  public static fromValue(value: AlgebraicValue): Point {
    let productValue = value.asProductValue();
    let __x = productValue.elements[0].asNumber();
    let __y = productValue.elements[1].asNumber();
    return new this(__x, __y);
  }
}

export default Point;
