//HintName: Reducers.DemoProcedure.cs
// <auto-generated />
#nullable enable

partial class Reducers
{
    [System.Diagnostics.CodeAnalysis.Experimental("STDB_UNSTABLE")]
    public static void VolatileNonatomicScheduleImmediateDemoProcedure()
    {
        using var stream = new MemoryStream();
        using var writer = new BinaryWriter(stream);

        SpacetimeDB.Internal.ProcedureExtensions.VolatileNonatomicScheduleImmediate(
            nameof(DemoProcedure),
            stream
        );
    }
} // Reducers
