// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "InsertViewPkPlayer.g.generated.h"

// Reducer arguments struct for InsertViewPkPlayer
USTRUCT(BlueprintType)
struct TESTVIEWPKCLIENT_API FInsertViewPkPlayerArgs
{
    GENERATED_BODY()

    // NOTE: uint64 field not exposed to Blueprint due to non-blueprintable elements
    uint64 Id = 0;

    UPROPERTY(BlueprintReadWrite, Category="SpacetimeDB")
    FString Name;

    FInsertViewPkPlayerArgs() = default;

    FInsertViewPkPlayerArgs(const uint64& InId, const FString& InName)
        : Id(InId), Name(InName)
    {}


    FORCEINLINE bool operator==(const FInsertViewPkPlayerArgs& Other) const
    {
        return Id == Other.Id && Name == Other.Name;
    }
    FORCEINLINE bool operator!=(const FInsertViewPkPlayerArgs& Other) const
    {
        return !(*this == Other);
    }
};

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_STRUCT(FInsertViewPkPlayerArgs, Id, Name);
}

// Reducer class for internal dispatching
UCLASS(BlueprintType)
class TESTVIEWPKCLIENT_API UInsertViewPkPlayerReducer : public UReducerBase
{
    GENERATED_BODY()

public:
    // NOTE: uint64 field not exposed to Blueprint due to non-blueprintable elements
    uint64 Id = 0;
    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    FString Name;

};


