// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/ReducerBase.g.h"
#include "InsertViewPkMembershipSecondary.g.generated.h"

// Reducer arguments struct for InsertViewPkMembershipSecondary
USTRUCT(BlueprintType)
struct TESTVIEWPKCLIENT_API FInsertViewPkMembershipSecondaryArgs
{
    GENERATED_BODY()

    // NOTE: uint64 field not exposed to Blueprint due to non-blueprintable elements
    uint64 Id = 0;

    // NOTE: uint64 field not exposed to Blueprint due to non-blueprintable elements
    uint64 PlayerId = 0;

    FInsertViewPkMembershipSecondaryArgs() = default;

    FInsertViewPkMembershipSecondaryArgs(const uint64& InId, const uint64& InPlayerId)
        : Id(InId), PlayerId(InPlayerId)
    {}


    FORCEINLINE bool operator==(const FInsertViewPkMembershipSecondaryArgs& Other) const
    {
        return Id == Other.Id && PlayerId == Other.PlayerId;
    }
    FORCEINLINE bool operator!=(const FInsertViewPkMembershipSecondaryArgs& Other) const
    {
        return !(*this == Other);
    }
};

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_STRUCT(FInsertViewPkMembershipSecondaryArgs, Id, PlayerId);
}

// Reducer class for internal dispatching
UCLASS(BlueprintType)
class TESTVIEWPKCLIENT_API UInsertViewPkMembershipSecondaryReducer : public UReducerBase
{
    GENERATED_BODY()

public:
    // NOTE: uint64 field not exposed to Blueprint due to non-blueprintable elements
    uint64 Id = 0;
    // NOTE: uint64 field not exposed to Blueprint due to non-blueprintable elements
    uint64 PlayerId = 0;

};


