// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb codegen.

#pragma once

#include <cstdint>
#include <string>
#include <vector>
#include <optional>
#include <memory>
#include "../autogen_base.h"
#include "spacetimedb/bsatn/bsatn.h"
#include "FunctionVisibility.g.h"
#include "ProductType.g.h"
#include "AlgebraicType.g.h"

namespace SpacetimeDB::Internal {

SPACETIMEDB_INTERNAL_PRODUCT_TYPE(RawProcedureDefV10) {
    std::string source_name;
    SpacetimeDB::Internal::ProductType params;
    SpacetimeDB::Internal::AlgebraicType return_type;
    SpacetimeDB::Internal::FunctionVisibility visibility;

    void bsatn_serialize(::SpacetimeDB::bsatn::Writer& writer) const {
        ::SpacetimeDB::bsatn::serialize(writer, source_name);
        ::SpacetimeDB::bsatn::serialize(writer, params);
        ::SpacetimeDB::bsatn::serialize(writer, return_type);
        ::SpacetimeDB::bsatn::serialize(writer, visibility);
    }
    SPACETIMEDB_PRODUCT_TYPE_EQUALITY(source_name, params, return_type, visibility)
};
} // namespace SpacetimeDB::Internal
