// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb codegen.

#pragma once

#include <cstdint>
#include <string>
#include <vector>
#include <optional>
#include <memory>
#include "../autogen_base.h"
#include "spacetimedb/bsatn/bsatn.h"
#include "RawScopedTypeNameV9.g.h"

namespace SpacetimeDB::Internal {

SPACETIMEDB_INTERNAL_PRODUCT_TYPE(RawTypeDefV9) {
    SpacetimeDB::Internal::RawScopedTypeNameV9 name;
    uint32_t ty;
    bool custom_ordering;

    void bsatn_serialize(::SpacetimeDB::bsatn::Writer& writer) const {
        ::SpacetimeDB::bsatn::serialize(writer, name);
        ::SpacetimeDB::bsatn::serialize(writer, ty);
        ::SpacetimeDB::bsatn::serialize(writer, custom_ordering);
    }
    SPACETIMEDB_PRODUCT_TYPE_EQUALITY(name, ty, custom_ordering)
};
} // namespace SpacetimeDB::Internal
