// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb codegen.

#pragma once

#include <cstdint>
#include <string>
#include <vector>
#include <optional>
#include <memory>
#include "../autogen_base.h"
#include "spacetimedb/bsatn/bsatn.h"
#include "ProductTypeElement.g.h"

namespace SpacetimeDB::Internal {

SPACETIMEDB_INTERNAL_PRODUCT_TYPE(ReducerDef) {
    std::string name;
    std::vector<SpacetimeDB::Internal::ProductTypeElement> args;

    void bsatn_serialize(::SpacetimeDB::bsatn::Writer& writer) const {
        ::SpacetimeDB::bsatn::serialize(writer, name);
        ::SpacetimeDB::bsatn::serialize(writer, args);
    }
    SPACETIMEDB_PRODUCT_TYPE_EQUALITY(name, args)
};
} // namespace SpacetimeDB::Internal
