[package]
name = "go-integration-test"
version = "0.1.0"
edition.workspace = true
license-file = "LICENSE"

[lib]
crate-type = ["cdylib"]

[dependencies]
spacetimedb = { path = "../../crates/bindings" }
anyhow.workspace = true
log.workspace = true
serde = { version = "1.0", features = ["derive"] } 