run:
  timeout: 5m
  go: "1.21"
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
    - gosec
    - exportloopref
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - unconvert
    - unparam
    - whitespace

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/clockworklabs/SpacetimeDB/crates/bindings-go
  revive:
    min-confidence: 0.8
    rules:
      - name: var-naming
      - name: package-comments
      - name: exported
      - name: var-declaration
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-naming
      - name: error-return
      - name: error-strings
      - name: increment-decrement
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-naming
      - name: indent-error-flow
  gosec:
    severity: "medium"
    confidence: "medium"

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gosec
        - revive
    # Exclude autogen directory from linting
    - path: internal/autogen/
      linters:
        - all
  max-issues-per-linter: 0
  max-same-issues: 0 