// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#![allow(unused_imports)]
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, i256, ser::Serialize, u256},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address, ScheduleAt,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct Message {
    pub sender: Identity,
    pub sent: u64,
    pub text: String,
}

impl TableType for Message {
    const TABLE_NAME: &'static str = "message";
    type ReducerEvent = super::ReducerEvent;
}

impl Message {
    #[allow(unused)]
    pub fn filter_by_sender(sender: Identity) -> TableIter<Self> {
        Self::filter(|row| row.sender == sender)
    }
    #[allow(unused)]
    pub fn filter_by_sent(sent: u64) -> TableIter<Self> {
        Self::filter(|row| row.sent == sent)
    }
    #[allow(unused)]
    pub fn filter_by_text(text: String) -> TableIter<Self> {
        Self::filter(|row| row.text == text)
    }
}
