// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit 88dc3695d8bc55c081db4a5646a4968da7587405).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SendMessageArgs {
    pub text: String,
}

impl From<SendMessageArgs> for super::Reducer {
    fn from(args: SendMessageArgs) -> Self {
        Self::SendMessage { text: args.text }
    }
}

impl __sdk::InModule for SendMessageArgs {
    type Module = super::RemoteModule;
}

pub struct SendMessageCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `send_message`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait send_message {
    /// Request that the remote module invoke the reducer `send_message` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_send_message`] callbacks.
    fn send_message(&self, text: String) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `send_message`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`SendMessageCallbackId`] can be passed to [`Self::remove_on_send_message`]
    /// to cancel the callback.
    fn on_send_message(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> SendMessageCallbackId;
    /// Cancel a callback previously registered by [`Self::on_send_message`],
    /// causing it not to run in the future.
    fn remove_on_send_message(&self, callback: SendMessageCallbackId);
}

impl send_message for super::RemoteReducers {
    fn send_message(&self, text: String) -> __sdk::Result<()> {
        self.imp.call_reducer("send_message", SendMessageArgs { text })
    }
    fn on_send_message(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> SendMessageCallbackId {
        SendMessageCallbackId(self.imp.on_reducer(
            "send_message",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::SendMessage { text },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, text)
            }),
        ))
    }
    fn remove_on_send_message(&self, callback: SendMessageCallbackId) {
        self.imp.remove_on_reducer("send_message", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `send_message`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_send_message {
    /// Set the call-reducer flags for the reducer `send_message` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn send_message(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_send_message for super::SetReducerFlags {
    fn send_message(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("send_message", flags);
    }
}
