// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.
// <auto-generated />

#nullable enable

using System;
using SpacetimeDB;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;

namespace SpacetimeDB.ClientApi
{
	[SpacetimeDB.Type]
	[DataContract]
	public partial class OneOffQueryResponse
	{
		[DataMember(Name = "message_id")]
		public byte[] MessageId = Array.Empty<byte>();
		[DataMember(Name = "error")]
		public string? Error;
		[DataMember(Name = "tables")]
		public System.Collections.Generic.List<SpacetimeDB.ClientApi.OneOffTable> Tables = new();
		[DataMember(Name = "total_host_execution_duration_micros")]
		public ulong TotalHostExecutionDurationMicros;

	}
}
