// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk as spacetimedb;

#[spacetimedb::table(accessor = indexed_table)]
pub struct IndexedTable {
    #[index(btree)]
    pub player_id: u32,
}
