// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{
	self as __sdk,
	__lib,
	__sats,
	__ws,
};


#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct InsertOneU128Args {
    pub n: u128,
}

impl From<InsertOneU128Args> for super::Reducer {
    fn from(args: InsertOneU128Args) -> Self {
        Self::InsertOneU128 {
            n: args.n,
}
}
}

impl __sdk::InModule for InsertOneU128Args {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `insert_one_u128`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait insert_one_u_128 {
    /// Request that the remote module invoke the reducer `insert_one_u128` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`insert_one_u_128:insert_one_u_128_then`] to run a callback after the reducer completes.
    fn insert_one_u_128(&self, n: u128,
) -> __sdk::Result<()> {
        self.insert_one_u_128_then(n,  |_, _| {})
    }

    /// Request that the remote module invoke the reducer `insert_one_u128` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn insert_one_u_128_then(
        &self,
        n: u128,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl insert_one_u_128 for super::RemoteReducers {
    fn insert_one_u_128_then(
        &self,
        n: u128,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(InsertOneU128Args { n,  }, callback)
    }
}

