// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct InsertCallUuidV4Args {}

impl From<InsertCallUuidV4Args> for super::Reducer {
    fn from(args: InsertCallUuidV4Args) -> Self {
        Self::InsertCallUuidV4
    }
}

impl __sdk::InModule for InsertCallUuidV4Args {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `insert_call_uuid_v_4`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait insert_call_uuid_v_4 {
    /// Request that the remote module invoke the reducer `insert_call_uuid_v_4` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`insert_call_uuid_v_4:insert_call_uuid_v_4_then`] to run a callback after the reducer completes.
    fn insert_call_uuid_v_4(&self) -> __sdk::Result<()> {
        self.insert_call_uuid_v_4_then(|_, _| {})
    }

    /// Request that the remote module invoke the reducer `insert_call_uuid_v_4` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn insert_call_uuid_v_4_then(
        &self,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl insert_call_uuid_v_4 for super::RemoteReducers {
    fn insert_call_uuid_v_4_then(
        &self,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(InsertCallUuidV4Args {}, callback)
    }
}
