// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk as spacetimedb;

use super::every_vec_struct_type::EveryVecStruct;

#[spacetimedb::reducer]
pub fn insert_vec_every_vec_struct(ctx: &spacetimedb::ReducerContext, s: Vec<EveryVecStruct>);
