// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk as spacetimedb;

use super::byte_struct_type::ByteStruct;
use super::enum_with_payload_type::EnumWithPayload;
use super::every_primitive_struct_type::EveryPrimitiveStruct;
use super::every_vec_struct_type::EveryVecStruct;
use super::simple_enum_type::SimpleEnum;
use super::unit_struct_type::UnitStruct;

#[spacetimedb::table(accessor = large_table, public)]
pub struct LargeTable {
    pub a: u8,
    pub b: u16,
    pub c: u32,
    pub d: u64,
    pub e: u128,
    pub f: spacetimedb::u256,
    pub g: i8,
    pub h: i16,
    pub i: i32,
    pub j: i64,
    pub k: i128,
    pub l: spacetimedb::i256,
    pub m: bool,
    pub n: f32,
    pub o: f64,
    pub p: String,
    pub q: SimpleEnum,
    pub r: EnumWithPayload,
    pub s: UnitStruct,
    pub t: ByteStruct,
    pub u: EveryPrimitiveStruct,
    pub v: EveryVecStruct,
}
