// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk as spacetimedb;

#[spacetimedb::table(accessor = option_vec_option_i_32, public)]
pub struct OptionVecOptionI32 {
    pub v: Option<Vec<Option<i32>>>,
}
