// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateUniqueOptionU128Args {
    pub n: Option<u128>,
    pub data: i32,
}

impl From<UpdateUniqueOptionU128Args> for super::Reducer {
    fn from(args: UpdateUniqueOptionU128Args) -> Self {
        Self::UpdateUniqueOptionU128 {
            n: args.n,
            data: args.data,
        }
    }
}

impl __sdk::InModule for UpdateUniqueOptionU128Args {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_unique_option_u_128`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_unique_option_u_128 {
    /// Request that the remote module invoke the reducer `update_unique_option_u_128` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_unique_option_u_128:update_unique_option_u_128_then`] to run a callback after the reducer completes.
    fn update_unique_option_u_128(&self, n: Option<u128>, data: i32) -> __sdk::Result<()> {
        self.update_unique_option_u_128_then(n, data, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_unique_option_u_128` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_unique_option_u_128_then(
        &self,
        n: Option<u128>,
        data: i32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_unique_option_u_128 for super::RemoteReducers {
    fn update_unique_option_u_128_then(
        &self,
        n: Option<u128>,
        data: i32,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(UpdateUniqueOptionU128Args { n, data }, callback)
    }
}
