// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk as spacetimedb;

#[spacetimedb::reducer]
pub fn update_unique_connection_id(ctx: &spacetimedb::ReducerContext, a: spacetimedb::ConnectionId, data: i32);
