// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit ).

#nullable enable

using System;
using SpacetimeDB.ClientApi;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace SpacetimeDB.Types
{
    public sealed partial class RemoteReducers : RemoteBase
    {
        public delegate void SuicideHandler(ReducerEventContext ctx);
        public event SuicideHandler? OnSuicide;

        public void Suicide()
        {
            conn.InternalCallReducer(new Reducer.Suicide(), this.SetCallReducerFlags.SuicideFlags);
        }

        public bool InvokeSuicide(ReducerEventContext ctx, Reducer.Suicide args)
        {
            if (OnSuicide == null)
            {
                if (InternalOnUnhandledReducerError != null)
                {
                    switch (ctx.Event.Status)
                    {
                        case Status.Failed(var reason): InternalOnUnhandledReducerError(ctx, new Exception(reason)); break;
                        case Status.OutOfEnergy(var _): InternalOnUnhandledReducerError(ctx, new Exception("out of energy")); break;
                    }
                }
                return false;
            }
            OnSuicide(
                ctx
            );
            return true;
        }
    }

    public abstract partial class Reducer
    {
        [SpacetimeDB.Type]
        [DataContract]
        public sealed partial class Suicide : Reducer, IReducerArgs
        {
            string IReducerArgs.ReducerName => "suicide";
        }
    }

    public sealed partial class SetReducerFlags
    {
        internal CallReducerFlags SuicideFlags;
        public void Suicide(CallReducerFlags flags) => SuicideFlags = flags;
    }
}
