// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "Types/Builtins.h"
#include "IdentityTokenType.g.generated.h"

USTRUCT(BlueprintType)
struct SPACETIMEDBSDK_API FIdentityTokenType
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FSpacetimeDBIdentity Identity;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FString Token;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FSpacetimeDBConnectionId ConnectionId;

    FORCEINLINE bool operator==(const FIdentityTokenType& Other) const
    {
        return Identity == Other.Identity && Token == Other.Token && ConnectionId == Other.ConnectionId;
    }

    FORCEINLINE bool operator!=(const FIdentityTokenType& Other) const
    {
        return !(*this == Other);
    }
};

/**
 * Custom hash function for FIdentityTokenType.
 * Combines the hashes of all fields that are compared in operator==.
 * @param IdentityTokenType The FIdentityTokenType instance to hash.
 * @return The combined hash value.
 */
FORCEINLINE uint32 GetTypeHash(const FIdentityTokenType& IdentityTokenType)
{
    uint32 Hash = GetTypeHash(IdentityTokenType.Identity);
    Hash = HashCombine(Hash, GetTypeHash(IdentityTokenType.Token));
    Hash = HashCombine(Hash, GetTypeHash(IdentityTokenType.ConnectionId));
    return Hash;
}

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_ENABLE_TARRAY(FIdentityTokenType);

    UE_SPACETIMEDB_STRUCT(FIdentityTokenType, Identity, Token, ConnectionId);
}
