// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/Types/QueryIdType.g.h"
#include "SubscribeMultiType.g.generated.h"

USTRUCT(BlueprintType)
struct SPACETIMEDBSDK_API FSubscribeMultiType
{
    GENERATED_BODY()

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    TArray<FString> QueryStrings;

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 RequestId = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FQueryIdType QueryId;

    FORCEINLINE bool operator==(const FSubscribeMultiType& Other) const
    {
        return QueryStrings == Other.QueryStrings && RequestId == Other.RequestId && QueryId == Other.QueryId;
    }

    FORCEINLINE bool operator!=(const FSubscribeMultiType& Other) const
    {
        return !(*this == Other);
    }
};

/**
 * Custom hash function for FSubscribeMultiType.
 * Combines the hashes of all fields that are compared in operator==.
 * @param SubscribeMultiType The FSubscribeMultiType instance to hash.
 * @return The combined hash value.
 */
FORCEINLINE uint32 GetTypeHash(const FSubscribeMultiType& SubscribeMultiType)
{
    uint32 Hash = GetTypeHash(SubscribeMultiType.QueryStrings);
    Hash = HashCombine(Hash, GetTypeHash(SubscribeMultiType.RequestId));
    Hash = HashCombine(Hash, GetTypeHash(SubscribeMultiType.QueryId));
    return Hash;
}

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_ENABLE_TARRAY(FSubscribeMultiType);

    UE_SPACETIMEDB_STRUCT(FSubscribeMultiType, QueryStrings, RequestId, QueryId);
}
