// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#pragma once
#include "CoreMinimal.h"
#include "BSATN/UESpacetimeDB.h"
#include "ModuleBindings/Types/QueryIdType.g.h"
#include "UnsubscribeType.g.generated.h"

USTRUCT(BlueprintType)
struct SPACETIMEDBSDK_API FUnsubscribeType
{
    GENERATED_BODY()

    // NOTE: uint32 field not exposed to Blueprint due to non-blueprintable elements
    uint32 RequestId = 0;

    UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "SpacetimeDB")
    FQueryIdType QueryId;

    FORCEINLINE bool operator==(const FUnsubscribeType& Other) const
    {
        return RequestId == Other.RequestId && QueryId == Other.QueryId;
    }

    FORCEINLINE bool operator!=(const FUnsubscribeType& Other) const
    {
        return !(*this == Other);
    }
};

/**
 * Custom hash function for FUnsubscribeType.
 * Combines the hashes of all fields that are compared in operator==.
 * @param UnsubscribeType The FUnsubscribeType instance to hash.
 * @return The combined hash value.
 */
FORCEINLINE uint32 GetTypeHash(const FUnsubscribeType& UnsubscribeType)
{
    uint32 Hash = GetTypeHash(UnsubscribeType.RequestId);
    Hash = HashCombine(Hash, GetTypeHash(UnsubscribeType.QueryId));
    return Hash;
}

namespace UE::SpacetimeDB
{
    UE_SPACETIMEDB_ENABLE_TARRAY(FUnsubscribeType);

    UE_SPACETIMEDB_STRUCT(FUnsubscribeType, RequestId, QueryId);
}
