// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.8.3 (commit 8e410d2842147bd8e5a32a9589cc00c19f7478e2).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AdvanceDuelReducer from "./advance_duel_reducer";
import ChooseManeuverReducer from "./choose_maneuver_reducer";
import FallbackToAiReducer from "./fallback_to_ai_reducer";
import FindDuelReducer from "./find_duel_reducer";
import JoinDuelRoomReducer from "./join_duel_room_reducer";
import LeaveDuelReducer from "./leave_duel_reducer";
import QueueAgainReducer from "./queue_again_reducer";
import SelectShipReducer from "./select_ship_reducer";
import SetDisplayNameReducer from "./set_display_name_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import LobbyQueueSummaryRow from "./lobby_queue_summary_table";
import LobbyRankedLeaderboardRow from "./lobby_ranked_leaderboard_table";
import ManeuverCatalogRow from "./maneuver_catalog_table";
import MyDuelCombatantsRow from "./my_duel_combatants_table";
import MyDuelManeuversRow from "./my_duel_maneuvers_table";
import MyDuelRoundLogsRow from "./my_duel_round_logs_table";
import MyDuelsRow from "./my_duels_table";
import MyLobbyRatingsRow from "./my_lobby_ratings_table";
import MyLobbyRoomSeatsRow from "./my_lobby_room_seats_table";
import MyLobbyRoomsRow from "./my_lobby_rooms_table";
import MyLobbyTicketsRow from "./my_lobby_tickets_table";
import MyProfileRow from "./my_profile_table";
import PlayersRow from "./players_table";
import ShipCatalogRow from "./ship_catalog_table";

// Import namespace table schema definitions
import Lobby_LobbyAdminMatchResultsRow from "./lobby/lobby_admin_match_results_table";
import Lobby_LobbyAdminRoomSeatsRow from "./lobby/lobby_admin_room_seats_table";
import Lobby_LobbyAdminRoomsRow from "./lobby/lobby_admin_rooms_table";
import Lobby_LobbyAdminTicketsRow from "./lobby/lobby_admin_tickets_table";
import Lobby_LobbyQueueSummaryRow from "./lobby/lobby_queue_summary_table";
import Lobby_LobbyRankedLeaderboardRow from "./lobby/lobby_ranked_leaderboard_table";
import Lobby_MyLobbyRatingsRow from "./lobby/my_lobby_ratings_table";
import Lobby_MyLobbyRoomSeatsRow from "./lobby/my_lobby_room_seats_table";
import Lobby_MyLobbyRoomsRow from "./lobby/my_lobby_rooms_table";
import Lobby_MyLobbyTicketsRow from "./lobby/my_lobby_tickets_table";

// Import namespace reducer arg schemas
import Lobby_AddAdminIdentityReducer from "./lobby/add_admin_identity_reducer";
import Lobby_CancelTicketReducer from "./lobby/cancel_ticket_reducer";
import Lobby_CloseRoomReducer from "./lobby/close_room_reducer";
import Lobby_ExpireTicketsReducer from "./lobby/expire_tickets_reducer";
import Lobby_JoinQueueReducer from "./lobby/join_queue_reducer";
import Lobby_JoinRankedQueueReducer from "./lobby/join_ranked_queue_reducer";
import Lobby_JoinRoomReducer from "./lobby/join_room_reducer";
import Lobby_LeaveRoomReducer from "./lobby/leave_room_reducer";
import Lobby_RemoveAdminIdentityReducer from "./lobby/remove_admin_identity_reducer";
import Lobby_SetRatingReducer from "./lobby/set_rating_reducer";
import Lobby_UpdateConfigReducer from "./lobby/update_config_reducer";

// Import namespace procedure arg schemas
import * as Lobby_GetLobbyStatusProcedure from "./lobby/get_lobby_status_procedure";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  maneuverCatalog: __table({
    name: 'maneuver_catalog',
    indexes: [
      { accessor: 'maneuverId', name: 'maneuver_catalog_maneuver_id_idx_btree', algorithm: 'btree', columns: [
        'maneuverId',
      ] },
      { accessor: 'byShipClass', name: 'maneuver_catalog_ship_class_idx_btree', algorithm: 'btree', columns: [
        'shipClass',
      ] },
      { accessor: 'bySlot', name: 'maneuver_catalog_slot_idx_btree', algorithm: 'btree', columns: [
        'slot',
      ] },
    ],
    constraints: [
      { name: 'maneuver_catalog_maneuver_id_key', constraint: 'unique', columns: ['maneuverId'] },
    ],
  }, ManeuverCatalogRow),
  shipCatalog: __table({
    name: 'ship_catalog',
    indexes: [
      { accessor: 'byShipClass', name: 'ship_catalog_ship_class_idx_btree', algorithm: 'btree', columns: [
        'shipClass',
      ] },
      { accessor: 'shipId', name: 'ship_catalog_ship_id_idx_btree', algorithm: 'btree', columns: [
        'shipId',
      ] },
    ],
    constraints: [
      { name: 'ship_catalog_ship_id_key', constraint: 'unique', columns: ['shipId'] },
    ],
  }, ShipCatalogRow),
  lobbyQueueSummary: __table({
    name: 'lobby_queue_summary',
    indexes: [
    ],
    constraints: [
    ],
  }, LobbyQueueSummaryRow),
  lobbyRankedLeaderboard: __table({
    name: 'lobby_ranked_leaderboard',
    indexes: [
    ],
    constraints: [
    ],
  }, LobbyRankedLeaderboardRow),
  myDuelCombatants: __table({
    name: 'my_duel_combatants',
    indexes: [
    ],
    constraints: [
    ],
  }, MyDuelCombatantsRow),
  myDuelManeuvers: __table({
    name: 'my_duel_maneuvers',
    indexes: [
    ],
    constraints: [
    ],
  }, MyDuelManeuversRow),
  myDuelRoundLogs: __table({
    name: 'my_duel_round_logs',
    indexes: [
    ],
    constraints: [
    ],
  }, MyDuelRoundLogsRow),
  myDuels: __table({
    name: 'my_duels',
    indexes: [
    ],
    constraints: [
    ],
  }, MyDuelsRow),
  myLobbyRatings: __table({
    name: 'my_lobby_ratings',
    indexes: [
    ],
    constraints: [
    ],
  }, MyLobbyRatingsRow),
  myLobbyRoomSeats: __table({
    name: 'my_lobby_room_seats',
    indexes: [
    ],
    constraints: [
    ],
  }, MyLobbyRoomSeatsRow),
  myLobbyRooms: __table({
    name: 'my_lobby_rooms',
    indexes: [
    ],
    constraints: [
    ],
  }, MyLobbyRoomsRow),
  myLobbyTickets: __table({
    name: 'my_lobby_tickets',
    indexes: [
    ],
    constraints: [
    ],
  }, MyLobbyTicketsRow),
  myProfile: __table({
    name: 'my_profile',
    indexes: [
    ],
    constraints: [
    ],
  }, MyProfileRow),
  players: __table({
    name: 'players',
    indexes: [
    ],
    constraints: [
    ],
  }, PlayersRow),
  "lobby.lobby_admin_match_results": __table({
    name: 'lobby.lobby_admin_match_results',
    indexes: [
    ],
    constraints: [
    ],
  }, Lobby_LobbyAdminMatchResultsRow),
  "lobby.lobby_admin_room_seats": __table({
    name: 'lobby.lobby_admin_room_seats',
    indexes: [
    ],
    constraints: [
    ],
  }, Lobby_LobbyAdminRoomSeatsRow),
  "lobby.lobby_admin_rooms": __table({
    name: 'lobby.lobby_admin_rooms',
    indexes: [
    ],
    constraints: [
    ],
  }, Lobby_LobbyAdminRoomsRow),
  "lobby.lobby_admin_tickets": __table({
    name: 'lobby.lobby_admin_tickets',
    indexes: [
    ],
    constraints: [
    ],
  }, Lobby_LobbyAdminTicketsRow),
  "lobby.lobby_queue_summary": __table({
    name: 'lobby.lobby_queue_summary',
    indexes: [
    ],
    constraints: [
    ],
  }, Lobby_LobbyQueueSummaryRow),
  "lobby.lobby_ranked_leaderboard": __table({
    name: 'lobby.lobby_ranked_leaderboard',
    indexes: [
    ],
    constraints: [
    ],
  }, Lobby_LobbyRankedLeaderboardRow),
  "lobby.my_lobby_ratings": __table({
    name: 'lobby.my_lobby_ratings',
    indexes: [
    ],
    constraints: [
    ],
  }, Lobby_MyLobbyRatingsRow),
  "lobby.my_lobby_room_seats": __table({
    name: 'lobby.my_lobby_room_seats',
    indexes: [
    ],
    constraints: [
    ],
  }, Lobby_MyLobbyRoomSeatsRow),
  "lobby.my_lobby_rooms": __table({
    name: 'lobby.my_lobby_rooms',
    indexes: [
    ],
    constraints: [
    ],
  }, Lobby_MyLobbyRoomsRow),
  "lobby.my_lobby_tickets": __table({
    name: 'lobby.my_lobby_tickets',
    indexes: [
    ],
    constraints: [
    ],
  }, Lobby_MyLobbyTicketsRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("advance_duel", AdvanceDuelReducer),
  __reducerSchema("choose_maneuver", ChooseManeuverReducer),
  __reducerSchema("fallback_to_ai", FallbackToAiReducer),
  __reducerSchema("find_duel", FindDuelReducer),
  __reducerSchema("join_duel_room", JoinDuelRoomReducer),
  __reducerSchema("leave_duel", LeaveDuelReducer),
  __reducerSchema("queue_again", QueueAgainReducer),
  __reducerSchema("select_ship", SelectShipReducer),
  __reducerSchema("set_display_name", SetDisplayNameReducer),
  __reducerSchema("lobby.add_admin_identity", Lobby_AddAdminIdentityReducer),
  __reducerSchema("lobby.cancel_ticket", Lobby_CancelTicketReducer),
  __reducerSchema("lobby.close_room", Lobby_CloseRoomReducer),
  __reducerSchema("lobby.expire_tickets", Lobby_ExpireTicketsReducer),
  __reducerSchema("lobby.join_queue", Lobby_JoinQueueReducer),
  __reducerSchema("lobby.join_ranked_queue", Lobby_JoinRankedQueueReducer),
  __reducerSchema("lobby.join_room", Lobby_JoinRoomReducer),
  __reducerSchema("lobby.leave_room", Lobby_LeaveRoomReducer),
  __reducerSchema("lobby.remove_admin_identity", Lobby_RemoveAdminIdentityReducer),
  __reducerSchema("lobby.set_rating", Lobby_SetRatingReducer),
  __reducerSchema("lobby.update_config", Lobby_UpdateConfigReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
  __procedureSchema("lobby.get_lobby_status", Lobby_GetLobbyStatusProcedure.params, Lobby_GetLobbyStatusProcedure.returnType),
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.8.3" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
const __qb = __makeQueryBuilder(tablesSchema.schemaType);
export const tables = {
  maneuverCatalog: __qb.maneuverCatalog,
  shipCatalog: __qb.shipCatalog,
  lobbyQueueSummary: __qb.lobbyQueueSummary,
  lobbyRankedLeaderboard: __qb.lobbyRankedLeaderboard,
  myDuelCombatants: __qb.myDuelCombatants,
  myDuelManeuvers: __qb.myDuelManeuvers,
  myDuelRoundLogs: __qb.myDuelRoundLogs,
  myDuels: __qb.myDuels,
  myLobbyRatings: __qb.myLobbyRatings,
  myLobbyRoomSeats: __qb.myLobbyRoomSeats,
  myLobbyRooms: __qb.myLobbyRooms,
  myLobbyTickets: __qb.myLobbyTickets,
  myProfile: __qb.myProfile,
  players: __qb.players,
  lobby: {
    lobbyAdminMatchResults: __qb["lobby.lobby_admin_match_results"],
    lobbyAdminRoomSeats: __qb["lobby.lobby_admin_room_seats"],
    lobbyAdminRooms: __qb["lobby.lobby_admin_rooms"],
    lobbyAdminTickets: __qb["lobby.lobby_admin_tickets"],
    lobbyQueueSummary: __qb["lobby.lobby_queue_summary"],
    lobbyRankedLeaderboard: __qb["lobby.lobby_ranked_leaderboard"],
    myLobbyRatings: __qb["lobby.my_lobby_ratings"],
    myLobbyRoomSeats: __qb["lobby.my_lobby_room_seats"],
    myLobbyRooms: __qb["lobby.my_lobby_rooms"],
    myLobbyTickets: __qb["lobby.my_lobby_tickets"],
  },
} as const;

/** The reducers available in this remote SpacetimeDB module. */
const __reducerAccessors = __convertToAccessorMap(reducersSchema.reducersType.reducers);
export const reducers = {
  advanceDuel: __reducerAccessors.advanceDuel,
  chooseManeuver: __reducerAccessors.chooseManeuver,
  fallbackToAi: __reducerAccessors.fallbackToAi,
  findDuel: __reducerAccessors.findDuel,
  joinDuelRoom: __reducerAccessors.joinDuelRoom,
  leaveDuel: __reducerAccessors.leaveDuel,
  queueAgain: __reducerAccessors.queueAgain,
  selectShip: __reducerAccessors.selectShip,
  setDisplayName: __reducerAccessors.setDisplayName,
  lobby: {
    addAdminIdentity: __reducerAccessors["lobby.addAdminIdentity"],
    cancelTicket: __reducerAccessors["lobby.cancelTicket"],
    closeRoom: __reducerAccessors["lobby.closeRoom"],
    expireTickets: __reducerAccessors["lobby.expireTickets"],
    joinQueue: __reducerAccessors["lobby.joinQueue"],
    joinRankedQueue: __reducerAccessors["lobby.joinRankedQueue"],
    joinRoom: __reducerAccessors["lobby.joinRoom"],
    leaveRoom: __reducerAccessors["lobby.leaveRoom"],
    removeAdminIdentity: __reducerAccessors["lobby.removeAdminIdentity"],
    setRating: __reducerAccessors["lobby.setRating"],
    updateConfig: __reducerAccessors["lobby.updateConfig"],
  },
} as const;

/** The procedures available in this remote SpacetimeDB module. */
const __procedureAccessors = __convertToAccessorMap(proceduresSchema.procedures);
export const procedures = {
  lobby: {
    getLobbyStatus: __procedureAccessors["lobby.getLobbyStatus"],
  },
} as const;

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

