name: Check merge labels

on:
  pull_request:
    types: [opened, reopened, labeled, unlabeled]
  merge_group:

permissions: read-all

jobs:
  label_checks:
    name: Check merge labels
    runs-on: ubuntu-latest
    steps:
      - if: github.event_name == 'merge_group'
        run: echo "Merge group run; skipping merge-label checks."

      - if: github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'do not merge')
        run: |
          echo "This is labeled \"Do not merge\"."
          exit 1
