name: Check merge labels

on:
  pull_request:
    types: [labeled, unlabeled]
  merge_group:
permissions: read-all

jobs:
  Check merge labels:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'Do not merge') }}
    runs-on: ubuntu-latest
    steps:
    - run: exit 1

  check_future_release_label:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'release-0.9') }}
    runs-on: ubuntu-latest
    steps:
    - run: exit 1

  check_breaking_change_labels:
    if: |
      contains(github.event.pull_request.labels.*.name, 'abi-break') ||
      contains(github.event.pull_request.labels.*.name, 'breaking change')
    runs-on: ubuntu-latest
    steps:
    - run: exit 1
