name: Check merge labels

on:
  pull_request:
    types: [labeled, unlabeled]
  merge_group:
permissions: read-all

jobs:
  label_checks:
    runs-on: ubuntu-latest
    steps:
      - id: manually_blocked
        if: |
          contains(github.event.pull_request.labels.*.name, 'do not merge')
        run: |
          echo "This is labeled \"Do not merge\"."
          exit 1
