name: Check merge labels

on:
  pull_request:
    types: [labeled, unlabeled]
  merge_group:
permissions: read-all

jobs:
  check:
    if: |
      contains(github.event.pull_request.labels.*.name, 'abi-break') ||
      contains(github.event.pull_request.labels.*.name, 'breaking change') ||
      contains(github.event.pull_request.labels.*.name, 'Do not merge') ||
      contains(github.event.pull_request.labels.*.name, 'release-0.9')
    runs-on: ubuntu-latest
    steps:
    - run: exit 1
