name: Check merge labels

on:
  pull_request:
    types: [labeled, unlabeled]
  merge_group:
permissions: read-all

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - if: |
          contains(github.event.pull_request.labels.*.name, 'do not merge')
        run: echo "::error::This is labeled \"Do not merge\"." && exit 1
      - if: |
          contains(github.event.pull_request.labels.*.name, 'release-0.9')
        run: echo "::error::This is targeted for a future release." && exit 1
      - if: |
          contains(github.event.pull_request.labels.*.name, 'abi-break') ||
          contains(github.event.pull_request.labels.*.name, 'breaking change')
        run: echo "::error::This is a breaking change." && exit 1
