name: Git tree checks

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
  # TODO: This isn't used, probably remove it?
  merge_group:
permissions: read-all

jobs:
  check_base_ref:
    name: Based on `master`
    runs-on: ubuntu-latest
    steps:
      - id: not_based_on_master
        if: |
          github.event_name == 'pull_request' &&
          github.event.pull_request.base.ref != 'master'
        run: |
          echo "This PR is not based on master. Please wait until the base PR merges."
          exit 1

  release_dependencies:
    if: ${{ github.event_name == 'pull_request' }}
    name: Check release dependencies
    runs-on: spacetimedb-new-runner-2
    permissions:
      contents: read
      pull-requests: read
    env:
      GH_TOKEN: ${{ github.token }}
      CARGO_TARGET_DIR: ${{ github.workspace }}/target
    steps:
      - uses: actions/checkout@v4
      - uses: dsherret/rust-toolchain-file@v1
      - name: Check release dependencies
        run: >-
          cargo ci other-workflows check-release-deps
          --repo clockworklabs/SpacetimeDB
          --pr-number "${{ github.event.pull_request.number }}"
