on:
  pull_request:
  push:
    branches:
      - master
  merge_group:
  workflow_dispatch:
    inputs:
      pr_number:
        description: "Pull Request Number"
        required: false
        default: ""

name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.inputs.pr_number || format('sha-{0}', github.sha) }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: read

jobs:
  upload-build-artifacts-linux:
    name: Upload build artifacts (Linux)
    runs-on: spacetimedb-new-runner-2-staging
    timeout-minutes: 15
    env:
      CARGO_TARGET_DIR: ${{ github.workspace }}/target
      RUST_BACKTRACE: full
      ARTIFACT_SUFFIX: linux
      EXE_SUFFIX: ""
    steps: &upload-build-artifact-steps
      - &find-git-ref
        name: Find Git ref
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          PR_NUMBER="${{ github.event.inputs.pr_number || null }}"
          if test -n "${PR_NUMBER}"; then
            GIT_REF="$( gh pr view --repo clockworklabs/SpacetimeDB $PR_NUMBER --json headRefName --jq .headRefName )"
          else
            GIT_REF="${{ github.ref }}"
          fi
          echo "GIT_REF=${GIT_REF}" >>"$GITHUB_ENV"

      - &checkout-sources
        name: Checkout sources
        uses: actions/checkout@v4
        with:
          ref: ${{ env.GIT_REF }}

      - uses: dsherret/rust-toolchain-file@v1
      - &set-default-rust-toolchain
        name: Set default rust toolchain
        run: rustup default $(rustup show active-toolchain | cut -d' ' -f1)

      - name: print some debug info
        run: |
          pwd -P
          find ~ -maxdepth 2

      - name: Build CLI and standalone
        shell: bash
        run: |
          cargo build --timings --release \
            -p spacetimedb-cli \
            -p spacetimedb-standalone \
            --features spacetimedb-standalone/allow_loopback_http_for_tests

      - name: Package build artifacts
        shell: bash
        run: |
          tar -czf build-support.tar.gz \
            "target/release/spacetimedb-cli${EXE_SUFFIX}" \
            "target/release/spacetimedb-standalone${EXE_SUFFIX}"

      - name: Upload Cargo timing reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-cargo-timings-${{ env.ARTIFACT_SUFFIX }}
          path: ${{ env.CARGO_TARGET_DIR }}/cargo-timings/
          if-no-files-found: warn
          overwrite: true
          retention-days: 14

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ env.ARTIFACT_SUFFIX }}
          path: build-support.tar.gz
          if-no-files-found: error
          overwrite: true
          retention-days: 14
