// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from '../index';

export type SubscriptionError = {
  totalHostExecutionDurationMicros: bigint;
  requestId: number | undefined;
  queryId: number | undefined;
  tableId: number | undefined;
  error: string;
};
/**
 * An object for generated helper functions.
 */
export const SubscriptionError = {
  /**
   * A function which returns this type represented as an AlgebraicType.
   * This function is derived from the AlgebraicType used to generate this type.
   */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Product({
      elements: [
        {
          name: 'totalHostExecutionDurationMicros',
          algebraicType: __AlgebraicTypeValue.U64,
        },
        {
          name: 'requestId',
          algebraicType: __AlgebraicTypeValue.createOptionType(
            __AlgebraicTypeValue.U32
          ),
        },
        {
          name: 'queryId',
          algebraicType: __AlgebraicTypeValue.createOptionType(
            __AlgebraicTypeValue.U32
          ),
        },
        {
          name: 'tableId',
          algebraicType: __AlgebraicTypeValue.createOptionType(
            __AlgebraicTypeValue.U32
          ),
        },
        { name: 'error', algebraicType: __AlgebraicTypeValue.String },
      ],
    });
  },

  serialize(writer: __BinaryWriter, value: SubscriptionError): void {
    __AlgebraicTypeValue.serializeValue(
      writer,
      SubscriptionError.getTypeScriptAlgebraicType(),
      value
    );
  },

  deserialize(reader: __BinaryReader): SubscriptionError {
    return __AlgebraicTypeValue.deserializeValue(
      reader,
      SubscriptionError.getTypeScriptAlgebraicType()
    );
  },
};

export default SubscriptionError;
