// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::return_struct_type::ReturnStruct;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
struct ReturnStructArgs {
    pub a: u32,
    pub b: String,
}

impl __sdk::InModule for ReturnStructArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the procedure `return_struct`.
///
/// Implemented for [`super::RemoteProcedures`].
pub trait return_struct {
    fn return_struct(&self, a: u32, b: String) {
        self.return_struct_then(a, b, |_, _| {});
    }

    fn return_struct_then(
        &self,
        a: u32,
        b: String,

        __callback: impl FnOnce(&super::ProcedureEventContext, Result<ReturnStruct, __sdk::InternalError>) + Send + 'static,
    );
}

impl return_struct for super::RemoteProcedures {
    fn return_struct_then(
        &self,
        a: u32,
        b: String,

        __callback: impl FnOnce(&super::ProcedureEventContext, Result<ReturnStruct, __sdk::InternalError>) + Send + 'static,
    ) {
        self.imp.invoke_procedure_with_callback::<_, ReturnStruct>(
            "return_struct",
            ReturnStructArgs { a, b },
            __callback,
        );
    }
}
